// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/card_stock_delete.proto

package debug

import (
	card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardStockDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStockDelete) Reset() {
	*x = CardStockDelete{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStockDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStockDelete) ProtoMessage() {}

func (x *CardStockDelete) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStockDelete.ProtoReflect.Descriptor instead.
func (*CardStockDelete) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescGZIP(), []int{0}
}

type CardStockDelete_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStockDelete_Types) Reset() {
	*x = CardStockDelete_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStockDelete_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStockDelete_Types) ProtoMessage() {}

func (x *CardStockDelete_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStockDelete_Types.ProtoReflect.Descriptor instead.
func (*CardStockDelete_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescGZIP(), []int{0, 0}
}

type CardStockDelete_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*card.CardInstance   `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStockDelete_Types_Request) Reset() {
	*x = CardStockDelete_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStockDelete_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStockDelete_Types_Request) ProtoMessage() {}

func (x *CardStockDelete_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStockDelete_Types_Request.ProtoReflect.Descriptor instead.
func (*CardStockDelete_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CardStockDelete_Types_Request) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CardStockDelete_Types_Request) GetCards() []*card.CardInstance {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CardStockDelete_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CardStocks    []*card.CardStock      `protobuf:"bytes,2,rep,name=card_stocks,json=cardStocks,proto3" json:"card_stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStockDelete_Types_Response) Reset() {
	*x = CardStockDelete_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStockDelete_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStockDelete_Types_Response) ProtoMessage() {}

func (x *CardStockDelete_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStockDelete_Types_Response.ProtoReflect.Descriptor instead.
func (*CardStockDelete_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *CardStockDelete_Types_Response) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CardStockDelete_Types_Response) GetCardStocks() []*card.CardStock {
	if x != nil {
		return x.CardStocks
	}
	return nil
}

var File_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDesc = "" +
	"\n" +
	"Atakasho/schema/lettuce_debug_server/debug/card_stock_delete.proto\x12)takasho.schema.lettuce_debug_server.debug\x1a?takasho/schema/lettuce_server/resource/card/card_instance.proto\x1a<takasho/schema/lettuce_server/resource/card/card_stock.proto\"\x97\x02\n" +
	"\x0fCardStockDelete\x1a\x83\x02\n" +
	"\x05Types\x1aw\n" +
	"\aRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12O\n" +
	"\x05cards\x18\x02 \x03(\v29.takasho.schema.lettuce_server.resource.card.CardInstanceR\x05cards\x1a\x80\x01\n" +
	"\bResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12W\n" +
	"\vcard_stocks\x18\x02 \x03(\v26.takasho.schema.lettuce_server.resource.card.CardStockR\n" +
	"cardStocksBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_goTypes = []any{
	(*CardStockDelete)(nil),                // 0: takasho.schema.lettuce_debug_server.debug.CardStockDelete
	(*CardStockDelete_Types)(nil),          // 1: takasho.schema.lettuce_debug_server.debug.CardStockDelete.Types
	(*CardStockDelete_Types_Request)(nil),  // 2: takasho.schema.lettuce_debug_server.debug.CardStockDelete.Types.Request
	(*CardStockDelete_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.CardStockDelete.Types.Response
	(*card.CardInstance)(nil),              // 4: takasho.schema.lettuce_server.resource.card.CardInstance
	(*card.CardStock)(nil),                 // 5: takasho.schema.lettuce_server.resource.card.CardStock
}
var file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_debug_server.debug.CardStockDelete.Types.Request.cards:type_name -> takasho.schema.lettuce_server.resource.card.CardInstance
	5, // 1: takasho.schema.lettuce_debug_server.debug.CardStockDelete.Types.Response.card_stocks:type_name -> takasho.schema.lettuce_server.resource.card.CardStock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_init() }
func file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_card_stock_delete_proto_depIdxs = nil
}
