// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/feed.proto

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Feed_EnableTimelineRenewal_FullMethodName        = "/takasho.schema.lettuce_debug_server.debug.Feed/EnableTimelineRenewal"
	Feed_AddPower_FullMethodName                     = "/takasho.schema.lettuce_debug_server.debug.Feed/AddPower"
	Feed_DeleteSharedPacks_FullMethodName            = "/takasho.schema.lettuce_debug_server.debug.Feed/DeleteSharedPacks"
	Feed_RenewTimelineWithOptions_FullMethodName     = "/takasho.schema.lettuce_debug_server.debug.Feed/RenewTimelineWithOptions"
	Feed_ChallengeWithOptions_FullMethodName         = "/takasho.schema.lettuce_debug_server.debug.Feed/ChallengeWithOptions"
	Feed_GetCardSpecFeedChallengePool_FullMethodName = "/takasho.schema.lettuce_debug_server.debug.Feed/GetCardSpecFeedChallengePool"
)

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedClient interface {
	EnableTimelineRenewal(ctx context.Context, in *FeedEnableTimelineRenewal_Types_Request, opts ...grpc.CallOption) (*FeedEnableTimelineRenewal_Types_Response, error)
	AddPower(ctx context.Context, in *FeedAddPower_Types_Request, opts ...grpc.CallOption) (*FeedAddPower_Types_Response, error)
	DeleteSharedPacks(ctx context.Context, in *FeedDeleteSharedPacks_Types_Request, opts ...grpc.CallOption) (*FeedDeleteSharedPacks_Types_Response, error)
	RenewTimelineWithOptions(ctx context.Context, in *FeedRenewTimelineWithOptions_Types_Request, opts ...grpc.CallOption) (*FeedRenewTimelineWithOptions_Types_Response, error)
	ChallengeWithOptions(ctx context.Context, in *FeedChallengeWithOptions_Types_Request, opts ...grpc.CallOption) (*FeedChallengeWithOptions_Types_Response, error)
	GetCardSpecFeedChallengePool(ctx context.Context, in *FeedGetCardSpecFeedChallengePool_Types_Request, opts ...grpc.CallOption) (*FeedGetCardSpecFeedChallengePool_Types_Response, error)
}

type feedClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedClient(cc grpc.ClientConnInterface) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) EnableTimelineRenewal(ctx context.Context, in *FeedEnableTimelineRenewal_Types_Request, opts ...grpc.CallOption) (*FeedEnableTimelineRenewal_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedEnableTimelineRenewal_Types_Response)
	err := c.cc.Invoke(ctx, Feed_EnableTimelineRenewal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) AddPower(ctx context.Context, in *FeedAddPower_Types_Request, opts ...grpc.CallOption) (*FeedAddPower_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedAddPower_Types_Response)
	err := c.cc.Invoke(ctx, Feed_AddPower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeleteSharedPacks(ctx context.Context, in *FeedDeleteSharedPacks_Types_Request, opts ...grpc.CallOption) (*FeedDeleteSharedPacks_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedDeleteSharedPacks_Types_Response)
	err := c.cc.Invoke(ctx, Feed_DeleteSharedPacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) RenewTimelineWithOptions(ctx context.Context, in *FeedRenewTimelineWithOptions_Types_Request, opts ...grpc.CallOption) (*FeedRenewTimelineWithOptions_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedRenewTimelineWithOptions_Types_Response)
	err := c.cc.Invoke(ctx, Feed_RenewTimelineWithOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) ChallengeWithOptions(ctx context.Context, in *FeedChallengeWithOptions_Types_Request, opts ...grpc.CallOption) (*FeedChallengeWithOptions_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedChallengeWithOptions_Types_Response)
	err := c.cc.Invoke(ctx, Feed_ChallengeWithOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetCardSpecFeedChallengePool(ctx context.Context, in *FeedGetCardSpecFeedChallengePool_Types_Request, opts ...grpc.CallOption) (*FeedGetCardSpecFeedChallengePool_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedGetCardSpecFeedChallengePool_Types_Response)
	err := c.cc.Invoke(ctx, Feed_GetCardSpecFeedChallengePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
// All implementations must embed UnimplementedFeedServer
// for forward compatibility.
type FeedServer interface {
	EnableTimelineRenewal(context.Context, *FeedEnableTimelineRenewal_Types_Request) (*FeedEnableTimelineRenewal_Types_Response, error)
	AddPower(context.Context, *FeedAddPower_Types_Request) (*FeedAddPower_Types_Response, error)
	DeleteSharedPacks(context.Context, *FeedDeleteSharedPacks_Types_Request) (*FeedDeleteSharedPacks_Types_Response, error)
	RenewTimelineWithOptions(context.Context, *FeedRenewTimelineWithOptions_Types_Request) (*FeedRenewTimelineWithOptions_Types_Response, error)
	ChallengeWithOptions(context.Context, *FeedChallengeWithOptions_Types_Request) (*FeedChallengeWithOptions_Types_Response, error)
	GetCardSpecFeedChallengePool(context.Context, *FeedGetCardSpecFeedChallengePool_Types_Request) (*FeedGetCardSpecFeedChallengePool_Types_Response, error)
	mustEmbedUnimplementedFeedServer()
}

// UnimplementedFeedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedServer struct{}

func (UnimplementedFeedServer) EnableTimelineRenewal(context.Context, *FeedEnableTimelineRenewal_Types_Request) (*FeedEnableTimelineRenewal_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableTimelineRenewal not implemented")
}
func (UnimplementedFeedServer) AddPower(context.Context, *FeedAddPower_Types_Request) (*FeedAddPower_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPower not implemented")
}
func (UnimplementedFeedServer) DeleteSharedPacks(context.Context, *FeedDeleteSharedPacks_Types_Request) (*FeedDeleteSharedPacks_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSharedPacks not implemented")
}
func (UnimplementedFeedServer) RenewTimelineWithOptions(context.Context, *FeedRenewTimelineWithOptions_Types_Request) (*FeedRenewTimelineWithOptions_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewTimelineWithOptions not implemented")
}
func (UnimplementedFeedServer) ChallengeWithOptions(context.Context, *FeedChallengeWithOptions_Types_Request) (*FeedChallengeWithOptions_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ChallengeWithOptions not implemented")
}
func (UnimplementedFeedServer) GetCardSpecFeedChallengePool(context.Context, *FeedGetCardSpecFeedChallengePool_Types_Request) (*FeedGetCardSpecFeedChallengePool_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCardSpecFeedChallengePool not implemented")
}
func (UnimplementedFeedServer) mustEmbedUnimplementedFeedServer() {}
func (UnimplementedFeedServer) testEmbeddedByValue()              {}

// UnsafeFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedServer will
// result in compilation errors.
type UnsafeFeedServer interface {
	mustEmbedUnimplementedFeedServer()
}

func RegisterFeedServer(s grpc.ServiceRegistrar, srv FeedServer) {
	// If the following call panics, it indicates UnimplementedFeedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Feed_ServiceDesc, srv)
}

func _Feed_EnableTimelineRenewal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedEnableTimelineRenewal_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).EnableTimelineRenewal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_EnableTimelineRenewal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).EnableTimelineRenewal(ctx, req.(*FeedEnableTimelineRenewal_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_AddPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedAddPower_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).AddPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_AddPower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).AddPower(ctx, req.(*FeedAddPower_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeleteSharedPacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedDeleteSharedPacks_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeleteSharedPacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_DeleteSharedPacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeleteSharedPacks(ctx, req.(*FeedDeleteSharedPacks_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_RenewTimelineWithOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRenewTimelineWithOptions_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).RenewTimelineWithOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_RenewTimelineWithOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).RenewTimelineWithOptions(ctx, req.(*FeedRenewTimelineWithOptions_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_ChallengeWithOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedChallengeWithOptions_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).ChallengeWithOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_ChallengeWithOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).ChallengeWithOptions(ctx, req.(*FeedChallengeWithOptions_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetCardSpecFeedChallengePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedGetCardSpecFeedChallengePool_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetCardSpecFeedChallengePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetCardSpecFeedChallengePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetCardSpecFeedChallengePool(ctx, req.(*FeedGetCardSpecFeedChallengePool_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Feed_ServiceDesc is the grpc.ServiceDesc for Feed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Feed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_debug_server.debug.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableTimelineRenewal",
			Handler:    _Feed_EnableTimelineRenewal_Handler,
		},
		{
			MethodName: "AddPower",
			Handler:    _Feed_AddPower_Handler,
		},
		{
			MethodName: "DeleteSharedPacks",
			Handler:    _Feed_DeleteSharedPacks_Handler,
		},
		{
			MethodName: "RenewTimelineWithOptions",
			Handler:    _Feed_RenewTimelineWithOptions_Handler,
		},
		{
			MethodName: "ChallengeWithOptions",
			Handler:    _Feed_ChallengeWithOptions_Handler,
		},
		{
			MethodName: "GetCardSpecFeedChallengePool",
			Handler:    _Feed_GetCardSpecFeedChallengePool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_debug_server/debug/feed.proto",
}
