// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/feed_renew_timeline_with_options.proto

package debug

import (
	feed "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/feed"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedRenewTimelineWithOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRenewTimelineWithOptions) Reset() {
	*x = FeedRenewTimelineWithOptions{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRenewTimelineWithOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRenewTimelineWithOptions) ProtoMessage() {}

func (x *FeedRenewTimelineWithOptions) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRenewTimelineWithOptions.ProtoReflect.Descriptor instead.
func (*FeedRenewTimelineWithOptions) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescGZIP(), []int{0}
}

type FeedRenewTimelineWithOptions_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRenewTimelineWithOptions_Types) Reset() {
	*x = FeedRenewTimelineWithOptions_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRenewTimelineWithOptions_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRenewTimelineWithOptions_Types) ProtoMessage() {}

func (x *FeedRenewTimelineWithOptions_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRenewTimelineWithOptions_Types.ProtoReflect.Descriptor instead.
func (*FeedRenewTimelineWithOptions_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescGZIP(), []int{0, 0}
}

type FeedRenewTimelineWithOptions_Types_Request struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	LuckyFeedProbabilityPermill int64                  `protobuf:"varint,1,opt,name=lucky_feed_probability_permill,json=luckyFeedProbabilityPermill,proto3" json:"lucky_feed_probability_permill,omitempty"`
	FreeFeedProbabilityPermill  int64                  `protobuf:"varint,2,opt,name=free_feed_probability_permill,json=freeFeedProbabilityPermill,proto3" json:"free_feed_probability_permill,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FeedRenewTimelineWithOptions_Types_Request) Reset() {
	*x = FeedRenewTimelineWithOptions_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRenewTimelineWithOptions_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRenewTimelineWithOptions_Types_Request) ProtoMessage() {}

func (x *FeedRenewTimelineWithOptions_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRenewTimelineWithOptions_Types_Request.ProtoReflect.Descriptor instead.
func (*FeedRenewTimelineWithOptions_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *FeedRenewTimelineWithOptions_Types_Request) GetLuckyFeedProbabilityPermill() int64 {
	if x != nil {
		return x.LuckyFeedProbabilityPermill
	}
	return 0
}

func (x *FeedRenewTimelineWithOptions_Types_Request) GetFreeFeedProbabilityPermill() int64 {
	if x != nil {
		return x.FreeFeedProbabilityPermill
	}
	return 0
}

type FeedRenewTimelineWithOptions_Types_Response struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timeline       *feed.FeedTimeline     `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
	ChallengePower *feed.ChallengePower   `protobuf:"bytes,2,opt,name=challenge_power,json=challengePower,proto3" json:"challenge_power,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeedRenewTimelineWithOptions_Types_Response) Reset() {
	*x = FeedRenewTimelineWithOptions_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRenewTimelineWithOptions_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRenewTimelineWithOptions_Types_Response) ProtoMessage() {}

func (x *FeedRenewTimelineWithOptions_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRenewTimelineWithOptions_Types_Response.ProtoReflect.Descriptor instead.
func (*FeedRenewTimelineWithOptions_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *FeedRenewTimelineWithOptions_Types_Response) GetTimeline() *feed.FeedTimeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *FeedRenewTimelineWithOptions_Types_Response) GetChallengePower() *feed.ChallengePower {
	if x != nil {
		return x.ChallengePower
	}
	return nil
}

var File_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDesc = "" +
	"\n" +
	"Ptakasho/schema/lettuce_debug_server/debug/feed_renew_timeline_with_options.proto\x12)takasho.schema.lettuce_debug_server.debug\x1aAtakasho/schema/lettuce_server/resource/feed/challenge_power.proto\x1a?takasho/schema/lettuce_server/resource/feed/feed_timeline.proto\"\x86\x03\n" +
	"\x1cFeedRenewTimelineWithOptions\x1a\xe5\x02\n" +
	"\x05Types\x1a\x91\x01\n" +
	"\aRequest\x12C\n" +
	"\x1elucky_feed_probability_permill\x18\x01 \x01(\x03R\x1bluckyFeedProbabilityPermill\x12A\n" +
	"\x1dfree_feed_probability_permill\x18\x02 \x01(\x03R\x1afreeFeedProbabilityPermill\x1a\xc7\x01\n" +
	"\bResponse\x12U\n" +
	"\btimeline\x18\x01 \x01(\v29.takasho.schema.lettuce_server.resource.feed.FeedTimelineR\btimeline\x12d\n" +
	"\x0fchallenge_power\x18\x02 \x01(\v2;.takasho.schema.lettuce_server.resource.feed.ChallengePowerR\x0echallengePowerBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_goTypes = []any{
	(*FeedRenewTimelineWithOptions)(nil),                // 0: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions
	(*FeedRenewTimelineWithOptions_Types)(nil),          // 1: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions.Types
	(*FeedRenewTimelineWithOptions_Types_Request)(nil),  // 2: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions.Types.Request
	(*FeedRenewTimelineWithOptions_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions.Types.Response
	(*feed.FeedTimeline)(nil),                           // 4: takasho.schema.lettuce_server.resource.feed.FeedTimeline
	(*feed.ChallengePower)(nil),                         // 5: takasho.schema.lettuce_server.resource.feed.ChallengePower
}
var file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions.Types.Response.timeline:type_name -> takasho.schema.lettuce_server.resource.feed.FeedTimeline
	5, // 1: takasho.schema.lettuce_debug_server.debug.FeedRenewTimelineWithOptions.Types.Response.challenge_power:type_name -> takasho.schema.lettuce_server.resource.feed.ChallengePower
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_init()
}
func file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_feed_renew_timeline_with_options_proto_depIdxs = nil
}
