// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/friend.proto

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Friend_Add_FullMethodName             = "/takasho.schema.lettuce_debug_server.debug.Friend/Add"
	Friend_AddExisting_FullMethodName     = "/takasho.schema.lettuce_debug_server.debug.Friend/AddExisting"
	Friend_SendRequests_FullMethodName    = "/takasho.schema.lettuce_debug_server.debug.Friend/SendRequests"
	Friend_ApproveRequests_FullMethodName = "/takasho.schema.lettuce_debug_server.debug.Friend/ApproveRequests"
	Friend_CancelRequests_FullMethodName  = "/takasho.schema.lettuce_debug_server.debug.Friend/CancelRequests"
	Friend_RejectRequests_FullMethodName  = "/takasho.schema.lettuce_debug_server.debug.Friend/RejectRequests"
)

// FriendClient is the client API for Friend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendClient interface {
	Add(ctx context.Context, in *FriendAdd_Types_Request, opts ...grpc.CallOption) (*FriendAdd_Types_Response, error)
	AddExisting(ctx context.Context, in *FriendAddExisting_Types_Request, opts ...grpc.CallOption) (*FriendAddExisting_Types_Response, error)
	SendRequests(ctx context.Context, in *FriendSendRequests_Types_Request, opts ...grpc.CallOption) (*FriendSendRequests_Types_Response, error)
	ApproveRequests(ctx context.Context, in *FriendApproveRequests_Types_Request, opts ...grpc.CallOption) (*FriendApproveRequests_Types_Response, error)
	CancelRequests(ctx context.Context, in *FriendCancelRequests_Types_Request, opts ...grpc.CallOption) (*FriendCancelRequests_Types_Response, error)
	RejectRequests(ctx context.Context, in *FriendRejectRequests_Types_Request, opts ...grpc.CallOption) (*FriendRejectRequests_Types_Response, error)
}

type friendClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendClient(cc grpc.ClientConnInterface) FriendClient {
	return &friendClient{cc}
}

func (c *friendClient) Add(ctx context.Context, in *FriendAdd_Types_Request, opts ...grpc.CallOption) (*FriendAdd_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendAdd_Types_Response)
	err := c.cc.Invoke(ctx, Friend_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) AddExisting(ctx context.Context, in *FriendAddExisting_Types_Request, opts ...grpc.CallOption) (*FriendAddExisting_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendAddExisting_Types_Response)
	err := c.cc.Invoke(ctx, Friend_AddExisting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) SendRequests(ctx context.Context, in *FriendSendRequests_Types_Request, opts ...grpc.CallOption) (*FriendSendRequests_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendSendRequests_Types_Response)
	err := c.cc.Invoke(ctx, Friend_SendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) ApproveRequests(ctx context.Context, in *FriendApproveRequests_Types_Request, opts ...grpc.CallOption) (*FriendApproveRequests_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendApproveRequests_Types_Response)
	err := c.cc.Invoke(ctx, Friend_ApproveRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) CancelRequests(ctx context.Context, in *FriendCancelRequests_Types_Request, opts ...grpc.CallOption) (*FriendCancelRequests_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendCancelRequests_Types_Response)
	err := c.cc.Invoke(ctx, Friend_CancelRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) RejectRequests(ctx context.Context, in *FriendRejectRequests_Types_Request, opts ...grpc.CallOption) (*FriendRejectRequests_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendRejectRequests_Types_Response)
	err := c.cc.Invoke(ctx, Friend_RejectRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServer is the server API for Friend service.
// All implementations must embed UnimplementedFriendServer
// for forward compatibility.
type FriendServer interface {
	Add(context.Context, *FriendAdd_Types_Request) (*FriendAdd_Types_Response, error)
	AddExisting(context.Context, *FriendAddExisting_Types_Request) (*FriendAddExisting_Types_Response, error)
	SendRequests(context.Context, *FriendSendRequests_Types_Request) (*FriendSendRequests_Types_Response, error)
	ApproveRequests(context.Context, *FriendApproveRequests_Types_Request) (*FriendApproveRequests_Types_Response, error)
	CancelRequests(context.Context, *FriendCancelRequests_Types_Request) (*FriendCancelRequests_Types_Response, error)
	RejectRequests(context.Context, *FriendRejectRequests_Types_Request) (*FriendRejectRequests_Types_Response, error)
	mustEmbedUnimplementedFriendServer()
}

// UnimplementedFriendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServer struct{}

func (UnimplementedFriendServer) Add(context.Context, *FriendAdd_Types_Request) (*FriendAdd_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedFriendServer) AddExisting(context.Context, *FriendAddExisting_Types_Request) (*FriendAddExisting_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExisting not implemented")
}
func (UnimplementedFriendServer) SendRequests(context.Context, *FriendSendRequests_Types_Request) (*FriendSendRequests_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRequests not implemented")
}
func (UnimplementedFriendServer) ApproveRequests(context.Context, *FriendApproveRequests_Types_Request) (*FriendApproveRequests_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveRequests not implemented")
}
func (UnimplementedFriendServer) CancelRequests(context.Context, *FriendCancelRequests_Types_Request) (*FriendCancelRequests_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRequests not implemented")
}
func (UnimplementedFriendServer) RejectRequests(context.Context, *FriendRejectRequests_Types_Request) (*FriendRejectRequests_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRequests not implemented")
}
func (UnimplementedFriendServer) mustEmbedUnimplementedFriendServer() {}
func (UnimplementedFriendServer) testEmbeddedByValue()                {}

// UnsafeFriendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServer will
// result in compilation errors.
type UnsafeFriendServer interface {
	mustEmbedUnimplementedFriendServer()
}

func RegisterFriendServer(s grpc.ServiceRegistrar, srv FriendServer) {
	// If the following call panics, it indicates UnimplementedFriendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Friend_ServiceDesc, srv)
}

func _Friend_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendAdd_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).Add(ctx, req.(*FriendAdd_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_AddExisting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendAddExisting_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).AddExisting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_AddExisting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).AddExisting(ctx, req.(*FriendAddExisting_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_SendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendSendRequests_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).SendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_SendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).SendRequests(ctx, req.(*FriendSendRequests_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_ApproveRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendApproveRequests_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).ApproveRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_ApproveRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).ApproveRequests(ctx, req.(*FriendApproveRequests_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_CancelRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendCancelRequests_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).CancelRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_CancelRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).CancelRequests(ctx, req.(*FriendCancelRequests_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_RejectRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRejectRequests_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).RejectRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friend_RejectRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).RejectRequests(ctx, req.(*FriendRejectRequests_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Friend_ServiceDesc is the grpc.ServiceDesc for Friend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_debug_server.debug.Friend",
	HandlerType: (*FriendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Friend_Add_Handler,
		},
		{
			MethodName: "AddExisting",
			Handler:    _Friend_AddExisting_Handler,
		},
		{
			MethodName: "SendRequests",
			Handler:    _Friend_SendRequests_Handler,
		},
		{
			MethodName: "ApproveRequests",
			Handler:    _Friend_ApproveRequests_Handler,
		},
		{
			MethodName: "CancelRequests",
			Handler:    _Friend_CancelRequests_Handler,
		},
		{
			MethodName: "RejectRequests",
			Handler:    _Friend_RejectRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_debug_server/debug/friend.proto",
}
