// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/item_shop_add_purchase_summaries.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemShopAddPurchaseSummaries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries) Reset() {
	*x = ItemShopAddPurchaseSummaries{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0}
}

type ItemShopAddPurchaseSummaries_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries_Types) Reset() {
	*x = ItemShopAddPurchaseSummaries_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries_Types) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries_Types.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0, 0}
}

type ItemShopAddPurchaseSummaries_Types_Request struct {
	state             protoimpl.MessageState                                              `protogen:"open.v1"`
	ShopId            string                                                              `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	PurchaseSummaries []*ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary `protobuf:"bytes,2,rep,name=purchase_summaries,json=purchaseSummaries,proto3" json:"purchase_summaries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries_Types_Request) Reset() {
	*x = ItemShopAddPurchaseSummaries_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries_Types_Request) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries_Types_Request.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ItemShopAddPurchaseSummaries_Types_Request) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ItemShopAddPurchaseSummaries_Types_Request) GetPurchaseSummaries() []*ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary {
	if x != nil {
		return x.PurchaseSummaries
	}
	return nil
}

type ItemShopAddPurchaseSummaries_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries_Types_Response) Reset() {
	*x = ItemShopAddPurchaseSummaries_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries_Types_Response) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries_Types_Response.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0, 0, 1}
}

type ItemShopAddPurchaseSummaries_Types_Request_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types) Reset() {
	*x = ItemShopAddPurchaseSummaries_Types_Request_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries_Types_Request_Types) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries_Types_Request_Types.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries_Types_Request_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseAmount  int64                  `protobuf:"varint,2,opt,name=purchase_amount,json=purchaseAmount,proto3" json:"purchase_amount,omitempty"`
	NextResetAt     int64                  `protobuf:"varint,3,opt,name=next_reset_at,json=nextResetAt,proto3" json:"next_reset_at,omitempty"`
	LastPurchasedAt int64                  `protobuf:"varint,4,opt,name=last_purchased_at,json=lastPurchasedAt,proto3" json:"last_purchased_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) Reset() {
	*x = ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) ProtoMessage() {}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary.ProtoReflect.Descriptor instead.
func (*ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) GetPurchaseAmount() int64 {
	if x != nil {
		return x.PurchaseAmount
	}
	return 0
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) GetNextResetAt() int64 {
	if x != nil {
		return x.NextResetAt
	}
	return 0
}

func (x *ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary) GetLastPurchasedAt() int64 {
	if x != nil {
		return x.LastPurchasedAt
	}
	return 0
}

var File_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDesc = "" +
	"\n" +
	"Ptakasho/schema/lettuce_debug_server/debug/item_shop_add_purchase_summaries.proto\x12)takasho.schema.lettuce_debug_server.debug\"\xac\x03\n" +
	"\x1cItemShopAddPurchaseSummaries\x1a\x8b\x03\n" +
	"\x05Types\x1a\xf5\x02\n" +
	"\aRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x9a\x01\n" +
	"\x12purchase_summaries\x18\x02 \x03(\v2k.takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request.Types.PurchaseSummaryR\x11purchaseSummaries\x1a\xb3\x01\n" +
	"\x05Types\x1a\xa9\x01\n" +
	"\x0fPurchaseSummary\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12'\n" +
	"\x0fpurchase_amount\x18\x02 \x01(\x03R\x0epurchaseAmount\x12\"\n" +
	"\rnext_reset_at\x18\x03 \x01(\x03R\vnextResetAt\x12*\n" +
	"\x11last_purchased_at\x18\x04 \x01(\x03R\x0flastPurchasedAt\x1a\n" +
	"\n" +
	"\bResponseBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_goTypes = []any{
	(*ItemShopAddPurchaseSummaries)(nil),                                     // 0: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries
	(*ItemShopAddPurchaseSummaries_Types)(nil),                               // 1: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types
	(*ItemShopAddPurchaseSummaries_Types_Request)(nil),                       // 2: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request
	(*ItemShopAddPurchaseSummaries_Types_Response)(nil),                      // 3: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Response
	(*ItemShopAddPurchaseSummaries_Types_Request_Types)(nil),                 // 4: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request.Types
	(*ItemShopAddPurchaseSummaries_Types_Request_Types_PurchaseSummary)(nil), // 5: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request.Types.PurchaseSummary
}
var file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_depIdxs = []int32{
	5, // 0: takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request.purchase_summaries:type_name -> takasho.schema.lettuce_debug_server.debug.ItemShopAddPurchaseSummaries.Types.Request.Types.PurchaseSummary
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_init()
}
func file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_item_shop_add_purchase_summaries_proto_depIdxs = nil
}
