// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/item.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_takasho_schema_lettuce_debug_server_debug_item_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_item_proto_rawDesc = "" +
	"\n" +
	"4takasho/schema/lettuce_debug_server/debug/item.proto\x12)takasho.schema.lettuce_debug_server.debug\x1a8takasho/schema/lettuce_debug_server/debug/item_add.proto\x1aCtakasho/schema/lettuce_debug_server/debug/item_add_to_players.proto2\xbb\x02\n" +
	"\x04Item\x12\x8a\x01\n" +
	"\x03Add\x12@.takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Request\x1aA.takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Response\x12\xa5\x01\n" +
	"\fAddToPlayers\x12I.takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.Request\x1aJ.takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.ResponseBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var file_takasho_schema_lettuce_debug_server_debug_item_proto_goTypes = []any{
	(*ItemAdd_Types_Request)(nil),           // 0: takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Request
	(*ItemAddToPlayers_Types_Request)(nil),  // 1: takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.Request
	(*ItemAdd_Types_Response)(nil),          // 2: takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Response
	(*ItemAddToPlayers_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.Response
}
var file_takasho_schema_lettuce_debug_server_debug_item_proto_depIdxs = []int32{
	0, // 0: takasho.schema.lettuce_debug_server.debug.Item.Add:input_type -> takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Request
	1, // 1: takasho.schema.lettuce_debug_server.debug.Item.AddToPlayers:input_type -> takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.Request
	2, // 2: takasho.schema.lettuce_debug_server.debug.Item.Add:output_type -> takasho.schema.lettuce_debug_server.debug.ItemAdd.Types.Response
	3, // 3: takasho.schema.lettuce_debug_server.debug.Item.AddToPlayers:output_type -> takasho.schema.lettuce_debug_server.debug.ItemAddToPlayers.Types.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_debug_server_debug_item_proto_init() }
func file_takasho_schema_lettuce_debug_server_debug_item_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_item_proto != nil {
		return
	}
	file_takasho_schema_lettuce_debug_server_debug_item_add_proto_init()
	file_takasho_schema_lettuce_debug_server_debug_item_add_to_players_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_item_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_item_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_item_proto_depIdxs,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_item_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_item_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_item_proto_depIdxs = nil
}
