// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/mission_undo_clear.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissionUndoClear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUndoClear) Reset() {
	*x = MissionUndoClear{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUndoClear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUndoClear) ProtoMessage() {}

func (x *MissionUndoClear) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUndoClear.ProtoReflect.Descriptor instead.
func (*MissionUndoClear) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescGZIP(), []int{0}
}

type MissionUndoClear_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUndoClear_Types) Reset() {
	*x = MissionUndoClear_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUndoClear_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUndoClear_Types) ProtoMessage() {}

func (x *MissionUndoClear_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUndoClear_Types.ProtoReflect.Descriptor instead.
func (*MissionUndoClear_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescGZIP(), []int{0, 0}
}

type MissionUndoClear_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionIds    []string               `protobuf:"bytes,1,rep,name=mission_ids,json=missionIds,proto3" json:"mission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUndoClear_Types_Request) Reset() {
	*x = MissionUndoClear_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUndoClear_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUndoClear_Types_Request) ProtoMessage() {}

func (x *MissionUndoClear_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUndoClear_Types_Request.ProtoReflect.Descriptor instead.
func (*MissionUndoClear_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MissionUndoClear_Types_Request) GetMissionIds() []string {
	if x != nil {
		return x.MissionIds
	}
	return nil
}

type MissionUndoClear_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUndoClear_Types_Response) Reset() {
	*x = MissionUndoClear_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUndoClear_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUndoClear_Types_Response) ProtoMessage() {}

func (x *MissionUndoClear_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUndoClear_Types_Response.ProtoReflect.Descriptor instead.
func (*MissionUndoClear_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescGZIP(), []int{0, 0, 1}
}

var File_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDesc = "" +
	"\n" +
	"Btakasho/schema/lettuce_debug_server/debug/mission_undo_clear.proto\x12)takasho.schema.lettuce_debug_server.debug\"S\n" +
	"\x10MissionUndoClear\x1a?\n" +
	"\x05Types\x1a*\n" +
	"\aRequest\x12\x1f\n" +
	"\vmission_ids\x18\x01 \x03(\tR\n" +
	"missionIds\x1a\n" +
	"\n" +
	"\bResponseBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_goTypes = []any{
	(*MissionUndoClear)(nil),                // 0: takasho.schema.lettuce_debug_server.debug.MissionUndoClear
	(*MissionUndoClear_Types)(nil),          // 1: takasho.schema.lettuce_debug_server.debug.MissionUndoClear.Types
	(*MissionUndoClear_Types_Request)(nil),  // 2: takasho.schema.lettuce_debug_server.debug.MissionUndoClear.Types.Request
	(*MissionUndoClear_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.MissionUndoClear.Types.Response
}
var file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_init() }
func file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_mission_undo_clear_proto_depIdxs = nil
}
