// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/player_set_baas_user_debug_setting.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerSetBaasUserDebugSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSetBaasUserDebugSetting) Reset() {
	*x = PlayerSetBaasUserDebugSetting{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSetBaasUserDebugSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetBaasUserDebugSetting) ProtoMessage() {}

func (x *PlayerSetBaasUserDebugSetting) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetBaasUserDebugSetting.ProtoReflect.Descriptor instead.
func (*PlayerSetBaasUserDebugSetting) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP(), []int{0}
}

type PlayerSetBaasUserDebugSetting_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSetBaasUserDebugSetting_Types) Reset() {
	*x = PlayerSetBaasUserDebugSetting_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSetBaasUserDebugSetting_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetBaasUserDebugSetting_Types) ProtoMessage() {}

func (x *PlayerSetBaasUserDebugSetting_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetBaasUserDebugSetting_Types.ProtoReflect.Descriptor instead.
func (*PlayerSetBaasUserDebugSetting_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchasedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=purchased_at,json=purchasedAt,proto3" json:"purchased_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) Reset() {
	*x = PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) ProtoMessage() {}

func (x *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent.ProtoReflect.Descriptor instead.
func (*PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent) GetPurchasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchasedAt
	}
	return nil
}

type PlayerSetBaasUserDebugSetting_Types_Request struct {
	state                 protoimpl.MessageState                                     `protogen:"open.v1"`
	MasterVersion         string                                                     `protobuf:"bytes,1,opt,name=master_version,json=masterVersion,proto3" json:"master_version,omitempty"`
	PokeGoldPurchaseEvent *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent `protobuf:"bytes,2,opt,name=poke_gold_purchase_event,json=pokeGoldPurchaseEvent,proto3" json:"poke_gold_purchase_event,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerSetBaasUserDebugSetting_Types_Request) Reset() {
	*x = PlayerSetBaasUserDebugSetting_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSetBaasUserDebugSetting_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetBaasUserDebugSetting_Types_Request) ProtoMessage() {}

func (x *PlayerSetBaasUserDebugSetting_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetBaasUserDebugSetting_Types_Request.ProtoReflect.Descriptor instead.
func (*PlayerSetBaasUserDebugSetting_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PlayerSetBaasUserDebugSetting_Types_Request) GetMasterVersion() string {
	if x != nil {
		return x.MasterVersion
	}
	return ""
}

func (x *PlayerSetBaasUserDebugSetting_Types_Request) GetPokeGoldPurchaseEvent() *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent {
	if x != nil {
		return x.PokeGoldPurchaseEvent
	}
	return nil
}

type PlayerSetBaasUserDebugSetting_Types_Response struct {
	state                 protoimpl.MessageState                                     `protogen:"open.v1"`
	BaasUserId            string                                                     `protobuf:"bytes,1,opt,name=baas_user_id,json=baasUserId,proto3" json:"baas_user_id,omitempty"`
	MasterVersion         string                                                     `protobuf:"bytes,2,opt,name=master_version,json=masterVersion,proto3" json:"master_version,omitempty"`
	PokeGoldPurchaseEvent *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent `protobuf:"bytes,3,opt,name=poke_gold_purchase_event,json=pokeGoldPurchaseEvent,proto3" json:"poke_gold_purchase_event,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) Reset() {
	*x = PlayerSetBaasUserDebugSetting_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetBaasUserDebugSetting_Types_Response) ProtoMessage() {}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetBaasUserDebugSetting_Types_Response.ProtoReflect.Descriptor instead.
func (*PlayerSetBaasUserDebugSetting_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) GetBaasUserId() string {
	if x != nil {
		return x.BaasUserId
	}
	return ""
}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) GetMasterVersion() string {
	if x != nil {
		return x.MasterVersion
	}
	return ""
}

func (x *PlayerSetBaasUserDebugSetting_Types_Response) GetPokeGoldPurchaseEvent() *PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent {
	if x != nil {
		return x.PokeGoldPurchaseEvent
	}
	return nil
}

var File_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDesc = "" +
	"\n" +
	"Rtakasho/schema/lettuce_debug_server/debug/player_set_baas_user_debug_setting.proto\x12)takasho.schema.lettuce_debug_server.debug\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x04\n" +
	"\x1dPlayerSetBaasUserDebugSetting\x1a\xa8\x04\n" +
	"\x05Types\x1aV\n" +
	"\x15PokeGoldPurchaseEvent\x12=\n" +
	"\fpurchased_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vpurchasedAt\x1a\xd0\x01\n" +
	"\aRequest\x12%\n" +
	"\x0emaster_version\x18\x01 \x01(\tR\rmasterVersion\x12\x9d\x01\n" +
	"\x18poke_gold_purchase_event\x18\x02 \x01(\v2d.takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEventR\x15pokeGoldPurchaseEvent\x1a\xf3\x01\n" +
	"\bResponse\x12 \n" +
	"\fbaas_user_id\x18\x01 \x01(\tR\n" +
	"baasUserId\x12%\n" +
	"\x0emaster_version\x18\x02 \x01(\tR\rmasterVersion\x12\x9d\x01\n" +
	"\x18poke_gold_purchase_event\x18\x03 \x01(\v2d.takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEventR\x15pokeGoldPurchaseEventBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_goTypes = []any{
	(*PlayerSetBaasUserDebugSetting)(nil),                             // 0: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting
	(*PlayerSetBaasUserDebugSetting_Types)(nil),                       // 1: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types
	(*PlayerSetBaasUserDebugSetting_Types_PokeGoldPurchaseEvent)(nil), // 2: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEvent
	(*PlayerSetBaasUserDebugSetting_Types_Request)(nil),               // 3: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.Request
	(*PlayerSetBaasUserDebugSetting_Types_Response)(nil),              // 4: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.Response
	(*timestamppb.Timestamp)(nil),                                     // 5: google.protobuf.Timestamp
}
var file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_depIdxs = []int32{
	5, // 0: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEvent.purchased_at:type_name -> google.protobuf.Timestamp
	2, // 1: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.Request.poke_gold_purchase_event:type_name -> takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEvent
	2, // 2: takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.Response.poke_gold_purchase_event:type_name -> takasho.schema.lettuce_debug_server.debug.PlayerSetBaasUserDebugSetting.Types.PokeGoldPurchaseEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_init()
}
func file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_player_set_baas_user_debug_setting_proto_depIdxs = nil
}
