// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/pvp_casual.proto

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PvpCasual_SetProfiles_FullMethodName          = "/takasho.schema.lettuce_debug_server.debug.PvpCasual/SetProfiles"
	PvpCasual_SetProfileUpdateMode_FullMethodName = "/takasho.schema.lettuce_debug_server.debug.PvpCasual/SetProfileUpdateMode"
	PvpCasual_GetProfile_FullMethodName           = "/takasho.schema.lettuce_debug_server.debug.PvpCasual/GetProfile"
)

// PvpCasualClient is the client API for PvpCasual service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PvpCasualClient interface {
	SetProfiles(ctx context.Context, in *PvpCasualSetProfiles_Types_Request, opts ...grpc.CallOption) (*PvpCasualSetProfiles_Types_Response, error)
	SetProfileUpdateMode(ctx context.Context, in *PvpCasualSetProfileUpdateMode_Types_Request, opts ...grpc.CallOption) (*PvpCasualSetProfileUpdateMode_Types_Response, error)
	GetProfile(ctx context.Context, in *PvpCasualGetProfile_Types_Request, opts ...grpc.CallOption) (*PvpCasualGetProfile_Types_Response, error)
}

type pvpCasualClient struct {
	cc grpc.ClientConnInterface
}

func NewPvpCasualClient(cc grpc.ClientConnInterface) PvpCasualClient {
	return &pvpCasualClient{cc}
}

func (c *pvpCasualClient) SetProfiles(ctx context.Context, in *PvpCasualSetProfiles_Types_Request, opts ...grpc.CallOption) (*PvpCasualSetProfiles_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PvpCasualSetProfiles_Types_Response)
	err := c.cc.Invoke(ctx, PvpCasual_SetProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvpCasualClient) SetProfileUpdateMode(ctx context.Context, in *PvpCasualSetProfileUpdateMode_Types_Request, opts ...grpc.CallOption) (*PvpCasualSetProfileUpdateMode_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PvpCasualSetProfileUpdateMode_Types_Response)
	err := c.cc.Invoke(ctx, PvpCasual_SetProfileUpdateMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvpCasualClient) GetProfile(ctx context.Context, in *PvpCasualGetProfile_Types_Request, opts ...grpc.CallOption) (*PvpCasualGetProfile_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PvpCasualGetProfile_Types_Response)
	err := c.cc.Invoke(ctx, PvpCasual_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PvpCasualServer is the server API for PvpCasual service.
// All implementations must embed UnimplementedPvpCasualServer
// for forward compatibility.
type PvpCasualServer interface {
	SetProfiles(context.Context, *PvpCasualSetProfiles_Types_Request) (*PvpCasualSetProfiles_Types_Response, error)
	SetProfileUpdateMode(context.Context, *PvpCasualSetProfileUpdateMode_Types_Request) (*PvpCasualSetProfileUpdateMode_Types_Response, error)
	GetProfile(context.Context, *PvpCasualGetProfile_Types_Request) (*PvpCasualGetProfile_Types_Response, error)
	mustEmbedUnimplementedPvpCasualServer()
}

// UnimplementedPvpCasualServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPvpCasualServer struct{}

func (UnimplementedPvpCasualServer) SetProfiles(context.Context, *PvpCasualSetProfiles_Types_Request) (*PvpCasualSetProfiles_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProfiles not implemented")
}
func (UnimplementedPvpCasualServer) SetProfileUpdateMode(context.Context, *PvpCasualSetProfileUpdateMode_Types_Request) (*PvpCasualSetProfileUpdateMode_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProfileUpdateMode not implemented")
}
func (UnimplementedPvpCasualServer) GetProfile(context.Context, *PvpCasualGetProfile_Types_Request) (*PvpCasualGetProfile_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedPvpCasualServer) mustEmbedUnimplementedPvpCasualServer() {}
func (UnimplementedPvpCasualServer) testEmbeddedByValue()                   {}

// UnsafePvpCasualServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PvpCasualServer will
// result in compilation errors.
type UnsafePvpCasualServer interface {
	mustEmbedUnimplementedPvpCasualServer()
}

func RegisterPvpCasualServer(s grpc.ServiceRegistrar, srv PvpCasualServer) {
	// If the following call panics, it indicates UnimplementedPvpCasualServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PvpCasual_ServiceDesc, srv)
}

func _PvpCasual_SetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PvpCasualSetProfiles_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvpCasualServer).SetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvpCasual_SetProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvpCasualServer).SetProfiles(ctx, req.(*PvpCasualSetProfiles_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvpCasual_SetProfileUpdateMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PvpCasualSetProfileUpdateMode_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvpCasualServer).SetProfileUpdateMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvpCasual_SetProfileUpdateMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvpCasualServer).SetProfileUpdateMode(ctx, req.(*PvpCasualSetProfileUpdateMode_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvpCasual_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PvpCasualGetProfile_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvpCasualServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvpCasual_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvpCasualServer).GetProfile(ctx, req.(*PvpCasualGetProfile_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PvpCasual_ServiceDesc is the grpc.ServiceDesc for PvpCasual service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PvpCasual_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_debug_server.debug.PvpCasual",
	HandlerType: (*PvpCasualServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetProfiles",
			Handler:    _PvpCasual_SetProfiles_Handler,
		},
		{
			MethodName: "SetProfileUpdateMode",
			Handler:    _PvpCasual_SetProfileUpdateMode_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _PvpCasual_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_debug_server/debug/pvp_casual.proto",
}
