// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/pvp_casual_get_profile.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PvpCasualGetProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpCasualGetProfile) Reset() {
	*x = PvpCasualGetProfile{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualGetProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualGetProfile) ProtoMessage() {}

func (x *PvpCasualGetProfile) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualGetProfile.ProtoReflect.Descriptor instead.
func (*PvpCasualGetProfile) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescGZIP(), []int{0}
}

type PvpCasualGetProfile_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpCasualGetProfile_Types) Reset() {
	*x = PvpCasualGetProfile_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualGetProfile_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualGetProfile_Types) ProtoMessage() {}

func (x *PvpCasualGetProfile_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualGetProfile_Types.ProtoReflect.Descriptor instead.
func (*PvpCasualGetProfile_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescGZIP(), []int{0, 0}
}

type PvpCasualGetProfile_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpCasualGetProfile_Types_Request) Reset() {
	*x = PvpCasualGetProfile_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualGetProfile_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualGetProfile_Types_Request) ProtoMessage() {}

func (x *PvpCasualGetProfile_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualGetProfile_Types_Request.ProtoReflect.Descriptor instead.
func (*PvpCasualGetProfile_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PvpCasualGetProfile_Types_Request) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PvpCasualGetProfile_Types_Response struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlayerId             string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TotalAcquiredPoint   int64                  `protobuf:"varint,2,opt,name=total_acquired_point,json=totalAcquiredPoint,proto3" json:"total_acquired_point,omitempty"`
	TotalBattleCount     int64                  `protobuf:"varint,3,opt,name=total_battle_count,json=totalBattleCount,proto3" json:"total_battle_count,omitempty"`
	TotalWinCount        int64                  `protobuf:"varint,4,opt,name=total_win_count,json=totalWinCount,proto3" json:"total_win_count,omitempty"`
	TotalLoseCount       int64                  `protobuf:"varint,5,opt,name=total_lose_count,json=totalLoseCount,proto3" json:"total_lose_count,omitempty"`
	MaxDamage            int64                  `protobuf:"varint,6,opt,name=max_damage,json=maxDamage,proto3" json:"max_damage,omitempty"`
	MaxWinningStreak     int64                  `protobuf:"varint,7,opt,name=max_winning_streak,json=maxWinningStreak,proto3" json:"max_winning_streak,omitempty"`
	CurrentWinningStreak int64                  `protobuf:"varint,8,opt,name=current_winning_streak,json=currentWinningStreak,proto3" json:"current_winning_streak,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PvpCasualGetProfile_Types_Response) Reset() {
	*x = PvpCasualGetProfile_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualGetProfile_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualGetProfile_Types_Response) ProtoMessage() {}

func (x *PvpCasualGetProfile_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualGetProfile_Types_Response.ProtoReflect.Descriptor instead.
func (*PvpCasualGetProfile_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PvpCasualGetProfile_Types_Response) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PvpCasualGetProfile_Types_Response) GetTotalAcquiredPoint() int64 {
	if x != nil {
		return x.TotalAcquiredPoint
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetTotalBattleCount() int64 {
	if x != nil {
		return x.TotalBattleCount
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetTotalWinCount() int64 {
	if x != nil {
		return x.TotalWinCount
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetTotalLoseCount() int64 {
	if x != nil {
		return x.TotalLoseCount
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetMaxDamage() int64 {
	if x != nil {
		return x.MaxDamage
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetMaxWinningStreak() int64 {
	if x != nil {
		return x.MaxWinningStreak
	}
	return 0
}

func (x *PvpCasualGetProfile_Types_Response) GetCurrentWinningStreak() int64 {
	if x != nil {
		return x.CurrentWinningStreak
	}
	return 0
}

var File_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDesc = "" +
	"\n" +
	"Ftakasho/schema/lettuce_debug_server/debug/pvp_casual_get_profile.proto\x12)takasho.schema.lettuce_debug_server.debug\"\xa6\x03\n" +
	"\x13PvpCasualGetProfile\x1a\x8e\x03\n" +
	"\x05Types\x1a&\n" +
	"\aRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x1a\xdc\x02\n" +
	"\bResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x120\n" +
	"\x14total_acquired_point\x18\x02 \x01(\x03R\x12totalAcquiredPoint\x12,\n" +
	"\x12total_battle_count\x18\x03 \x01(\x03R\x10totalBattleCount\x12&\n" +
	"\x0ftotal_win_count\x18\x04 \x01(\x03R\rtotalWinCount\x12(\n" +
	"\x10total_lose_count\x18\x05 \x01(\x03R\x0etotalLoseCount\x12\x1d\n" +
	"\n" +
	"max_damage\x18\x06 \x01(\x03R\tmaxDamage\x12,\n" +
	"\x12max_winning_streak\x18\a \x01(\x03R\x10maxWinningStreak\x124\n" +
	"\x16current_winning_streak\x18\b \x01(\x03R\x14currentWinningStreakBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_goTypes = []any{
	(*PvpCasualGetProfile)(nil),                // 0: takasho.schema.lettuce_debug_server.debug.PvpCasualGetProfile
	(*PvpCasualGetProfile_Types)(nil),          // 1: takasho.schema.lettuce_debug_server.debug.PvpCasualGetProfile.Types
	(*PvpCasualGetProfile_Types_Request)(nil),  // 2: takasho.schema.lettuce_debug_server.debug.PvpCasualGetProfile.Types.Request
	(*PvpCasualGetProfile_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.PvpCasualGetProfile.Types.Response
}
var file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_init() }
func file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_pvp_casual_get_profile_proto_depIdxs = nil
}
