// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/pvp_rank_restore_ranking.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PvpRankRestoreRanking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankRestoreRanking) Reset() {
	*x = PvpRankRestoreRanking{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankRestoreRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankRestoreRanking) ProtoMessage() {}

func (x *PvpRankRestoreRanking) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankRestoreRanking.ProtoReflect.Descriptor instead.
func (*PvpRankRestoreRanking) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescGZIP(), []int{0}
}

type PvpRankRestoreRanking_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankRestoreRanking_Types) Reset() {
	*x = PvpRankRestoreRanking_Types{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankRestoreRanking_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankRestoreRanking_Types) ProtoMessage() {}

func (x *PvpRankRestoreRanking_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankRestoreRanking_Types.ProtoReflect.Descriptor instead.
func (*PvpRankRestoreRanking_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescGZIP(), []int{0, 0}
}

type PvpRankRestoreRanking_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeasonId      string                 `protobuf:"bytes,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankRestoreRanking_Types_Request) Reset() {
	*x = PvpRankRestoreRanking_Types_Request{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankRestoreRanking_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankRestoreRanking_Types_Request) ProtoMessage() {}

func (x *PvpRankRestoreRanking_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankRestoreRanking_Types_Request.ProtoReflect.Descriptor instead.
func (*PvpRankRestoreRanking_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PvpRankRestoreRanking_Types_Request) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

type PvpRankRestoreRanking_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankRestoreRanking_Types_Response) Reset() {
	*x = PvpRankRestoreRanking_Types_Response{}
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankRestoreRanking_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankRestoreRanking_Types_Response) ProtoMessage() {}

func (x *PvpRankRestoreRanking_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankRestoreRanking_Types_Response.ProtoReflect.Descriptor instead.
func (*PvpRankRestoreRanking_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescGZIP(), []int{0, 0, 1}
}

var File_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDesc = "" +
	"\n" +
	"Htakasho/schema/lettuce_debug_server/debug/pvp_rank_restore_ranking.proto\x12)takasho.schema.lettuce_debug_server.debug\"T\n" +
	"\x15PvpRankRestoreRanking\x1a;\n" +
	"\x05Types\x1a&\n" +
	"\aRequest\x12\x1b\n" +
	"\tseason_id\x18\x01 \x01(\tR\bseasonId\x1a\n" +
	"\n" +
	"\bResponseBkZigithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_debug_server/debug;debugb\x06proto3"

var (
	file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDescData
}

var file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_goTypes = []any{
	(*PvpRankRestoreRanking)(nil),                // 0: takasho.schema.lettuce_debug_server.debug.PvpRankRestoreRanking
	(*PvpRankRestoreRanking_Types)(nil),          // 1: takasho.schema.lettuce_debug_server.debug.PvpRankRestoreRanking.Types
	(*PvpRankRestoreRanking_Types_Request)(nil),  // 2: takasho.schema.lettuce_debug_server.debug.PvpRankRestoreRanking.Types.Request
	(*PvpRankRestoreRanking_Types_Response)(nil), // 3: takasho.schema.lettuce_debug_server.debug.PvpRankRestoreRanking.Types.Response
}
var file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_init() }
func file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_init() {
	if File_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDesc), len(file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto = out.File
	file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_goTypes = nil
	file_takasho_schema_lettuce_debug_server_debug_pvp_rank_restore_ranking_proto_depIdxs = nil
}
