// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_debug_server/debug/webview.proto

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Webview_SetLastViewed_FullMethodName = "/takasho.schema.lettuce_debug_server.debug.Webview/SetLastViewed"
)

// WebviewClient is the client API for Webview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebviewClient interface {
	SetLastViewed(ctx context.Context, in *WebviewSetLastViewed_Types_Request, opts ...grpc.CallOption) (*WebviewSetLastViewed_Types_Response, error)
}

type webviewClient struct {
	cc grpc.ClientConnInterface
}

func NewWebviewClient(cc grpc.ClientConnInterface) WebviewClient {
	return &webviewClient{cc}
}

func (c *webviewClient) SetLastViewed(ctx context.Context, in *WebviewSetLastViewed_Types_Request, opts ...grpc.CallOption) (*WebviewSetLastViewed_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebviewSetLastViewed_Types_Response)
	err := c.cc.Invoke(ctx, Webview_SetLastViewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebviewServer is the server API for Webview service.
// All implementations must embed UnimplementedWebviewServer
// for forward compatibility.
type WebviewServer interface {
	SetLastViewed(context.Context, *WebviewSetLastViewed_Types_Request) (*WebviewSetLastViewed_Types_Response, error)
	mustEmbedUnimplementedWebviewServer()
}

// UnimplementedWebviewServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebviewServer struct{}

func (UnimplementedWebviewServer) SetLastViewed(context.Context, *WebviewSetLastViewed_Types_Request) (*WebviewSetLastViewed_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLastViewed not implemented")
}
func (UnimplementedWebviewServer) mustEmbedUnimplementedWebviewServer() {}
func (UnimplementedWebviewServer) testEmbeddedByValue()                 {}

// UnsafeWebviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebviewServer will
// result in compilation errors.
type UnsafeWebviewServer interface {
	mustEmbedUnimplementedWebviewServer()
}

func RegisterWebviewServer(s grpc.ServiceRegistrar, srv WebviewServer) {
	// If the following call panics, it indicates UnimplementedWebviewServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Webview_ServiceDesc, srv)
}

func _Webview_SetLastViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebviewSetLastViewed_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebviewServer).SetLastViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webview_SetLastViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebviewServer).SetLastViewed(ctx, req.(*WebviewSetLastViewed_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Webview_ServiceDesc is the grpc.ServiceDesc for Webview service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Webview_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_debug_server.debug.Webview",
	HandlerType: (*WebviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLastViewed",
			Handler:    _Webview_SetLastViewed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_debug_server/debug/webview.proto",
}
