// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_server/player_api/card.proto

package player_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Card_SetDesiresV1_FullMethodName = "/takasho.schema.lettuce_server.player_api.Card/SetDesiresV1"
	Card_GetDesiresV1_FullMethodName = "/takasho.schema.lettuce_server.player_api.Card/GetDesiresV1"
	Card_GetUsageV1_FullMethodName   = "/takasho.schema.lettuce_server.player_api.Card/GetUsageV1"
)

// CardClient is the client API for Card service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardClient interface {
	SetDesiresV1(ctx context.Context, in *CardSetDesiresV1_Types_Request, opts ...grpc.CallOption) (*CardSetDesiresV1_Types_Response, error)
	GetDesiresV1(ctx context.Context, in *CardGetDesiresV1_Types_Request, opts ...grpc.CallOption) (*CardGetDesiresV1_Types_Response, error)
	GetUsageV1(ctx context.Context, in *CardGetUsageV1_Types_Request, opts ...grpc.CallOption) (*CardGetUsageV1_Types_Response, error)
}

type cardClient struct {
	cc grpc.ClientConnInterface
}

func NewCardClient(cc grpc.ClientConnInterface) CardClient {
	return &cardClient{cc}
}

func (c *cardClient) SetDesiresV1(ctx context.Context, in *CardSetDesiresV1_Types_Request, opts ...grpc.CallOption) (*CardSetDesiresV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardSetDesiresV1_Types_Response)
	err := c.cc.Invoke(ctx, Card_SetDesiresV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) GetDesiresV1(ctx context.Context, in *CardGetDesiresV1_Types_Request, opts ...grpc.CallOption) (*CardGetDesiresV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardGetDesiresV1_Types_Response)
	err := c.cc.Invoke(ctx, Card_GetDesiresV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) GetUsageV1(ctx context.Context, in *CardGetUsageV1_Types_Request, opts ...grpc.CallOption) (*CardGetUsageV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardGetUsageV1_Types_Response)
	err := c.cc.Invoke(ctx, Card_GetUsageV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServer is the server API for Card service.
// All implementations must embed UnimplementedCardServer
// for forward compatibility.
type CardServer interface {
	SetDesiresV1(context.Context, *CardSetDesiresV1_Types_Request) (*CardSetDesiresV1_Types_Response, error)
	GetDesiresV1(context.Context, *CardGetDesiresV1_Types_Request) (*CardGetDesiresV1_Types_Response, error)
	GetUsageV1(context.Context, *CardGetUsageV1_Types_Request) (*CardGetUsageV1_Types_Response, error)
	mustEmbedUnimplementedCardServer()
}

// UnimplementedCardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardServer struct{}

func (UnimplementedCardServer) SetDesiresV1(context.Context, *CardSetDesiresV1_Types_Request) (*CardSetDesiresV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDesiresV1 not implemented")
}
func (UnimplementedCardServer) GetDesiresV1(context.Context, *CardGetDesiresV1_Types_Request) (*CardGetDesiresV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesiresV1 not implemented")
}
func (UnimplementedCardServer) GetUsageV1(context.Context, *CardGetUsageV1_Types_Request) (*CardGetUsageV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageV1 not implemented")
}
func (UnimplementedCardServer) mustEmbedUnimplementedCardServer() {}
func (UnimplementedCardServer) testEmbeddedByValue()              {}

// UnsafeCardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardServer will
// result in compilation errors.
type UnsafeCardServer interface {
	mustEmbedUnimplementedCardServer()
}

func RegisterCardServer(s grpc.ServiceRegistrar, srv CardServer) {
	// If the following call panics, it indicates UnimplementedCardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Card_ServiceDesc, srv)
}

func _Card_SetDesiresV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardSetDesiresV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).SetDesiresV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Card_SetDesiresV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).SetDesiresV1(ctx, req.(*CardSetDesiresV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_GetDesiresV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardGetDesiresV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).GetDesiresV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Card_GetDesiresV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).GetDesiresV1(ctx, req.(*CardGetDesiresV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_GetUsageV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardGetUsageV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).GetUsageV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Card_GetUsageV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).GetUsageV1(ctx, req.(*CardGetUsageV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Card_ServiceDesc is the grpc.ServiceDesc for Card service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Card_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_server.player_api.Card",
	HandlerType: (*CardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDesiresV1",
			Handler:    _Card_SetDesiresV1_Handler,
		},
		{
			MethodName: "GetDesiresV1",
			Handler:    _Card_GetDesiresV1_Handler,
		},
		{
			MethodName: "GetUsageV1",
			Handler:    _Card_GetUsageV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_server/player_api/card.proto",
}
