// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/collection.proto

package player_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_takasho_schema_lettuce_server_player_api_collection_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_collection_proto_rawDesc = "" +
	"\n" +
	"9takasho/schema/lettuce_server/player_api/collection.proto\x12(takasho.schema.lettuce_server.player_api\x1aItakasho/schema/lettuce_server/player_api/collection_get_someones_v1.proto\x1aAtakasho/schema/lettuce_server/player_api/collection_like_v1.proto\x1aAtakasho/schema/lettuce_server/player_api/collection_list_v1.proto\x1aGtakasho/schema/lettuce_server/player_api/collection_other_list_v1.proto\x1aHtakasho/schema/lettuce_server/player_api/collection_set_my_best_v1.proto2\xdf\x06\n" +
	"\n" +
	"Collection\x12\xb2\x01\n" +
	"\rGetSomeonesV1\x12O.takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Request\x1aP.takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Response\x12\x9d\x01\n" +
	"\x06ListV1\x12H.takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Request\x1aI.takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Response\x12\xac\x01\n" +
	"\vOtherListV1\x12M.takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Request\x1aN.takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Response\x12\xac\x01\n" +
	"\vSetMyBestV1\x12M.takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Request\x1aN.takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Response\x12\x9d\x01\n" +
	"\x06LikeV1\x12H.takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.Request\x1aI.takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.ResponseBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var file_takasho_schema_lettuce_server_player_api_collection_proto_goTypes = []any{
	(*CollectionGetSomeonesV1_Types_Request)(nil),  // 0: takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Request
	(*CollectionListV1_Types_Request)(nil),         // 1: takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Request
	(*CollectionOtherListV1_Types_Request)(nil),    // 2: takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Request
	(*CollectionSetMyBestV1_Types_Request)(nil),    // 3: takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Request
	(*CollectionLikeV1_Types_Request)(nil),         // 4: takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.Request
	(*CollectionGetSomeonesV1_Types_Response)(nil), // 5: takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Response
	(*CollectionListV1_Types_Response)(nil),        // 6: takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Response
	(*CollectionOtherListV1_Types_Response)(nil),   // 7: takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Response
	(*CollectionSetMyBestV1_Types_Response)(nil),   // 8: takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Response
	(*CollectionLikeV1_Types_Response)(nil),        // 9: takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.Response
}
var file_takasho_schema_lettuce_server_player_api_collection_proto_depIdxs = []int32{
	0, // 0: takasho.schema.lettuce_server.player_api.Collection.GetSomeonesV1:input_type -> takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Request
	1, // 1: takasho.schema.lettuce_server.player_api.Collection.ListV1:input_type -> takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Request
	2, // 2: takasho.schema.lettuce_server.player_api.Collection.OtherListV1:input_type -> takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Request
	3, // 3: takasho.schema.lettuce_server.player_api.Collection.SetMyBestV1:input_type -> takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Request
	4, // 4: takasho.schema.lettuce_server.player_api.Collection.LikeV1:input_type -> takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.Request
	5, // 5: takasho.schema.lettuce_server.player_api.Collection.GetSomeonesV1:output_type -> takasho.schema.lettuce_server.player_api.CollectionGetSomeonesV1.Types.Response
	6, // 6: takasho.schema.lettuce_server.player_api.Collection.ListV1:output_type -> takasho.schema.lettuce_server.player_api.CollectionListV1.Types.Response
	7, // 7: takasho.schema.lettuce_server.player_api.Collection.OtherListV1:output_type -> takasho.schema.lettuce_server.player_api.CollectionOtherListV1.Types.Response
	8, // 8: takasho.schema.lettuce_server.player_api.Collection.SetMyBestV1:output_type -> takasho.schema.lettuce_server.player_api.CollectionSetMyBestV1.Types.Response
	9, // 9: takasho.schema.lettuce_server.player_api.Collection.LikeV1:output_type -> takasho.schema.lettuce_server.player_api.CollectionLikeV1.Types.Response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_collection_proto_init() }
func file_takasho_schema_lettuce_server_player_api_collection_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_collection_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_player_api_collection_get_someones_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_collection_like_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_collection_list_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_collection_other_list_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_collection_set_my_best_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_collection_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_collection_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_collection_proto_depIdxs,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_collection_proto = out.File
	file_takasho_schema_lettuce_server_player_api_collection_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_collection_proto_depIdxs = nil
}
