// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_server/player_api/deck.proto

package player_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Deck_GetListV1_FullMethodName        = "/takasho.schema.lettuce_server.player_api.Deck/GetListV1"
	Deck_SaveV1_FullMethodName           = "/takasho.schema.lettuce_server.player_api.Deck/SaveV1"
	Deck_DeleteV1_FullMethodName         = "/takasho.schema.lettuce_server.player_api.Deck/DeleteV1"
	Deck_GetRentalDecksV1_FullMethodName = "/takasho.schema.lettuce_server.player_api.Deck/GetRentalDecksV1"
	Deck_ChangeOrderV1_FullMethodName    = "/takasho.schema.lettuce_server.player_api.Deck/ChangeOrderV1"
)

// DeckClient is the client API for Deck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeckClient interface {
	GetListV1(ctx context.Context, in *DeckGetListV1_Types_Request, opts ...grpc.CallOption) (*DeckGetListV1_Types_Response, error)
	SaveV1(ctx context.Context, in *DeckSaveV1_Types_Request, opts ...grpc.CallOption) (*DeckSaveV1_Types_Response, error)
	DeleteV1(ctx context.Context, in *DeckDeleteV1_Types_Request, opts ...grpc.CallOption) (*DeckDeleteV1_Types_Response, error)
	GetRentalDecksV1(ctx context.Context, in *DeckGetRentalDecksV1_Types_Request, opts ...grpc.CallOption) (*DeckGetRentalDecksV1_Types_Response, error)
	ChangeOrderV1(ctx context.Context, in *DeckChangeOrderV1_Types_Request, opts ...grpc.CallOption) (*DeckChangeOrderV1_Types_Response, error)
}

type deckClient struct {
	cc grpc.ClientConnInterface
}

func NewDeckClient(cc grpc.ClientConnInterface) DeckClient {
	return &deckClient{cc}
}

func (c *deckClient) GetListV1(ctx context.Context, in *DeckGetListV1_Types_Request, opts ...grpc.CallOption) (*DeckGetListV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckGetListV1_Types_Response)
	err := c.cc.Invoke(ctx, Deck_GetListV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckClient) SaveV1(ctx context.Context, in *DeckSaveV1_Types_Request, opts ...grpc.CallOption) (*DeckSaveV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckSaveV1_Types_Response)
	err := c.cc.Invoke(ctx, Deck_SaveV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckClient) DeleteV1(ctx context.Context, in *DeckDeleteV1_Types_Request, opts ...grpc.CallOption) (*DeckDeleteV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckDeleteV1_Types_Response)
	err := c.cc.Invoke(ctx, Deck_DeleteV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckClient) GetRentalDecksV1(ctx context.Context, in *DeckGetRentalDecksV1_Types_Request, opts ...grpc.CallOption) (*DeckGetRentalDecksV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckGetRentalDecksV1_Types_Response)
	err := c.cc.Invoke(ctx, Deck_GetRentalDecksV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckClient) ChangeOrderV1(ctx context.Context, in *DeckChangeOrderV1_Types_Request, opts ...grpc.CallOption) (*DeckChangeOrderV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeckChangeOrderV1_Types_Response)
	err := c.cc.Invoke(ctx, Deck_ChangeOrderV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeckServer is the server API for Deck service.
// All implementations must embed UnimplementedDeckServer
// for forward compatibility.
type DeckServer interface {
	GetListV1(context.Context, *DeckGetListV1_Types_Request) (*DeckGetListV1_Types_Response, error)
	SaveV1(context.Context, *DeckSaveV1_Types_Request) (*DeckSaveV1_Types_Response, error)
	DeleteV1(context.Context, *DeckDeleteV1_Types_Request) (*DeckDeleteV1_Types_Response, error)
	GetRentalDecksV1(context.Context, *DeckGetRentalDecksV1_Types_Request) (*DeckGetRentalDecksV1_Types_Response, error)
	ChangeOrderV1(context.Context, *DeckChangeOrderV1_Types_Request) (*DeckChangeOrderV1_Types_Response, error)
	mustEmbedUnimplementedDeckServer()
}

// UnimplementedDeckServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeckServer struct{}

func (UnimplementedDeckServer) GetListV1(context.Context, *DeckGetListV1_Types_Request) (*DeckGetListV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListV1 not implemented")
}
func (UnimplementedDeckServer) SaveV1(context.Context, *DeckSaveV1_Types_Request) (*DeckSaveV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveV1 not implemented")
}
func (UnimplementedDeckServer) DeleteV1(context.Context, *DeckDeleteV1_Types_Request) (*DeckDeleteV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteV1 not implemented")
}
func (UnimplementedDeckServer) GetRentalDecksV1(context.Context, *DeckGetRentalDecksV1_Types_Request) (*DeckGetRentalDecksV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRentalDecksV1 not implemented")
}
func (UnimplementedDeckServer) ChangeOrderV1(context.Context, *DeckChangeOrderV1_Types_Request) (*DeckChangeOrderV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeOrderV1 not implemented")
}
func (UnimplementedDeckServer) mustEmbedUnimplementedDeckServer() {}
func (UnimplementedDeckServer) testEmbeddedByValue()              {}

// UnsafeDeckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeckServer will
// result in compilation errors.
type UnsafeDeckServer interface {
	mustEmbedUnimplementedDeckServer()
}

func RegisterDeckServer(s grpc.ServiceRegistrar, srv DeckServer) {
	// If the following call panics, it indicates UnimplementedDeckServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deck_ServiceDesc, srv)
}

func _Deck_GetListV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckGetListV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServer).GetListV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deck_GetListV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServer).GetListV1(ctx, req.(*DeckGetListV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deck_SaveV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckSaveV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServer).SaveV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deck_SaveV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServer).SaveV1(ctx, req.(*DeckSaveV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deck_DeleteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckDeleteV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServer).DeleteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deck_DeleteV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServer).DeleteV1(ctx, req.(*DeckDeleteV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deck_GetRentalDecksV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckGetRentalDecksV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServer).GetRentalDecksV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deck_GetRentalDecksV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServer).GetRentalDecksV1(ctx, req.(*DeckGetRentalDecksV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deck_ChangeOrderV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeckChangeOrderV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServer).ChangeOrderV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deck_ChangeOrderV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServer).ChangeOrderV1(ctx, req.(*DeckChangeOrderV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Deck_ServiceDesc is the grpc.ServiceDesc for Deck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_server.player_api.Deck",
	HandlerType: (*DeckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListV1",
			Handler:    _Deck_GetListV1_Handler,
		},
		{
			MethodName: "SaveV1",
			Handler:    _Deck_SaveV1_Handler,
		},
		{
			MethodName: "DeleteV1",
			Handler:    _Deck_DeleteV1_Handler,
		},
		{
			MethodName: "GetRentalDecksV1",
			Handler:    _Deck_GetRentalDecksV1_Handler,
		},
		{
			MethodName: "ChangeOrderV1",
			Handler:    _Deck_ChangeOrderV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_server/player_api/deck.proto",
}
