// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/deck_change_order_v1.proto

package player_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckChangeOrderV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1) Reset() {
	*x = DeckChangeOrderV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1) ProtoMessage() {}

func (x *DeckChangeOrderV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0}
}

type DeckChangeOrderV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1_Types) Reset() {
	*x = DeckChangeOrderV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1_Types) ProtoMessage() {}

func (x *DeckChangeOrderV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1_Types.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0, 0}
}

type DeckChangeOrderV1_Types_Request struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Orders        []*DeckChangeOrderV1_Types_Request_Types_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1_Types_Request) Reset() {
	*x = DeckChangeOrderV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1_Types_Request) ProtoMessage() {}

func (x *DeckChangeOrderV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1_Types_Request.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DeckChangeOrderV1_Types_Request) GetOrders() []*DeckChangeOrderV1_Types_Request_Types_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type DeckChangeOrderV1_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1_Types_Response) Reset() {
	*x = DeckChangeOrderV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1_Types_Response) ProtoMessage() {}

func (x *DeckChangeOrderV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1_Types_Response.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

type DeckChangeOrderV1_Types_Request_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1_Types_Request_Types) Reset() {
	*x = DeckChangeOrderV1_Types_Request_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1_Types_Request_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1_Types_Request_Types) ProtoMessage() {}

func (x *DeckChangeOrderV1_Types_Request_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1_Types_Request_Types.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1_Types_Request_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type DeckChangeOrderV1_Types_Request_Types_Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        uint64                 `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Order         int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckChangeOrderV1_Types_Request_Types_Order) Reset() {
	*x = DeckChangeOrderV1_Types_Request_Types_Order{}
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckChangeOrderV1_Types_Request_Types_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckChangeOrderV1_Types_Request_Types_Order) ProtoMessage() {}

func (x *DeckChangeOrderV1_Types_Request_Types_Order) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckChangeOrderV1_Types_Request_Types_Order.ProtoReflect.Descriptor instead.
func (*DeckChangeOrderV1_Types_Request_Types_Order) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *DeckChangeOrderV1_Types_Request_Types_Order) GetDeckId() uint64 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *DeckChangeOrderV1_Types_Request_Types_Order) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

var File_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDesc = "" +
	"\n" +
	"Ctakasho/schema/lettuce_server/player_api/deck_change_order_v1.proto\x12(takasho.schema.lettuce_server.player_api\"\xe5\x01\n" +
	"\x11DeckChangeOrderV1\x1a\xcf\x01\n" +
	"\x05Types\x1a\xb9\x01\n" +
	"\aRequest\x12m\n" +
	"\x06orders\x18\x01 \x03(\v2U.takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request.Types.OrderR\x06orders\x1a?\n" +
	"\x05Types\x1a6\n" +
	"\x05Order\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\x04R\x06deckId\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x1a\n" +
	"\n" +
	"\bResponseBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_goTypes = []any{
	(*DeckChangeOrderV1)(nil),                           // 0: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1
	(*DeckChangeOrderV1_Types)(nil),                     // 1: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types
	(*DeckChangeOrderV1_Types_Request)(nil),             // 2: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request
	(*DeckChangeOrderV1_Types_Response)(nil),            // 3: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Response
	(*DeckChangeOrderV1_Types_Request_Types)(nil),       // 4: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request.Types
	(*DeckChangeOrderV1_Types_Request_Types_Order)(nil), // 5: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request.Types.Order
}
var file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_depIdxs = []int32{
	5, // 0: takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request.orders:type_name -> takasho.schema.lettuce_server.player_api.DeckChangeOrderV1.Types.Request.Types.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_init() }
func file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_deck_change_order_v1_proto_depIdxs = nil
}
