// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/error_code.proto

package player_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode_Types_Common int32

const (
	ErrorCode_Types_COMMON_UNSPECIFIED                   ErrorCode_Types_Common = 0
	ErrorCode_Types_COMMON_INVALID_SESSION               ErrorCode_Types_Common = 1001
	ErrorCode_Types_COMMON_SESSION_OVERWRITTEN           ErrorCode_Types_Common = 1002
	ErrorCode_Types_COMMON_INVALID_CLIENT                ErrorCode_Types_Common = 1003
	ErrorCode_Types_COMMON_INVALID_PLAYER_AVAILABLE      ErrorCode_Types_Common = 1004
	ErrorCode_Types_COMMON_UNDER_MAINTENANCE             ErrorCode_Types_Common = 1006
	ErrorCode_Types_COMMON_DELETED_PLAYER                ErrorCode_Types_Common = 1007
	ErrorCode_Types_COMMON_UNDER_PVP_PARTIAL_MAINTENANCE ErrorCode_Types_Common = 1008
	ErrorCode_Types_COMMON_FRAUDULENT_OPERATION          ErrorCode_Types_Common = 1009
)

// Enum value maps for ErrorCode_Types_Common.
var (
	ErrorCode_Types_Common_name = map[int32]string{
		0:    "COMMON_UNSPECIFIED",
		1001: "COMMON_INVALID_SESSION",
		1002: "COMMON_SESSION_OVERWRITTEN",
		1003: "COMMON_INVALID_CLIENT",
		1004: "COMMON_INVALID_PLAYER_AVAILABLE",
		1006: "COMMON_UNDER_MAINTENANCE",
		1007: "COMMON_DELETED_PLAYER",
		1008: "COMMON_UNDER_PVP_PARTIAL_MAINTENANCE",
		1009: "COMMON_FRAUDULENT_OPERATION",
	}
	ErrorCode_Types_Common_value = map[string]int32{
		"COMMON_UNSPECIFIED":                   0,
		"COMMON_INVALID_SESSION":               1001,
		"COMMON_SESSION_OVERWRITTEN":           1002,
		"COMMON_INVALID_CLIENT":                1003,
		"COMMON_INVALID_PLAYER_AVAILABLE":      1004,
		"COMMON_UNDER_MAINTENANCE":             1006,
		"COMMON_DELETED_PLAYER":                1007,
		"COMMON_UNDER_PVP_PARTIAL_MAINTENANCE": 1008,
		"COMMON_FRAUDULENT_OPERATION":          1009,
	}
)

func (x ErrorCode_Types_Common) Enum() *ErrorCode_Types_Common {
	p := new(ErrorCode_Types_Common)
	*p = x
	return p
}

func (x ErrorCode_Types_Common) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode_Types_Common) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode_Types_Common) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes[0]
}

func (x ErrorCode_Types_Common) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode_Types_Common.Descriptor instead.
func (ErrorCode_Types_Common) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescGZIP(), []int{0, 0, 0}
}

type ErrorCode_Types_Method int32

const (
	ErrorCode_Types_METHOD_UNSPECIFIED                                                      ErrorCode_Types_Method = 0
	ErrorCode_Types_METHOD_ILLEGAL_ARGUMENT                                                 ErrorCode_Types_Method = 2001
	ErrorCode_Types_METHOD_RESOURCE_NOT_FOUND                                               ErrorCode_Types_Method = 2002
	ErrorCode_Types_METHOD_RESOURCE_CONFLICT                                                ErrorCode_Types_Method = 2003
	ErrorCode_Types_METHOD_RESOURCE_INSUFFICIENT                                            ErrorCode_Types_Method = 2004
	ErrorCode_Types_METHOD_CARD_SKIN_EXCHANGE_IS_OUT_OF_TERM                                ErrorCode_Types_Method = 3401
	ErrorCode_Types_METHOD_FEED_IS_NOT_FOUND                                                ErrorCode_Types_Method = 3800
	ErrorCode_Types_METHOD_FEED_CHALLENGE_NUM_IS_INVALID                                    ErrorCode_Types_Method = 3801
	ErrorCode_Types_METHOD_FEED_CHALLENGE_POWER_IS_INSUFFICIENT                             ErrorCode_Types_Method = 3802
	ErrorCode_Types_METHOD_FEED_REVIVAL_CLOCK_IS_INSUFFICIENT                               ErrorCode_Types_Method = 3803
	ErrorCode_Types_METHOD_FEED_POKE_GOLD_IS_INSUFFICIENT                                   ErrorCode_Types_Method = 3804
	ErrorCode_Types_METHOD_FEED_HEAL_CHALLENGE_POWER_INSUFFICIENT_ITEMS                     ErrorCode_Types_Method = 3805
	ErrorCode_Types_METHOD_FEED_NON_TIME_SHORTENING_HEAL                                    ErrorCode_Types_Method = 3806
	ErrorCode_Types_METHOD_FEED_PACK_UNPACK_ORDER_TRANSACTION_ID_IS_NOT_FOUND               ErrorCode_Types_Method = 3807
	ErrorCode_Types_METHOD_FEED_SNOOP_ALREADY_SNOOPING_FEED                                 ErrorCode_Types_Method = 3808
	ErrorCode_Types_METHOD_FEED_SNOOP_IS_NOT_FOUND                                          ErrorCode_Types_Method = 3809
	ErrorCode_Types_METHOD_FEED_SNOOP_CHALLENGE_TYPE_IS_INVALID                             ErrorCode_Types_Method = 3810
	ErrorCode_Types_METHOD_FRIEND_ID_NOT_FOUND                                              ErrorCode_Types_Method = 3901
	ErrorCode_Types_METHOD_PLAYER_NICKNAME_NOT_FOUND                                        ErrorCode_Types_Method = 3902
	ErrorCode_Types_METHOD_SENDER_FRIEND_LIMIT_EXCEEDED                                     ErrorCode_Types_Method = 3903
	ErrorCode_Types_METHOD_RECEIVER_FRIEND_LIMIT_EXCEEDED                                   ErrorCode_Types_Method = 3904
	ErrorCode_Types_METHOD_SEND_FRIEND_REQUEST_LIMIT_EXCEEDED                               ErrorCode_Types_Method = 3905
	ErrorCode_Types_METHOD_RECEIVE_FRIEND_REQUEST_LIMIT_EXCEEDED                            ErrorCode_Types_Method = 3906
	ErrorCode_Types_METHOD_ALREADY_FRIENDS                                                  ErrorCode_Types_Method = 3907
	ErrorCode_Types_METHOD_FRIEND_NOT_FOUND                                                 ErrorCode_Types_Method = 3908
	ErrorCode_Types_METHOD_TRADE_PARTNER_SESSION_CONFLICT                                   ErrorCode_Types_Method = 4000
	ErrorCode_Types_METHOD_TRADE_SESSION_IS_EXPIRED                                         ErrorCode_Types_Method = 4001
	ErrorCode_Types_METHOD_TRADE_POWER_IS_INSUFFICIENT                                      ErrorCode_Types_Method = 4002
	ErrorCode_Types_METHOD_TRADE_CARD_STOCK_IS_INSUFFICIENT                                 ErrorCode_Types_Method = 4003
	ErrorCode_Types_METHOD_TRADE_ITEM_STOCK_IS_INSUFFICIENT                                 ErrorCode_Types_Method = 4004
	ErrorCode_Types_METHOD_TRADE_SUBMISSION_CARD_IS_NOT_ALLOWED                             ErrorCode_Types_Method = 4005
	ErrorCode_Types_METHOD_TRADE_RULE_HAS_CHANGED                                           ErrorCode_Types_Method = 4006
	ErrorCode_Types_METHOD_TRADE_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA         ErrorCode_Types_Method = 4007
	ErrorCode_Types_METHOD_TRADE_FEATURE_LOCKED                                             ErrorCode_Types_Method = 4008
	ErrorCode_Types_METHOD_TRADE_DEPOSIT_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA ErrorCode_Types_Method = 4009
	ErrorCode_Types_METHOD_MISSION_ALREADY_CLEARED                                          ErrorCode_Types_Method = 4301
	ErrorCode_Types_METHOD_MISSION_IS_OUT_OF_TERM                                           ErrorCode_Types_Method = 4302
	ErrorCode_Types_METHOD_MISSION_IS_NOT_FOUND                                             ErrorCode_Types_Method = 4303
	ErrorCode_Types_METHOD_INVALID_PREMIUM_MISSION                                          ErrorCode_Types_Method = 4304
	ErrorCode_Types_METHOD_MISSION_REWARD_OVERRIDE_MISMATCH                                 ErrorCode_Types_Method = 4305
	ErrorCode_Types_METHOD_PROFILE_NICKNAME_CHANGE_WITHIN_TIME_LIMIT                        ErrorCode_Types_Method = 5101
	ErrorCode_Types_METHOD_PROFILE_EMBLEMS_AMOUNT_EXCEED                                    ErrorCode_Types_Method = 5102
	ErrorCode_Types_METHOD_PROFILE_ICON_IS_INSUFFICIENT                                     ErrorCode_Types_Method = 5103
	ErrorCode_Types_METHOD_PROFILE_EMBLEM_IS_INSUFFICIENT                                   ErrorCode_Types_Method = 5104
	ErrorCode_Types_METHOD_PROFILE_IS_NOT_FOUND                                             ErrorCode_Types_Method = 5105
	ErrorCode_Types_METHOD_PROFILE_NICKNAME_LENGTH_EXCEED                                   ErrorCode_Types_Method = 5106
	ErrorCode_Types_METHOD_PLAYER_UNAVAILABLE                                               ErrorCode_Types_Method = 5500
	ErrorCode_Types_METHOD_MATCHING_HAS_NOT_BEEN_ESTABLISHED                                ErrorCode_Types_Method = 5803
	ErrorCode_Types_METHOD_FAILED_TO_ASSIGN_PVP_BATTLE                                      ErrorCode_Types_Method = 5804
	ErrorCode_Types_METHOD_MASTER_VERSION_MISMATCH                                          ErrorCode_Types_Method = 5805
	ErrorCode_Types_METHOD_PVP_OUT_OF_EVENT_SCHEDULE                                        ErrorCode_Types_Method = 5806
	ErrorCode_Types_METHOD_OUT_OF_SEASON                                                    ErrorCode_Types_Method = 6000
	ErrorCode_Types_METHOD_OUT_OF_SEASON_RESULT                                             ErrorCode_Types_Method = 6001
	ErrorCode_Types_METHOD_SEASON_CANCELLED                                                 ErrorCode_Types_Method = 6002
	ErrorCode_Types_METHOD_MY_DECK_NOT_FOUND                                                ErrorCode_Types_Method = 6101
	ErrorCode_Types_METHOD_RENTAL_DECK_NOT_FOUND                                            ErrorCode_Types_Method = 6102
	ErrorCode_Types_METHOD_SOLO_BATTLE_OUT_OF_SCHEDULE                                      ErrorCode_Types_Method = 6103
	ErrorCode_Types_METHOD_ID_TOKEN_EXPIRED                                                 ErrorCode_Types_Method = 6201
	ErrorCode_Types_METHOD_SYSTEM_INVALID_AGREEMENT_VERSION                                 ErrorCode_Types_Method = 6202
	ErrorCode_Types_METHOD_SYSTEM_INVALID_PARTIAL_MAINTENANCE_TYPE                          ErrorCode_Types_Method = 6203
	ErrorCode_Types_METHOD_TROPHY_ARGUMENT_IS_INVALID                                       ErrorCode_Types_Method = 6401
	ErrorCode_Types_METHOD_TROPHY_IS_ALREADY_CLEARED                                        ErrorCode_Types_Method = 6402
	ErrorCode_Types_METHOD_TROPHY_IS_NOT_FOUND                                              ErrorCode_Types_Method = 6403
	ErrorCode_Types_METHOD_TUTORIAL_INVALID_STEPS                                           ErrorCode_Types_Method = 6501
	ErrorCode_Types_METHOD_TUTORIAL_COULD_NOT_CHOICE_ROUTE                                  ErrorCode_Types_Method = 6502
	ErrorCode_Types_METHOD_TUTORIAL_ALREADY_PURCHASED_PACK                                  ErrorCode_Types_Method = 6503
	ErrorCode_Types_METHOD_PACK_MASTER_VERSION_MISMATCH                                     ErrorCode_Types_Method = 6601
	ErrorCode_Types_METHOD_PACK_PURCHASE_MASTER_VERSION_MISMATCH                            ErrorCode_Types_Method = 6701
	ErrorCode_Types_METHOD_GIVE_CARD_RECEIVER_DAILY_LIMIT_EXCEEDED                          ErrorCode_Types_Method = 6900
)

// Enum value maps for ErrorCode_Types_Method.
var (
	ErrorCode_Types_Method_name = map[int32]string{
		0:    "METHOD_UNSPECIFIED",
		2001: "METHOD_ILLEGAL_ARGUMENT",
		2002: "METHOD_RESOURCE_NOT_FOUND",
		2003: "METHOD_RESOURCE_CONFLICT",
		2004: "METHOD_RESOURCE_INSUFFICIENT",
		3401: "METHOD_CARD_SKIN_EXCHANGE_IS_OUT_OF_TERM",
		3800: "METHOD_FEED_IS_NOT_FOUND",
		3801: "METHOD_FEED_CHALLENGE_NUM_IS_INVALID",
		3802: "METHOD_FEED_CHALLENGE_POWER_IS_INSUFFICIENT",
		3803: "METHOD_FEED_REVIVAL_CLOCK_IS_INSUFFICIENT",
		3804: "METHOD_FEED_POKE_GOLD_IS_INSUFFICIENT",
		3805: "METHOD_FEED_HEAL_CHALLENGE_POWER_INSUFFICIENT_ITEMS",
		3806: "METHOD_FEED_NON_TIME_SHORTENING_HEAL",
		3807: "METHOD_FEED_PACK_UNPACK_ORDER_TRANSACTION_ID_IS_NOT_FOUND",
		3808: "METHOD_FEED_SNOOP_ALREADY_SNOOPING_FEED",
		3809: "METHOD_FEED_SNOOP_IS_NOT_FOUND",
		3810: "METHOD_FEED_SNOOP_CHALLENGE_TYPE_IS_INVALID",
		3901: "METHOD_FRIEND_ID_NOT_FOUND",
		3902: "METHOD_PLAYER_NICKNAME_NOT_FOUND",
		3903: "METHOD_SENDER_FRIEND_LIMIT_EXCEEDED",
		3904: "METHOD_RECEIVER_FRIEND_LIMIT_EXCEEDED",
		3905: "METHOD_SEND_FRIEND_REQUEST_LIMIT_EXCEEDED",
		3906: "METHOD_RECEIVE_FRIEND_REQUEST_LIMIT_EXCEEDED",
		3907: "METHOD_ALREADY_FRIENDS",
		3908: "METHOD_FRIEND_NOT_FOUND",
		4000: "METHOD_TRADE_PARTNER_SESSION_CONFLICT",
		4001: "METHOD_TRADE_SESSION_IS_EXPIRED",
		4002: "METHOD_TRADE_POWER_IS_INSUFFICIENT",
		4003: "METHOD_TRADE_CARD_STOCK_IS_INSUFFICIENT",
		4004: "METHOD_TRADE_ITEM_STOCK_IS_INSUFFICIENT",
		4005: "METHOD_TRADE_SUBMISSION_CARD_IS_NOT_ALLOWED",
		4006: "METHOD_TRADE_RULE_HAS_CHANGED",
		4007: "METHOD_TRADE_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA",
		4008: "METHOD_TRADE_FEATURE_LOCKED",
		4009: "METHOD_TRADE_DEPOSIT_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA",
		4301: "METHOD_MISSION_ALREADY_CLEARED",
		4302: "METHOD_MISSION_IS_OUT_OF_TERM",
		4303: "METHOD_MISSION_IS_NOT_FOUND",
		4304: "METHOD_INVALID_PREMIUM_MISSION",
		4305: "METHOD_MISSION_REWARD_OVERRIDE_MISMATCH",
		5101: "METHOD_PROFILE_NICKNAME_CHANGE_WITHIN_TIME_LIMIT",
		5102: "METHOD_PROFILE_EMBLEMS_AMOUNT_EXCEED",
		5103: "METHOD_PROFILE_ICON_IS_INSUFFICIENT",
		5104: "METHOD_PROFILE_EMBLEM_IS_INSUFFICIENT",
		5105: "METHOD_PROFILE_IS_NOT_FOUND",
		5106: "METHOD_PROFILE_NICKNAME_LENGTH_EXCEED",
		5500: "METHOD_PLAYER_UNAVAILABLE",
		5803: "METHOD_MATCHING_HAS_NOT_BEEN_ESTABLISHED",
		5804: "METHOD_FAILED_TO_ASSIGN_PVP_BATTLE",
		5805: "METHOD_MASTER_VERSION_MISMATCH",
		5806: "METHOD_PVP_OUT_OF_EVENT_SCHEDULE",
		6000: "METHOD_OUT_OF_SEASON",
		6001: "METHOD_OUT_OF_SEASON_RESULT",
		6002: "METHOD_SEASON_CANCELLED",
		6101: "METHOD_MY_DECK_NOT_FOUND",
		6102: "METHOD_RENTAL_DECK_NOT_FOUND",
		6103: "METHOD_SOLO_BATTLE_OUT_OF_SCHEDULE",
		6201: "METHOD_ID_TOKEN_EXPIRED",
		6202: "METHOD_SYSTEM_INVALID_AGREEMENT_VERSION",
		6203: "METHOD_SYSTEM_INVALID_PARTIAL_MAINTENANCE_TYPE",
		6401: "METHOD_TROPHY_ARGUMENT_IS_INVALID",
		6402: "METHOD_TROPHY_IS_ALREADY_CLEARED",
		6403: "METHOD_TROPHY_IS_NOT_FOUND",
		6501: "METHOD_TUTORIAL_INVALID_STEPS",
		6502: "METHOD_TUTORIAL_COULD_NOT_CHOICE_ROUTE",
		6503: "METHOD_TUTORIAL_ALREADY_PURCHASED_PACK",
		6601: "METHOD_PACK_MASTER_VERSION_MISMATCH",
		6701: "METHOD_PACK_PURCHASE_MASTER_VERSION_MISMATCH",
		6900: "METHOD_GIVE_CARD_RECEIVER_DAILY_LIMIT_EXCEEDED",
	}
	ErrorCode_Types_Method_value = map[string]int32{
		"METHOD_UNSPECIFIED":                                                      0,
		"METHOD_ILLEGAL_ARGUMENT":                                                 2001,
		"METHOD_RESOURCE_NOT_FOUND":                                               2002,
		"METHOD_RESOURCE_CONFLICT":                                                2003,
		"METHOD_RESOURCE_INSUFFICIENT":                                            2004,
		"METHOD_CARD_SKIN_EXCHANGE_IS_OUT_OF_TERM":                                3401,
		"METHOD_FEED_IS_NOT_FOUND":                                                3800,
		"METHOD_FEED_CHALLENGE_NUM_IS_INVALID":                                    3801,
		"METHOD_FEED_CHALLENGE_POWER_IS_INSUFFICIENT":                             3802,
		"METHOD_FEED_REVIVAL_CLOCK_IS_INSUFFICIENT":                               3803,
		"METHOD_FEED_POKE_GOLD_IS_INSUFFICIENT":                                   3804,
		"METHOD_FEED_HEAL_CHALLENGE_POWER_INSUFFICIENT_ITEMS":                     3805,
		"METHOD_FEED_NON_TIME_SHORTENING_HEAL":                                    3806,
		"METHOD_FEED_PACK_UNPACK_ORDER_TRANSACTION_ID_IS_NOT_FOUND":               3807,
		"METHOD_FEED_SNOOP_ALREADY_SNOOPING_FEED":                                 3808,
		"METHOD_FEED_SNOOP_IS_NOT_FOUND":                                          3809,
		"METHOD_FEED_SNOOP_CHALLENGE_TYPE_IS_INVALID":                             3810,
		"METHOD_FRIEND_ID_NOT_FOUND":                                              3901,
		"METHOD_PLAYER_NICKNAME_NOT_FOUND":                                        3902,
		"METHOD_SENDER_FRIEND_LIMIT_EXCEEDED":                                     3903,
		"METHOD_RECEIVER_FRIEND_LIMIT_EXCEEDED":                                   3904,
		"METHOD_SEND_FRIEND_REQUEST_LIMIT_EXCEEDED":                               3905,
		"METHOD_RECEIVE_FRIEND_REQUEST_LIMIT_EXCEEDED":                            3906,
		"METHOD_ALREADY_FRIENDS":                                                  3907,
		"METHOD_FRIEND_NOT_FOUND":                                                 3908,
		"METHOD_TRADE_PARTNER_SESSION_CONFLICT":                                   4000,
		"METHOD_TRADE_SESSION_IS_EXPIRED":                                         4001,
		"METHOD_TRADE_POWER_IS_INSUFFICIENT":                                      4002,
		"METHOD_TRADE_CARD_STOCK_IS_INSUFFICIENT":                                 4003,
		"METHOD_TRADE_ITEM_STOCK_IS_INSUFFICIENT":                                 4004,
		"METHOD_TRADE_SUBMISSION_CARD_IS_NOT_ALLOWED":                             4005,
		"METHOD_TRADE_RULE_HAS_CHANGED":                                           4006,
		"METHOD_TRADE_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA":         4007,
		"METHOD_TRADE_FEATURE_LOCKED":                                             4008,
		"METHOD_TRADE_DEPOSIT_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA": 4009,
		"METHOD_MISSION_ALREADY_CLEARED":                                          4301,
		"METHOD_MISSION_IS_OUT_OF_TERM":                                           4302,
		"METHOD_MISSION_IS_NOT_FOUND":                                             4303,
		"METHOD_INVALID_PREMIUM_MISSION":                                          4304,
		"METHOD_MISSION_REWARD_OVERRIDE_MISMATCH":                                 4305,
		"METHOD_PROFILE_NICKNAME_CHANGE_WITHIN_TIME_LIMIT":                        5101,
		"METHOD_PROFILE_EMBLEMS_AMOUNT_EXCEED":                                    5102,
		"METHOD_PROFILE_ICON_IS_INSUFFICIENT":                                     5103,
		"METHOD_PROFILE_EMBLEM_IS_INSUFFICIENT":                                   5104,
		"METHOD_PROFILE_IS_NOT_FOUND":                                             5105,
		"METHOD_PROFILE_NICKNAME_LENGTH_EXCEED":                                   5106,
		"METHOD_PLAYER_UNAVAILABLE":                                               5500,
		"METHOD_MATCHING_HAS_NOT_BEEN_ESTABLISHED":                                5803,
		"METHOD_FAILED_TO_ASSIGN_PVP_BATTLE":                                      5804,
		"METHOD_MASTER_VERSION_MISMATCH":                                          5805,
		"METHOD_PVP_OUT_OF_EVENT_SCHEDULE":                                        5806,
		"METHOD_OUT_OF_SEASON":                                                    6000,
		"METHOD_OUT_OF_SEASON_RESULT":                                             6001,
		"METHOD_SEASON_CANCELLED":                                                 6002,
		"METHOD_MY_DECK_NOT_FOUND":                                                6101,
		"METHOD_RENTAL_DECK_NOT_FOUND":                                            6102,
		"METHOD_SOLO_BATTLE_OUT_OF_SCHEDULE":                                      6103,
		"METHOD_ID_TOKEN_EXPIRED":                                                 6201,
		"METHOD_SYSTEM_INVALID_AGREEMENT_VERSION":                                 6202,
		"METHOD_SYSTEM_INVALID_PARTIAL_MAINTENANCE_TYPE":                          6203,
		"METHOD_TROPHY_ARGUMENT_IS_INVALID":                                       6401,
		"METHOD_TROPHY_IS_ALREADY_CLEARED":                                        6402,
		"METHOD_TROPHY_IS_NOT_FOUND":                                              6403,
		"METHOD_TUTORIAL_INVALID_STEPS":                                           6501,
		"METHOD_TUTORIAL_COULD_NOT_CHOICE_ROUTE":                                  6502,
		"METHOD_TUTORIAL_ALREADY_PURCHASED_PACK":                                  6503,
		"METHOD_PACK_MASTER_VERSION_MISMATCH":                                     6601,
		"METHOD_PACK_PURCHASE_MASTER_VERSION_MISMATCH":                            6701,
		"METHOD_GIVE_CARD_RECEIVER_DAILY_LIMIT_EXCEEDED":                          6900,
	}
)

func (x ErrorCode_Types_Method) Enum() *ErrorCode_Types_Method {
	p := new(ErrorCode_Types_Method)
	*p = x
	return p
}

func (x ErrorCode_Types_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode_Types_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes[1].Descriptor()
}

func (ErrorCode_Types_Method) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes[1]
}

func (x ErrorCode_Types_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode_Types_Method.Descriptor instead.
func (ErrorCode_Types_Method) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescGZIP(), []int{0, 0, 1}
}

type ErrorCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorCode) Reset() {
	*x = ErrorCode{}
	mi := &file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCode) ProtoMessage() {}

func (x *ErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCode.ProtoReflect.Descriptor instead.
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescGZIP(), []int{0}
}

type ErrorCode_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorCode_Types) Reset() {
	*x = ErrorCode_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorCode_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCode_Types) ProtoMessage() {}

func (x *ErrorCode_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCode_Types.ProtoReflect.Descriptor instead.
func (*ErrorCode_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescGZIP(), []int{0, 0}
}

var File_takasho_schema_lettuce_server_player_api_error_code_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDesc = "" +
	"\n" +
	"9takasho/schema/lettuce_server/player_api/error_code.proto\x12(takasho.schema.lettuce_server.player_api\"\x82\x19\n" +
	"\tErrorCode\x1a\xf4\x18\n" +
	"\x05Types\"\xa8\x02\n" +
	"\x06Common\x12\x16\n" +
	"\x12COMMON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x16COMMON_INVALID_SESSION\x10\xe9\a\x12\x1f\n" +
	"\x1aCOMMON_SESSION_OVERWRITTEN\x10\xea\a\x12\x1a\n" +
	"\x15COMMON_INVALID_CLIENT\x10\xeb\a\x12$\n" +
	"\x1fCOMMON_INVALID_PLAYER_AVAILABLE\x10\xec\a\x12\x1d\n" +
	"\x18COMMON_UNDER_MAINTENANCE\x10\xee\a\x12\x1a\n" +
	"\x15COMMON_DELETED_PLAYER\x10\xef\a\x12)\n" +
	"$COMMON_UNDER_PVP_PARTIAL_MAINTENANCE\x10\xf0\a\x12 \n" +
	"\x1bCOMMON_FRAUDULENT_OPERATION\x10\xf1\a\"\xbf\x16\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x17METHOD_ILLEGAL_ARGUMENT\x10\xd1\x0f\x12\x1e\n" +
	"\x19METHOD_RESOURCE_NOT_FOUND\x10\xd2\x0f\x12\x1d\n" +
	"\x18METHOD_RESOURCE_CONFLICT\x10\xd3\x0f\x12!\n" +
	"\x1cMETHOD_RESOURCE_INSUFFICIENT\x10\xd4\x0f\x12-\n" +
	"(METHOD_CARD_SKIN_EXCHANGE_IS_OUT_OF_TERM\x10\xc9\x1a\x12\x1d\n" +
	"\x18METHOD_FEED_IS_NOT_FOUND\x10\xd8\x1d\x12)\n" +
	"$METHOD_FEED_CHALLENGE_NUM_IS_INVALID\x10\xd9\x1d\x120\n" +
	"+METHOD_FEED_CHALLENGE_POWER_IS_INSUFFICIENT\x10\xda\x1d\x12.\n" +
	")METHOD_FEED_REVIVAL_CLOCK_IS_INSUFFICIENT\x10\xdb\x1d\x12*\n" +
	"%METHOD_FEED_POKE_GOLD_IS_INSUFFICIENT\x10\xdc\x1d\x128\n" +
	"3METHOD_FEED_HEAL_CHALLENGE_POWER_INSUFFICIENT_ITEMS\x10\xdd\x1d\x12)\n" +
	"$METHOD_FEED_NON_TIME_SHORTENING_HEAL\x10\xde\x1d\x12>\n" +
	"9METHOD_FEED_PACK_UNPACK_ORDER_TRANSACTION_ID_IS_NOT_FOUND\x10\xdf\x1d\x12,\n" +
	"'METHOD_FEED_SNOOP_ALREADY_SNOOPING_FEED\x10\xe0\x1d\x12#\n" +
	"\x1eMETHOD_FEED_SNOOP_IS_NOT_FOUND\x10\xe1\x1d\x120\n" +
	"+METHOD_FEED_SNOOP_CHALLENGE_TYPE_IS_INVALID\x10\xe2\x1d\x12\x1f\n" +
	"\x1aMETHOD_FRIEND_ID_NOT_FOUND\x10\xbd\x1e\x12%\n" +
	" METHOD_PLAYER_NICKNAME_NOT_FOUND\x10\xbe\x1e\x12(\n" +
	"#METHOD_SENDER_FRIEND_LIMIT_EXCEEDED\x10\xbf\x1e\x12*\n" +
	"%METHOD_RECEIVER_FRIEND_LIMIT_EXCEEDED\x10\xc0\x1e\x12.\n" +
	")METHOD_SEND_FRIEND_REQUEST_LIMIT_EXCEEDED\x10\xc1\x1e\x121\n" +
	",METHOD_RECEIVE_FRIEND_REQUEST_LIMIT_EXCEEDED\x10\xc2\x1e\x12\x1b\n" +
	"\x16METHOD_ALREADY_FRIENDS\x10\xc3\x1e\x12\x1c\n" +
	"\x17METHOD_FRIEND_NOT_FOUND\x10\xc4\x1e\x12*\n" +
	"%METHOD_TRADE_PARTNER_SESSION_CONFLICT\x10\xa0\x1f\x12$\n" +
	"\x1fMETHOD_TRADE_SESSION_IS_EXPIRED\x10\xa1\x1f\x12'\n" +
	"\"METHOD_TRADE_POWER_IS_INSUFFICIENT\x10\xa2\x1f\x12,\n" +
	"'METHOD_TRADE_CARD_STOCK_IS_INSUFFICIENT\x10\xa3\x1f\x12,\n" +
	"'METHOD_TRADE_ITEM_STOCK_IS_INSUFFICIENT\x10\xa4\x1f\x120\n" +
	"+METHOD_TRADE_SUBMISSION_CARD_IS_NOT_ALLOWED\x10\xa5\x1f\x12\"\n" +
	"\x1dMETHOD_TRADE_RULE_HAS_CHANGED\x10\xa6\x1f\x12D\n" +
	"?METHOD_TRADE_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA\x10\xa7\x1f\x12 \n" +
	"\x1bMETHOD_TRADE_FEATURE_LOCKED\x10\xa8\x1f\x12L\n" +
	"GMETHOD_TRADE_DEPOSIT_ITEM_CONSUMPTION_DOES_NOT_MATCH_LATEST_MASTER_DATA\x10\xa9\x1f\x12#\n" +
	"\x1eMETHOD_MISSION_ALREADY_CLEARED\x10\xcd!\x12\"\n" +
	"\x1dMETHOD_MISSION_IS_OUT_OF_TERM\x10\xce!\x12 \n" +
	"\x1bMETHOD_MISSION_IS_NOT_FOUND\x10\xcf!\x12#\n" +
	"\x1eMETHOD_INVALID_PREMIUM_MISSION\x10\xd0!\x12,\n" +
	"'METHOD_MISSION_REWARD_OVERRIDE_MISMATCH\x10\xd1!\x125\n" +
	"0METHOD_PROFILE_NICKNAME_CHANGE_WITHIN_TIME_LIMIT\x10\xed'\x12)\n" +
	"$METHOD_PROFILE_EMBLEMS_AMOUNT_EXCEED\x10\xee'\x12(\n" +
	"#METHOD_PROFILE_ICON_IS_INSUFFICIENT\x10\xef'\x12*\n" +
	"%METHOD_PROFILE_EMBLEM_IS_INSUFFICIENT\x10\xf0'\x12 \n" +
	"\x1bMETHOD_PROFILE_IS_NOT_FOUND\x10\xf1'\x12*\n" +
	"%METHOD_PROFILE_NICKNAME_LENGTH_EXCEED\x10\xf2'\x12\x1e\n" +
	"\x19METHOD_PLAYER_UNAVAILABLE\x10\xfc*\x12-\n" +
	"(METHOD_MATCHING_HAS_NOT_BEEN_ESTABLISHED\x10\xab-\x12'\n" +
	"\"METHOD_FAILED_TO_ASSIGN_PVP_BATTLE\x10\xac-\x12#\n" +
	"\x1eMETHOD_MASTER_VERSION_MISMATCH\x10\xad-\x12%\n" +
	" METHOD_PVP_OUT_OF_EVENT_SCHEDULE\x10\xae-\x12\x19\n" +
	"\x14METHOD_OUT_OF_SEASON\x10\xf0.\x12 \n" +
	"\x1bMETHOD_OUT_OF_SEASON_RESULT\x10\xf1.\x12\x1c\n" +
	"\x17METHOD_SEASON_CANCELLED\x10\xf2.\x12\x1d\n" +
	"\x18METHOD_MY_DECK_NOT_FOUND\x10\xd5/\x12!\n" +
	"\x1cMETHOD_RENTAL_DECK_NOT_FOUND\x10\xd6/\x12'\n" +
	"\"METHOD_SOLO_BATTLE_OUT_OF_SCHEDULE\x10\xd7/\x12\x1c\n" +
	"\x17METHOD_ID_TOKEN_EXPIRED\x10\xb90\x12,\n" +
	"'METHOD_SYSTEM_INVALID_AGREEMENT_VERSION\x10\xba0\x123\n" +
	".METHOD_SYSTEM_INVALID_PARTIAL_MAINTENANCE_TYPE\x10\xbb0\x12&\n" +
	"!METHOD_TROPHY_ARGUMENT_IS_INVALID\x10\x812\x12%\n" +
	" METHOD_TROPHY_IS_ALREADY_CLEARED\x10\x822\x12\x1f\n" +
	"\x1aMETHOD_TROPHY_IS_NOT_FOUND\x10\x832\x12\"\n" +
	"\x1dMETHOD_TUTORIAL_INVALID_STEPS\x10\xe52\x12+\n" +
	"&METHOD_TUTORIAL_COULD_NOT_CHOICE_ROUTE\x10\xe62\x12+\n" +
	"&METHOD_TUTORIAL_ALREADY_PURCHASED_PACK\x10\xe72\x12(\n" +
	"#METHOD_PACK_MASTER_VERSION_MISMATCH\x10\xc93\x121\n" +
	",METHOD_PACK_PURCHASE_MASTER_VERSION_MISMATCH\x10\xad4\x123\n" +
	".METHOD_GIVE_CARD_RECEIVER_DAILY_LIMIT_EXCEEDED\x10\xf45BoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_takasho_schema_lettuce_server_player_api_error_code_proto_goTypes = []any{
	(ErrorCode_Types_Common)(0), // 0: takasho.schema.lettuce_server.player_api.ErrorCode.Types.Common
	(ErrorCode_Types_Method)(0), // 1: takasho.schema.lettuce_server.player_api.ErrorCode.Types.Method
	(*ErrorCode)(nil),           // 2: takasho.schema.lettuce_server.player_api.ErrorCode
	(*ErrorCode_Types)(nil),     // 3: takasho.schema.lettuce_server.player_api.ErrorCode.Types
}
var file_takasho_schema_lettuce_server_player_api_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_error_code_proto_init() }
func file_takasho_schema_lettuce_server_player_api_error_code_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_error_code_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_error_code_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_error_code_proto_depIdxs,
		EnumInfos:         file_takasho_schema_lettuce_server_player_api_error_code_proto_enumTypes,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_error_code_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_error_code_proto = out.File
	file_takasho_schema_lettuce_server_player_api_error_code_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_error_code_proto_depIdxs = nil
}
