// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/fave_insight_v1.proto

package player_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaveInsightV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaveInsightV1) Reset() {
	*x = FaveInsightV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaveInsightV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaveInsightV1) ProtoMessage() {}

func (x *FaveInsightV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaveInsightV1.ProtoReflect.Descriptor instead.
func (*FaveInsightV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescGZIP(), []int{0}
}

type FaveInsightV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaveInsightV1_Types) Reset() {
	*x = FaveInsightV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaveInsightV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaveInsightV1_Types) ProtoMessage() {}

func (x *FaveInsightV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaveInsightV1_Types.ProtoReflect.Descriptor instead.
func (*FaveInsightV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescGZIP(), []int{0, 0}
}

type FaveInsightV1_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colorless     bool                   `protobuf:"varint,1,opt,name=colorless,proto3" json:"colorless,omitempty"`
	Grass         bool                   `protobuf:"varint,2,opt,name=grass,proto3" json:"grass,omitempty"`
	Fire          bool                   `protobuf:"varint,3,opt,name=fire,proto3" json:"fire,omitempty"`
	Water         bool                   `protobuf:"varint,4,opt,name=water,proto3" json:"water,omitempty"`
	Lightning     bool                   `protobuf:"varint,5,opt,name=lightning,proto3" json:"lightning,omitempty"`
	Psychic       bool                   `protobuf:"varint,6,opt,name=psychic,proto3" json:"psychic,omitempty"`
	Fighting      bool                   `protobuf:"varint,7,opt,name=fighting,proto3" json:"fighting,omitempty"`
	Darkness      bool                   `protobuf:"varint,8,opt,name=darkness,proto3" json:"darkness,omitempty"`
	Metal         bool                   `protobuf:"varint,9,opt,name=metal,proto3" json:"metal,omitempty"`
	Dragon        bool                   `protobuf:"varint,10,opt,name=dragon,proto3" json:"dragon,omitempty"`
	Nickname      string                 `protobuf:"bytes,11,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaveInsightV1_Types_Request) Reset() {
	*x = FaveInsightV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaveInsightV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaveInsightV1_Types_Request) ProtoMessage() {}

func (x *FaveInsightV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaveInsightV1_Types_Request.ProtoReflect.Descriptor instead.
func (*FaveInsightV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *FaveInsightV1_Types_Request) GetColorless() bool {
	if x != nil {
		return x.Colorless
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetGrass() bool {
	if x != nil {
		return x.Grass
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetFire() bool {
	if x != nil {
		return x.Fire
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetWater() bool {
	if x != nil {
		return x.Water
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetLightning() bool {
	if x != nil {
		return x.Lightning
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetPsychic() bool {
	if x != nil {
		return x.Psychic
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetFighting() bool {
	if x != nil {
		return x.Fighting
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetDarkness() bool {
	if x != nil {
		return x.Darkness
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetMetal() bool {
	if x != nil {
		return x.Metal
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetDragon() bool {
	if x != nil {
		return x.Dragon
	}
	return false
}

func (x *FaveInsightV1_Types_Request) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type FaveInsightV1_Types_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaveInsightV1_Types_Response) Reset() {
	*x = FaveInsightV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaveInsightV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaveInsightV1_Types_Response) ProtoMessage() {}

func (x *FaveInsightV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaveInsightV1_Types_Response.ProtoReflect.Descriptor instead.
func (*FaveInsightV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

var File_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDesc = "" +
	"\n" +
	">takasho/schema/lettuce_server/player_api/fave_insight_v1.proto\x12(takasho.schema.lettuce_server.player_api\"\xc9\x02\n" +
	"\rFaveInsightV1\x1a\xb7\x02\n" +
	"\x05Types\x1a\xa1\x02\n" +
	"\aRequest\x12\x1c\n" +
	"\tcolorless\x18\x01 \x01(\bR\tcolorless\x12\x14\n" +
	"\x05grass\x18\x02 \x01(\bR\x05grass\x12\x12\n" +
	"\x04fire\x18\x03 \x01(\bR\x04fire\x12\x14\n" +
	"\x05water\x18\x04 \x01(\bR\x05water\x12\x1c\n" +
	"\tlightning\x18\x05 \x01(\bR\tlightning\x12\x18\n" +
	"\apsychic\x18\x06 \x01(\bR\apsychic\x12\x1a\n" +
	"\bfighting\x18\a \x01(\bR\bfighting\x12\x1a\n" +
	"\bdarkness\x18\b \x01(\bR\bdarkness\x12\x14\n" +
	"\x05metal\x18\t \x01(\bR\x05metal\x12\x16\n" +
	"\x06dragon\x18\n" +
	" \x01(\bR\x06dragon\x12\x1a\n" +
	"\bnickname\x18\v \x01(\tR\bnickname\x1a\n" +
	"\n" +
	"\bResponseBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_goTypes = []any{
	(*FaveInsightV1)(nil),                // 0: takasho.schema.lettuce_server.player_api.FaveInsightV1
	(*FaveInsightV1_Types)(nil),          // 1: takasho.schema.lettuce_server.player_api.FaveInsightV1.Types
	(*FaveInsightV1_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.FaveInsightV1.Types.Request
	(*FaveInsightV1_Types_Response)(nil), // 3: takasho.schema.lettuce_server.player_api.FaveInsightV1.Types.Response
}
var file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_init() }
func file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_fave_insight_v1_proto_depIdxs = nil
}
