syntax = "proto3";

package takasho.schema.lettuce_server.player_api;

message FriendSetFavoriteV1 {
  message Types {
    message Request {
      message Types {
        enum FavoriteUpdateType {
          FAVORITE_UPDATE_TYPE_UNSPECIFIED = 0;
          FAVORITE_UPDATE_TYPE_ADD = 1;
          FAVORITE_UPDATE_TYPE_REMOVE = 2;
        }
      }
      string friend_player_id = 100;
      FriendSetFavoriteV1.Types.Request.Types.FavoriteUpdateType favorite_update_type = 200;
    }
    message Response {
      repeated string favorite_player_ids = 100;
    }
  }
}
