// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/friend_cancel_sent_requests_v1.proto

package player_api

import (
	friend "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/friend"
	player_profile "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/player_profile"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendCancelSentRequestsV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendCancelSentRequestsV1) Reset() {
	*x = FriendCancelSentRequestsV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendCancelSentRequestsV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendCancelSentRequestsV1) ProtoMessage() {}

func (x *FriendCancelSentRequestsV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendCancelSentRequestsV1.ProtoReflect.Descriptor instead.
func (*FriendCancelSentRequestsV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescGZIP(), []int{0}
}

type FriendCancelSentRequestsV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendCancelSentRequestsV1_Types) Reset() {
	*x = FriendCancelSentRequestsV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendCancelSentRequestsV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendCancelSentRequestsV1_Types) ProtoMessage() {}

func (x *FriendCancelSentRequestsV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendCancelSentRequestsV1_Types.ProtoReflect.Descriptor instead.
func (*FriendCancelSentRequestsV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescGZIP(), []int{0, 0}
}

type FriendCancelSentRequestsV1_Types_Request struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiverPlayerIds []string               `protobuf:"bytes,1,rep,name=receiver_player_ids,json=receiverPlayerIds,proto3" json:"receiver_player_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FriendCancelSentRequestsV1_Types_Request) Reset() {
	*x = FriendCancelSentRequestsV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendCancelSentRequestsV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendCancelSentRequestsV1_Types_Request) ProtoMessage() {}

func (x *FriendCancelSentRequestsV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendCancelSentRequestsV1_Types_Request.ProtoReflect.Descriptor instead.
func (*FriendCancelSentRequestsV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *FriendCancelSentRequestsV1_Types_Request) GetReceiverPlayerIds() []string {
	if x != nil {
		return x.ReceiverPlayerIds
	}
	return nil
}

type FriendCancelSentRequestsV1_Types_Response struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	SentFriendRequests []*friend.FriendRequest        `protobuf:"bytes,1,rep,name=sent_friend_requests,json=sentFriendRequests,proto3" json:"sent_friend_requests,omitempty"`
	Profiles           []*player_profile.ProfileSpine `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FriendCancelSentRequestsV1_Types_Response) Reset() {
	*x = FriendCancelSentRequestsV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendCancelSentRequestsV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendCancelSentRequestsV1_Types_Response) ProtoMessage() {}

func (x *FriendCancelSentRequestsV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendCancelSentRequestsV1_Types_Response.ProtoReflect.Descriptor instead.
func (*FriendCancelSentRequestsV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *FriendCancelSentRequestsV1_Types_Response) GetSentFriendRequests() []*friend.FriendRequest {
	if x != nil {
		return x.SentFriendRequests
	}
	return nil
}

func (x *FriendCancelSentRequestsV1_Types_Response) GetProfiles() []*player_profile.ProfileSpine {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDesc = "" +
	"\n" +
	"Mtakasho/schema/lettuce_server/player_api/friend_cancel_sent_requests_v1.proto\x12(takasho.schema.lettuce_server.player_api\x1aBtakasho/schema/lettuce_server/resource/friend/friend_request.proto\x1aItakasho/schema/lettuce_server/resource/player_profile/profile_spine.proto\"\xbf\x02\n" +
	"\x1aFriendCancelSentRequestsV1\x1a\xa0\x02\n" +
	"\x05Types\x1a9\n" +
	"\aRequest\x12.\n" +
	"\x13receiver_player_ids\x18\x01 \x03(\tR\x11receiverPlayerIds\x1a\xdb\x01\n" +
	"\bResponse\x12n\n" +
	"\x14sent_friend_requests\x18\x01 \x03(\v2<.takasho.schema.lettuce_server.resource.friend.FriendRequestR\x12sentFriendRequests\x12_\n" +
	"\bprofiles\x18\x02 \x03(\v2C.takasho.schema.lettuce_server.resource.player_profile.ProfileSpineR\bprofilesBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_goTypes = []any{
	(*FriendCancelSentRequestsV1)(nil),                // 0: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1
	(*FriendCancelSentRequestsV1_Types)(nil),          // 1: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1.Types
	(*FriendCancelSentRequestsV1_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1.Types.Request
	(*FriendCancelSentRequestsV1_Types_Response)(nil), // 3: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1.Types.Response
	(*friend.FriendRequest)(nil),                      // 4: takasho.schema.lettuce_server.resource.friend.FriendRequest
	(*player_profile.ProfileSpine)(nil),               // 5: takasho.schema.lettuce_server.resource.player_profile.ProfileSpine
}
var file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1.Types.Response.sent_friend_requests:type_name -> takasho.schema.lettuce_server.resource.friend.FriendRequest
	5, // 1: takasho.schema.lettuce_server.player_api.FriendCancelSentRequestsV1.Types.Response.profiles:type_name -> takasho.schema.lettuce_server.resource.player_profile.ProfileSpine
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_init()
}
func file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_friend_cancel_sent_requests_v1_proto_depIdxs = nil
}
