// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/give_card_execute_v1.proto

package player_api

import (
	card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card"
	give_card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/give_card"
	player_resources "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/player_resources"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GiveCardExecuteV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveCardExecuteV1) Reset() {
	*x = GiveCardExecuteV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveCardExecuteV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveCardExecuteV1) ProtoMessage() {}

func (x *GiveCardExecuteV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveCardExecuteV1.ProtoReflect.Descriptor instead.
func (*GiveCardExecuteV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescGZIP(), []int{0}
}

type GiveCardExecuteV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveCardExecuteV1_Types) Reset() {
	*x = GiveCardExecuteV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveCardExecuteV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveCardExecuteV1_Types) ProtoMessage() {}

func (x *GiveCardExecuteV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveCardExecuteV1_Types.ProtoReflect.Descriptor instead.
func (*GiveCardExecuteV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescGZIP(), []int{0, 0}
}

type GiveCardExecuteV1_Types_Request struct {
	state            protoimpl.MessageState              `protogen:"open.v1"`
	ReceiverPlayerId string                              `protobuf:"bytes,100,opt,name=receiver_player_id,json=receiverPlayerId,proto3" json:"receiver_player_id,omitempty"`
	Card             *card.CardInstance                  `protobuf:"bytes,200,opt,name=card,proto3" json:"card,omitempty"`
	Statistics       *give_card.GiveCardResultStatistics `protobuf:"bytes,300,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GiveCardExecuteV1_Types_Request) Reset() {
	*x = GiveCardExecuteV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveCardExecuteV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveCardExecuteV1_Types_Request) ProtoMessage() {}

func (x *GiveCardExecuteV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveCardExecuteV1_Types_Request.ProtoReflect.Descriptor instead.
func (*GiveCardExecuteV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GiveCardExecuteV1_Types_Request) GetReceiverPlayerId() string {
	if x != nil {
		return x.ReceiverPlayerId
	}
	return ""
}

func (x *GiveCardExecuteV1_Types_Request) GetCard() *card.CardInstance {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *GiveCardExecuteV1_Types_Request) GetStatistics() *give_card.GiveCardResultStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GiveCardExecuteV1_Types_Response struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	PlayerResources *player_resources.PlayerResources `protobuf:"bytes,100,opt,name=player_resources,json=playerResources,proto3" json:"player_resources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GiveCardExecuteV1_Types_Response) Reset() {
	*x = GiveCardExecuteV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveCardExecuteV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveCardExecuteV1_Types_Response) ProtoMessage() {}

func (x *GiveCardExecuteV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveCardExecuteV1_Types_Response.ProtoReflect.Descriptor instead.
func (*GiveCardExecuteV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *GiveCardExecuteV1_Types_Response) GetPlayerResources() *player_resources.PlayerResources {
	if x != nil {
		return x.PlayerResources
	}
	return nil
}

var File_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDesc = "" +
	"\n" +
	"Ctakasho/schema/lettuce_server/player_api/give_card_execute_v1.proto\x12(takasho.schema.lettuce_server.player_api\x1a?takasho/schema/lettuce_server/resource/card/card_instance.proto\x1aRtakasho/schema/lettuce_server/resource/give_card/give_card_result_statistics.proto\x1aNtakasho/schema/lettuce_server/resource/player_resources/player_resources.proto\"\x95\x03\n" +
	"\x11GiveCardExecuteV1\x1a\xff\x02\n" +
	"\x05Types\x1a\xf4\x01\n" +
	"\aRequest\x12,\n" +
	"\x12receiver_player_id\x18d \x01(\tR\x10receiverPlayerId\x12N\n" +
	"\x04card\x18\xc8\x01 \x01(\v29.takasho.schema.lettuce_server.resource.card.CardInstanceR\x04card\x12k\n" +
	"\n" +
	"statistics\x18\xac\x02 \x01(\v2J.takasho.schema.lettuce_server.resource.give_card.GiveCardResultStatisticsR\n" +
	"statistics\x1a\x7f\n" +
	"\bResponse\x12s\n" +
	"\x10player_resources\x18d \x01(\v2H.takasho.schema.lettuce_server.resource.player_resources.PlayerResourcesR\x0fplayerResourcesBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_goTypes = []any{
	(*GiveCardExecuteV1)(nil),                  // 0: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1
	(*GiveCardExecuteV1_Types)(nil),            // 1: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types
	(*GiveCardExecuteV1_Types_Request)(nil),    // 2: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types.Request
	(*GiveCardExecuteV1_Types_Response)(nil),   // 3: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types.Response
	(*card.CardInstance)(nil),                  // 4: takasho.schema.lettuce_server.resource.card.CardInstance
	(*give_card.GiveCardResultStatistics)(nil), // 5: takasho.schema.lettuce_server.resource.give_card.GiveCardResultStatistics
	(*player_resources.PlayerResources)(nil),   // 6: takasho.schema.lettuce_server.resource.player_resources.PlayerResources
}
var file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types.Request.card:type_name -> takasho.schema.lettuce_server.resource.card.CardInstance
	5, // 1: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types.Request.statistics:type_name -> takasho.schema.lettuce_server.resource.give_card.GiveCardResultStatistics
	6, // 2: takasho.schema.lettuce_server.player_api.GiveCardExecuteV1.Types.Response.player_resources:type_name -> takasho.schema.lettuce_server.resource.player_resources.PlayerResources
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_init() }
func file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_give_card_execute_v1_proto_depIdxs = nil
}
