// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/player_level_may_level_up_v1.proto

package player_api

import (
	item_acquisition "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/item_acquisition"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerLevelMayLevelUpV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLevelMayLevelUpV1) Reset() {
	*x = PlayerLevelMayLevelUpV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelMayLevelUpV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelMayLevelUpV1) ProtoMessage() {}

func (x *PlayerLevelMayLevelUpV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelMayLevelUpV1.ProtoReflect.Descriptor instead.
func (*PlayerLevelMayLevelUpV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescGZIP(), []int{0}
}

type PlayerLevelMayLevelUpV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLevelMayLevelUpV1_Types) Reset() {
	*x = PlayerLevelMayLevelUpV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelMayLevelUpV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelMayLevelUpV1_Types) ProtoMessage() {}

func (x *PlayerLevelMayLevelUpV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelMayLevelUpV1_Types.ProtoReflect.Descriptor instead.
func (*PlayerLevelMayLevelUpV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerLevelMayLevelUpV1_Types_Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=current_timestamp,json=currentTimestamp,proto3" json:"current_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerLevelMayLevelUpV1_Types_Request) Reset() {
	*x = PlayerLevelMayLevelUpV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelMayLevelUpV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelMayLevelUpV1_Types_Request) ProtoMessage() {}

func (x *PlayerLevelMayLevelUpV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelMayLevelUpV1_Types_Request.ProtoReflect.Descriptor instead.
func (*PlayerLevelMayLevelUpV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PlayerLevelMayLevelUpV1_Types_Request) GetCurrentTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentTimestamp
	}
	return nil
}

type PlayerLevelMayLevelUpV1_Types_Response struct {
	state                 protoimpl.MessageState                  `protogen:"open.v1"`
	PreviousLevel         int64                                   `protobuf:"varint,1,opt,name=previous_level,json=previousLevel,proto3" json:"previous_level,omitempty"`
	CurrentLevel          int64                                   `protobuf:"varint,2,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	Exp                   int64                                   `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	ItemAcquisitionResult *item_acquisition.ItemAcquisitionResult `protobuf:"bytes,14,opt,name=item_acquisition_result,json=itemAcquisitionResult,proto3" json:"item_acquisition_result,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) Reset() {
	*x = PlayerLevelMayLevelUpV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelMayLevelUpV1_Types_Response) ProtoMessage() {}

func (x *PlayerLevelMayLevelUpV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelMayLevelUpV1_Types_Response.ProtoReflect.Descriptor instead.
func (*PlayerLevelMayLevelUpV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) GetPreviousLevel() int64 {
	if x != nil {
		return x.PreviousLevel
	}
	return 0
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) GetCurrentLevel() int64 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerLevelMayLevelUpV1_Types_Response) GetItemAcquisitionResult() *item_acquisition.ItemAcquisitionResult {
	if x != nil {
		return x.ItemAcquisitionResult
	}
	return nil
}

var File_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDesc = "" +
	"\n" +
	"Ktakasho/schema/lettuce_server/player_api/player_level_may_level_up_v1.proto\x12(takasho.schema.lettuce_server.player_api\x1a\x1fgoogle/protobuf/timestamp.proto\x1aUtakasho/schema/lettuce_server/resource/item_acquisition/item_acquisition_result.proto\"\xeb\x02\n" +
	"\x17PlayerLevelMayLevelUpV1\x1a\xcf\x02\n" +
	"\x05Types\x1aR\n" +
	"\aRequest\x12G\n" +
	"\x11current_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x10currentTimestamp\x1a\xf1\x01\n" +
	"\bResponse\x12%\n" +
	"\x0eprevious_level\x18\x01 \x01(\x03R\rpreviousLevel\x12#\n" +
	"\rcurrent_level\x18\x02 \x01(\x03R\fcurrentLevel\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x86\x01\n" +
	"\x17item_acquisition_result\x18\x0e \x01(\v2N.takasho.schema.lettuce_server.resource.item_acquisition.ItemAcquisitionResultR\x15itemAcquisitionResultBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_goTypes = []any{
	(*PlayerLevelMayLevelUpV1)(nil),                // 0: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1
	(*PlayerLevelMayLevelUpV1_Types)(nil),          // 1: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1.Types
	(*PlayerLevelMayLevelUpV1_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1.Types.Request
	(*PlayerLevelMayLevelUpV1_Types_Response)(nil), // 3: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1.Types.Response
	(*timestamppb.Timestamp)(nil),                  // 4: google.protobuf.Timestamp
	(*item_acquisition.ItemAcquisitionResult)(nil), // 5: takasho.schema.lettuce_server.resource.item_acquisition.ItemAcquisitionResult
}
var file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1.Types.Request.current_timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: takasho.schema.lettuce_server.player_api.PlayerLevelMayLevelUpV1.Types.Response.item_acquisition_result:type_name -> takasho.schema.lettuce_server.resource.item_acquisition.ItemAcquisitionResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_init() }
func file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_player_level_may_level_up_v1_proto_depIdxs = nil
}
