// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/pvp_casual_request_public_matching_v2.proto

package player_api

import (
	pvp "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/pvp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PvpCasualRequestPublicMatchingV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpCasualRequestPublicMatchingV2) Reset() {
	*x = PvpCasualRequestPublicMatchingV2{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualRequestPublicMatchingV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualRequestPublicMatchingV2) ProtoMessage() {}

func (x *PvpCasualRequestPublicMatchingV2) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualRequestPublicMatchingV2.ProtoReflect.Descriptor instead.
func (*PvpCasualRequestPublicMatchingV2) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescGZIP(), []int{0}
}

type PvpCasualRequestPublicMatchingV2_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpCasualRequestPublicMatchingV2_Types) Reset() {
	*x = PvpCasualRequestPublicMatchingV2_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualRequestPublicMatchingV2_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualRequestPublicMatchingV2_Types) ProtoMessage() {}

func (x *PvpCasualRequestPublicMatchingV2_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualRequestPublicMatchingV2_Types.ProtoReflect.Descriptor instead.
func (*PvpCasualRequestPublicMatchingV2_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescGZIP(), []int{0, 0}
}

type PvpCasualRequestPublicMatchingV2_Types_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Deck           *pvp.PvpBattleDeck     `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	MatchingStance MatchingStance         `protobuf:"varint,2,opt,name=matching_stance,json=matchingStance,proto3,enum=takasho.schema.lettuce_server.player_api.MatchingStance" json:"matching_stance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Request) Reset() {
	*x = PvpCasualRequestPublicMatchingV2_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualRequestPublicMatchingV2_Types_Request) ProtoMessage() {}

func (x *PvpCasualRequestPublicMatchingV2_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualRequestPublicMatchingV2_Types_Request.ProtoReflect.Descriptor instead.
func (*PvpCasualRequestPublicMatchingV2_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Request) GetDeck() *pvp.PvpBattleDeck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Request) GetMatchingStance() MatchingStance {
	if x != nil {
		return x.MatchingStance
	}
	return MatchingStance_MATCHING_STANCE_UNSPECIFIED
}

type PvpCasualRequestPublicMatchingV2_Types_Response struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PollingIntervalMs int64                  `protobuf:"varint,1,opt,name=polling_interval_ms,json=pollingIntervalMs,proto3" json:"polling_interval_ms,omitempty"`
	LastBattle        *pvp.PvpBattleInfo     `protobuf:"bytes,2,opt,name=last_battle,json=lastBattle,proto3" json:"last_battle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Response) Reset() {
	*x = PvpCasualRequestPublicMatchingV2_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpCasualRequestPublicMatchingV2_Types_Response) ProtoMessage() {}

func (x *PvpCasualRequestPublicMatchingV2_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpCasualRequestPublicMatchingV2_Types_Response.ProtoReflect.Descriptor instead.
func (*PvpCasualRequestPublicMatchingV2_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Response) GetPollingIntervalMs() int64 {
	if x != nil {
		return x.PollingIntervalMs
	}
	return 0
}

func (x *PvpCasualRequestPublicMatchingV2_Types_Response) GetLastBattle() *pvp.PvpBattleInfo {
	if x != nil {
		return x.LastBattle
	}
	return nil
}

var File_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDesc = "" +
	"\n" +
	"Ttakasho/schema/lettuce_server/player_api/pvp_casual_request_public_matching_v2.proto\x12(takasho.schema.lettuce_server.player_api\x1a>takasho/schema/lettuce_server/player_api/matching_stance.proto\x1a@takasho/schema/lettuce_server/resource/pvp/pvp_battle_deck.proto\x1a@takasho/schema/lettuce_server/resource/pvp/pvp_battle_info.proto\"\x83\x03\n" +
	" PvpCasualRequestPublicMatchingV2\x1a\xde\x02\n" +
	"\x05Types\x1a\xbb\x01\n" +
	"\aRequest\x12M\n" +
	"\x04deck\x18\x01 \x01(\v29.takasho.schema.lettuce_server.resource.pvp.PvpBattleDeckR\x04deck\x12a\n" +
	"\x0fmatching_stance\x18\x02 \x01(\x0e28.takasho.schema.lettuce_server.player_api.MatchingStanceR\x0ematchingStance\x1a\x96\x01\n" +
	"\bResponse\x12.\n" +
	"\x13polling_interval_ms\x18\x01 \x01(\x03R\x11pollingIntervalMs\x12Z\n" +
	"\vlast_battle\x18\x02 \x01(\v29.takasho.schema.lettuce_server.resource.pvp.PvpBattleInfoR\n" +
	"lastBattleBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_goTypes = []any{
	(*PvpCasualRequestPublicMatchingV2)(nil),                // 0: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2
	(*PvpCasualRequestPublicMatchingV2_Types)(nil),          // 1: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types
	(*PvpCasualRequestPublicMatchingV2_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types.Request
	(*PvpCasualRequestPublicMatchingV2_Types_Response)(nil), // 3: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types.Response
	(*pvp.PvpBattleDeck)(nil),                               // 4: takasho.schema.lettuce_server.resource.pvp.PvpBattleDeck
	(MatchingStance)(0),                                     // 5: takasho.schema.lettuce_server.player_api.MatchingStance
	(*pvp.PvpBattleInfo)(nil),                               // 6: takasho.schema.lettuce_server.resource.pvp.PvpBattleInfo
}
var file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types.Request.deck:type_name -> takasho.schema.lettuce_server.resource.pvp.PvpBattleDeck
	5, // 1: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types.Request.matching_stance:type_name -> takasho.schema.lettuce_server.player_api.MatchingStance
	6, // 2: takasho.schema.lettuce_server.player_api.PvpCasualRequestPublicMatchingV2.Types.Response.last_battle:type_name -> takasho.schema.lettuce_server.resource.pvp.PvpBattleInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_init()
}
func file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_player_api_matching_stance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto = out.File
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_pvp_casual_request_public_matching_v2_proto_depIdxs = nil
}
