// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/pvp_rank_start_battle_v1.proto

package player_api

import (
	pvp "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/pvp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PvpRankStartBattleV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankStartBattleV1) Reset() {
	*x = PvpRankStartBattleV1{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankStartBattleV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankStartBattleV1) ProtoMessage() {}

func (x *PvpRankStartBattleV1) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankStartBattleV1.ProtoReflect.Descriptor instead.
func (*PvpRankStartBattleV1) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescGZIP(), []int{0}
}

type PvpRankStartBattleV1_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankStartBattleV1_Types) Reset() {
	*x = PvpRankStartBattleV1_Types{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankStartBattleV1_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankStartBattleV1_Types) ProtoMessage() {}

func (x *PvpRankStartBattleV1_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankStartBattleV1_Types.ProtoReflect.Descriptor instead.
func (*PvpRankStartBattleV1_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescGZIP(), []int{0, 0}
}

type PvpRankStartBattleV1_Types_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankStartBattleV1_Types_Request) Reset() {
	*x = PvpRankStartBattleV1_Types_Request{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankStartBattleV1_Types_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankStartBattleV1_Types_Request) ProtoMessage() {}

func (x *PvpRankStartBattleV1_Types_Request) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankStartBattleV1_Types_Request.ProtoReflect.Descriptor instead.
func (*PvpRankStartBattleV1_Types_Request) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

type PvpRankStartBattleV1_Types_Response struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	AuthInfo      *pvp.PvpRankBattleServerAuthInfo `protobuf:"bytes,1,opt,name=auth_info,json=authInfo,proto3" json:"auth_info,omitempty"`
	Match         *pvp.PvpRankEstablishedMatch     `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpRankStartBattleV1_Types_Response) Reset() {
	*x = PvpRankStartBattleV1_Types_Response{}
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRankStartBattleV1_Types_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRankStartBattleV1_Types_Response) ProtoMessage() {}

func (x *PvpRankStartBattleV1_Types_Response) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRankStartBattleV1_Types_Response.ProtoReflect.Descriptor instead.
func (*PvpRankStartBattleV1_Types_Response) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PvpRankStartBattleV1_Types_Response) GetAuthInfo() *pvp.PvpRankBattleServerAuthInfo {
	if x != nil {
		return x.AuthInfo
	}
	return nil
}

func (x *PvpRankStartBattleV1_Types_Response) GetMatch() *pvp.PvpRankEstablishedMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

var File_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDesc = "" +
	"\n" +
	"Gtakasho/schema/lettuce_server/player_api/pvp_rank_start_battle_v1.proto\x12(takasho.schema.lettuce_server.player_api\x1aQtakasho/schema/lettuce_server/resource/pvp/pvp_rank_battle_server_auth_info.proto\x1aKtakasho/schema/lettuce_server/resource/pvp/pvp_rank_established_match.proto\"\xf9\x01\n" +
	"\x14PvpRankStartBattleV1\x1a\xe0\x01\n" +
	"\x05Types\x1a\t\n" +
	"\aRequest\x1a\xcb\x01\n" +
	"\bResponse\x12d\n" +
	"\tauth_info\x18\x01 \x01(\v2G.takasho.schema.lettuce_server.resource.pvp.PvpRankBattleServerAuthInfoR\bauthInfo\x12Y\n" +
	"\x05match\x18\x02 \x01(\v2C.takasho.schema.lettuce_server.resource.pvp.PvpRankEstablishedMatchR\x05matchBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var (
	file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDescData
}

var file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_goTypes = []any{
	(*PvpRankStartBattleV1)(nil),                // 0: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1
	(*PvpRankStartBattleV1_Types)(nil),          // 1: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1.Types
	(*PvpRankStartBattleV1_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1.Types.Request
	(*PvpRankStartBattleV1_Types_Response)(nil), // 3: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1.Types.Response
	(*pvp.PvpRankBattleServerAuthInfo)(nil),     // 4: takasho.schema.lettuce_server.resource.pvp.PvpRankBattleServerAuthInfo
	(*pvp.PvpRankEstablishedMatch)(nil),         // 5: takasho.schema.lettuce_server.resource.pvp.PvpRankEstablishedMatch
}
var file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_depIdxs = []int32{
	4, // 0: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1.Types.Response.auth_info:type_name -> takasho.schema.lettuce_server.resource.pvp.PvpRankBattleServerAuthInfo
	5, // 1: takasho.schema.lettuce_server.player_api.PvpRankStartBattleV1.Types.Response.match:type_name -> takasho.schema.lettuce_server.resource.pvp.PvpRankEstablishedMatch
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_init() }
func file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto = out.File
	file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_pvp_rank_start_battle_v1_proto_depIdxs = nil
}
