// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/player_api/solo_battle.proto

package player_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_takasho_schema_lettuce_server_player_api_solo_battle_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_player_api_solo_battle_proto_rawDesc = "" +
	"\n" +
	":takasho/schema/lettuce_server/player_api/solo_battle.proto\x12(takasho.schema.lettuce_server.player_api\x1aQtakasho/schema/lettuce_server/player_api/solo_battle_finish_event_battle_v1.proto\x1aRtakasho/schema/lettuce_server/player_api/solo_battle_finish_random_battle_v1.proto\x1aRtakasho/schema/lettuce_server/player_api/solo_battle_finish_stepup_battle_v1.proto\x1aOtakasho/schema/lettuce_server/player_api/solo_battle_get_event_battles_v1.proto\x1aNtakasho/schema/lettuce_server/player_api/solo_battle_get_event_powers_v1.proto\x1aPtakasho/schema/lettuce_server/player_api/solo_battle_get_random_battles_v1.proto\x1aPtakasho/schema/lettuce_server/player_api/solo_battle_get_stepup_battles_v1.proto\x1aNtakasho/schema/lettuce_server/player_api/solo_battle_heal_event_power_v1.proto\x1aPtakasho/schema/lettuce_server/player_api/solo_battle_start_event_battle_v1.proto\x1aQtakasho/schema/lettuce_server/player_api/solo_battle_start_random_battle_v1.proto\x1aQtakasho/schema/lettuce_server/player_api/solo_battle_start_stepup_battle_v1.proto2\xfe\x10\n" +
	"\n" +
	"SoloBattle\x12\xc1\x01\n" +
	"\x12GetStepupBattlesV1\x12T.takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Request\x1aU.takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Response\x12\xc4\x01\n" +
	"\x13StartStepupBattleV1\x12U.takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Request\x1aV.takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Response\x12\xc7\x01\n" +
	"\x14FinishStepupBattleV1\x12V.takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Request\x1aW.takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Response\x12\xbe\x01\n" +
	"\x11GetEventBattlesV1\x12S.takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Request\x1aT.takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Response\x12\xc1\x01\n" +
	"\x12StartEventBattleV1\x12T.takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Request\x1aU.takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Response\x12\xc4\x01\n" +
	"\x13FinishEventBattleV1\x12U.takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Request\x1aV.takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Response\x12\xbb\x01\n" +
	"\x10HealEventPowerV1\x12R.takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Request\x1aS.takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Response\x12\xbb\x01\n" +
	"\x10GetEventPowersV1\x12R.takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Request\x1aS.takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Response\x12\xc1\x01\n" +
	"\x12GetRandomBattlesV1\x12T.takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Request\x1aU.takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Response\x12\xc4\x01\n" +
	"\x13StartRandomBattleV1\x12U.takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Request\x1aV.takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Response\x12\xc7\x01\n" +
	"\x14FinishRandomBattleV1\x12V.takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.Request\x1aW.takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.ResponseBoZmgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/player_api;player_apib\x06proto3"

var file_takasho_schema_lettuce_server_player_api_solo_battle_proto_goTypes = []any{
	(*SoloBattleGetStepupBattlesV1_Types_Request)(nil),    // 0: takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Request
	(*SoloBattleStartStepupBattleV1_Types_Request)(nil),   // 1: takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Request
	(*SoloBattleFinishStepupBattleV1_Types_Request)(nil),  // 2: takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Request
	(*SoloBattleGetEventBattlesV1_Types_Request)(nil),     // 3: takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Request
	(*SoloBattleStartEventBattleV1_Types_Request)(nil),    // 4: takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Request
	(*SoloBattleFinishEventBattleV1_Types_Request)(nil),   // 5: takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Request
	(*SoloBattleHealEventPowerV1_Types_Request)(nil),      // 6: takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Request
	(*SoloBattleGetEventPowersV1_Types_Request)(nil),      // 7: takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Request
	(*SoloBattleGetRandomBattlesV1_Types_Request)(nil),    // 8: takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Request
	(*SoloBattleStartRandomBattleV1_Types_Request)(nil),   // 9: takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Request
	(*SoloBattleFinishRandomBattleV1_Types_Request)(nil),  // 10: takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.Request
	(*SoloBattleGetStepupBattlesV1_Types_Response)(nil),   // 11: takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Response
	(*SoloBattleStartStepupBattleV1_Types_Response)(nil),  // 12: takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Response
	(*SoloBattleFinishStepupBattleV1_Types_Response)(nil), // 13: takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Response
	(*SoloBattleGetEventBattlesV1_Types_Response)(nil),    // 14: takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Response
	(*SoloBattleStartEventBattleV1_Types_Response)(nil),   // 15: takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Response
	(*SoloBattleFinishEventBattleV1_Types_Response)(nil),  // 16: takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Response
	(*SoloBattleHealEventPowerV1_Types_Response)(nil),     // 17: takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Response
	(*SoloBattleGetEventPowersV1_Types_Response)(nil),     // 18: takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Response
	(*SoloBattleGetRandomBattlesV1_Types_Response)(nil),   // 19: takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Response
	(*SoloBattleStartRandomBattleV1_Types_Response)(nil),  // 20: takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Response
	(*SoloBattleFinishRandomBattleV1_Types_Response)(nil), // 21: takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.Response
}
var file_takasho_schema_lettuce_server_player_api_solo_battle_proto_depIdxs = []int32{
	0,  // 0: takasho.schema.lettuce_server.player_api.SoloBattle.GetStepupBattlesV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Request
	1,  // 1: takasho.schema.lettuce_server.player_api.SoloBattle.StartStepupBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Request
	2,  // 2: takasho.schema.lettuce_server.player_api.SoloBattle.FinishStepupBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Request
	3,  // 3: takasho.schema.lettuce_server.player_api.SoloBattle.GetEventBattlesV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Request
	4,  // 4: takasho.schema.lettuce_server.player_api.SoloBattle.StartEventBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Request
	5,  // 5: takasho.schema.lettuce_server.player_api.SoloBattle.FinishEventBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Request
	6,  // 6: takasho.schema.lettuce_server.player_api.SoloBattle.HealEventPowerV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Request
	7,  // 7: takasho.schema.lettuce_server.player_api.SoloBattle.GetEventPowersV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Request
	8,  // 8: takasho.schema.lettuce_server.player_api.SoloBattle.GetRandomBattlesV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Request
	9,  // 9: takasho.schema.lettuce_server.player_api.SoloBattle.StartRandomBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Request
	10, // 10: takasho.schema.lettuce_server.player_api.SoloBattle.FinishRandomBattleV1:input_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.Request
	11, // 11: takasho.schema.lettuce_server.player_api.SoloBattle.GetStepupBattlesV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetStepupBattlesV1.Types.Response
	12, // 12: takasho.schema.lettuce_server.player_api.SoloBattle.StartStepupBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartStepupBattleV1.Types.Response
	13, // 13: takasho.schema.lettuce_server.player_api.SoloBattle.FinishStepupBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishStepupBattleV1.Types.Response
	14, // 14: takasho.schema.lettuce_server.player_api.SoloBattle.GetEventBattlesV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetEventBattlesV1.Types.Response
	15, // 15: takasho.schema.lettuce_server.player_api.SoloBattle.StartEventBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartEventBattleV1.Types.Response
	16, // 16: takasho.schema.lettuce_server.player_api.SoloBattle.FinishEventBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishEventBattleV1.Types.Response
	17, // 17: takasho.schema.lettuce_server.player_api.SoloBattle.HealEventPowerV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleHealEventPowerV1.Types.Response
	18, // 18: takasho.schema.lettuce_server.player_api.SoloBattle.GetEventPowersV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetEventPowersV1.Types.Response
	19, // 19: takasho.schema.lettuce_server.player_api.SoloBattle.GetRandomBattlesV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleGetRandomBattlesV1.Types.Response
	20, // 20: takasho.schema.lettuce_server.player_api.SoloBattle.StartRandomBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleStartRandomBattleV1.Types.Response
	21, // 21: takasho.schema.lettuce_server.player_api.SoloBattle.FinishRandomBattleV1:output_type -> takasho.schema.lettuce_server.player_api.SoloBattleFinishRandomBattleV1.Types.Response
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_player_api_solo_battle_proto_init() }
func file_takasho_schema_lettuce_server_player_api_solo_battle_proto_init() {
	if File_takasho_schema_lettuce_server_player_api_solo_battle_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_player_api_solo_battle_finish_event_battle_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_finish_random_battle_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_finish_stepup_battle_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_get_event_battles_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_get_event_powers_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_get_random_battles_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_get_stepup_battles_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_heal_event_power_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_start_event_battle_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_start_random_battle_v1_proto_init()
	file_takasho_schema_lettuce_server_player_api_solo_battle_start_stepup_battle_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_player_api_solo_battle_proto_rawDesc), len(file_takasho_schema_lettuce_server_player_api_solo_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_takasho_schema_lettuce_server_player_api_solo_battle_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_player_api_solo_battle_proto_depIdxs,
	}.Build()
	File_takasho_schema_lettuce_server_player_api_solo_battle_proto = out.File
	file_takasho_schema_lettuce_server_player_api_solo_battle_proto_goTypes = nil
	file_takasho_schema_lettuce_server_player_api_solo_battle_proto_depIdxs = nil
}
