// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: takasho/schema/lettuce_server/player_api/tutorial.proto

package player_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tutorial_CompleteV1_FullMethodName            = "/takasho.schema.lettuce_server.player_api.Tutorial/CompleteV1"
	Tutorial_ChoiceExchangeRouteV1_FullMethodName = "/takasho.schema.lettuce_server.player_api.Tutorial/ChoiceExchangeRouteV1"
	Tutorial_PackPurchaseV1_FullMethodName        = "/takasho.schema.lettuce_server.player_api.Tutorial/PackPurchaseV1"
	Tutorial_GetFeedTimelineV1_FullMethodName     = "/takasho.schema.lettuce_server.player_api.Tutorial/GetFeedTimelineV1"
	Tutorial_ChallengeFeedV1_FullMethodName       = "/takasho.schema.lettuce_server.player_api.Tutorial/ChallengeFeedV1"
)

// TutorialClient is the client API for Tutorial service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorialClient interface {
	CompleteV1(ctx context.Context, in *TutorialCompleteV1_Types_Request, opts ...grpc.CallOption) (*TutorialCompleteV1_Types_Response, error)
	ChoiceExchangeRouteV1(ctx context.Context, in *TutorialChoiceExchangeRouteV1_Types_Request, opts ...grpc.CallOption) (*TutorialChoiceExchangeRouteV1_Types_Response, error)
	PackPurchaseV1(ctx context.Context, in *TutorialPackPurchaseV1_Types_Request, opts ...grpc.CallOption) (*TutorialPackPurchaseV1_Types_Response, error)
	GetFeedTimelineV1(ctx context.Context, in *TutorialGetFeedTimelineV1_Types_Request, opts ...grpc.CallOption) (*TutorialGetFeedTimelineV1_Types_Response, error)
	ChallengeFeedV1(ctx context.Context, in *TutorialChallengeFeedV1_Types_Request, opts ...grpc.CallOption) (*TutorialChallengeFeedV1_Types_Response, error)
}

type tutorialClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorialClient(cc grpc.ClientConnInterface) TutorialClient {
	return &tutorialClient{cc}
}

func (c *tutorialClient) CompleteV1(ctx context.Context, in *TutorialCompleteV1_Types_Request, opts ...grpc.CallOption) (*TutorialCompleteV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TutorialCompleteV1_Types_Response)
	err := c.cc.Invoke(ctx, Tutorial_CompleteV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialClient) ChoiceExchangeRouteV1(ctx context.Context, in *TutorialChoiceExchangeRouteV1_Types_Request, opts ...grpc.CallOption) (*TutorialChoiceExchangeRouteV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TutorialChoiceExchangeRouteV1_Types_Response)
	err := c.cc.Invoke(ctx, Tutorial_ChoiceExchangeRouteV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialClient) PackPurchaseV1(ctx context.Context, in *TutorialPackPurchaseV1_Types_Request, opts ...grpc.CallOption) (*TutorialPackPurchaseV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TutorialPackPurchaseV1_Types_Response)
	err := c.cc.Invoke(ctx, Tutorial_PackPurchaseV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialClient) GetFeedTimelineV1(ctx context.Context, in *TutorialGetFeedTimelineV1_Types_Request, opts ...grpc.CallOption) (*TutorialGetFeedTimelineV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TutorialGetFeedTimelineV1_Types_Response)
	err := c.cc.Invoke(ctx, Tutorial_GetFeedTimelineV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialClient) ChallengeFeedV1(ctx context.Context, in *TutorialChallengeFeedV1_Types_Request, opts ...grpc.CallOption) (*TutorialChallengeFeedV1_Types_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TutorialChallengeFeedV1_Types_Response)
	err := c.cc.Invoke(ctx, Tutorial_ChallengeFeedV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorialServer is the server API for Tutorial service.
// All implementations must embed UnimplementedTutorialServer
// for forward compatibility.
type TutorialServer interface {
	CompleteV1(context.Context, *TutorialCompleteV1_Types_Request) (*TutorialCompleteV1_Types_Response, error)
	ChoiceExchangeRouteV1(context.Context, *TutorialChoiceExchangeRouteV1_Types_Request) (*TutorialChoiceExchangeRouteV1_Types_Response, error)
	PackPurchaseV1(context.Context, *TutorialPackPurchaseV1_Types_Request) (*TutorialPackPurchaseV1_Types_Response, error)
	GetFeedTimelineV1(context.Context, *TutorialGetFeedTimelineV1_Types_Request) (*TutorialGetFeedTimelineV1_Types_Response, error)
	ChallengeFeedV1(context.Context, *TutorialChallengeFeedV1_Types_Request) (*TutorialChallengeFeedV1_Types_Response, error)
	mustEmbedUnimplementedTutorialServer()
}

// UnimplementedTutorialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTutorialServer struct{}

func (UnimplementedTutorialServer) CompleteV1(context.Context, *TutorialCompleteV1_Types_Request) (*TutorialCompleteV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteV1 not implemented")
}
func (UnimplementedTutorialServer) ChoiceExchangeRouteV1(context.Context, *TutorialChoiceExchangeRouteV1_Types_Request) (*TutorialChoiceExchangeRouteV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ChoiceExchangeRouteV1 not implemented")
}
func (UnimplementedTutorialServer) PackPurchaseV1(context.Context, *TutorialPackPurchaseV1_Types_Request) (*TutorialPackPurchaseV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PackPurchaseV1 not implemented")
}
func (UnimplementedTutorialServer) GetFeedTimelineV1(context.Context, *TutorialGetFeedTimelineV1_Types_Request) (*TutorialGetFeedTimelineV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedTimelineV1 not implemented")
}
func (UnimplementedTutorialServer) ChallengeFeedV1(context.Context, *TutorialChallengeFeedV1_Types_Request) (*TutorialChallengeFeedV1_Types_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ChallengeFeedV1 not implemented")
}
func (UnimplementedTutorialServer) mustEmbedUnimplementedTutorialServer() {}
func (UnimplementedTutorialServer) testEmbeddedByValue()                  {}

// UnsafeTutorialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorialServer will
// result in compilation errors.
type UnsafeTutorialServer interface {
	mustEmbedUnimplementedTutorialServer()
}

func RegisterTutorialServer(s grpc.ServiceRegistrar, srv TutorialServer) {
	// If the following call panics, it indicates UnimplementedTutorialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tutorial_ServiceDesc, srv)
}

func _Tutorial_CompleteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TutorialCompleteV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServer).CompleteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tutorial_CompleteV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServer).CompleteV1(ctx, req.(*TutorialCompleteV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tutorial_ChoiceExchangeRouteV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TutorialChoiceExchangeRouteV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServer).ChoiceExchangeRouteV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tutorial_ChoiceExchangeRouteV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServer).ChoiceExchangeRouteV1(ctx, req.(*TutorialChoiceExchangeRouteV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tutorial_PackPurchaseV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TutorialPackPurchaseV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServer).PackPurchaseV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tutorial_PackPurchaseV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServer).PackPurchaseV1(ctx, req.(*TutorialPackPurchaseV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tutorial_GetFeedTimelineV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TutorialGetFeedTimelineV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServer).GetFeedTimelineV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tutorial_GetFeedTimelineV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServer).GetFeedTimelineV1(ctx, req.(*TutorialGetFeedTimelineV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tutorial_ChallengeFeedV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TutorialChallengeFeedV1_Types_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServer).ChallengeFeedV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tutorial_ChallengeFeedV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServer).ChallengeFeedV1(ctx, req.(*TutorialChallengeFeedV1_Types_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Tutorial_ServiceDesc is the grpc.ServiceDesc for Tutorial service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tutorial_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "takasho.schema.lettuce_server.player_api.Tutorial",
	HandlerType: (*TutorialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteV1",
			Handler:    _Tutorial_CompleteV1_Handler,
		},
		{
			MethodName: "ChoiceExchangeRouteV1",
			Handler:    _Tutorial_ChoiceExchangeRouteV1_Handler,
		},
		{
			MethodName: "PackPurchaseV1",
			Handler:    _Tutorial_PackPurchaseV1_Handler,
		},
		{
			MethodName: "GetFeedTimelineV1",
			Handler:    _Tutorial_GetFeedTimelineV1_Handler,
		},
		{
			MethodName: "ChallengeFeedV1",
			Handler:    _Tutorial_ChallengeFeedV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "takasho/schema/lettuce_server/player_api/tutorial.proto",
}
