// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/item_shop/purchase_summary.proto

package item_shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShopId         string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ProductId      string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseAmount int64                  `protobuf:"varint,3,opt,name=purchase_amount,json=purchaseAmount,proto3" json:"purchase_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PurchaseSummary) Reset() {
	*x = PurchaseSummary{}
	mi := &file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseSummary) ProtoMessage() {}

func (x *PurchaseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseSummary.ProtoReflect.Descriptor instead.
func (*PurchaseSummary) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseSummary) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *PurchaseSummary) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseSummary) GetPurchaseAmount() int64 {
	if x != nil {
		return x.PurchaseAmount
	}
	return 0
}

var File_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDesc = "" +
	"\n" +
	"Gtakasho/schema/lettuce_server/resource/item_shop/purchase_summary.proto\x120takasho.schema.lettuce_server.resource.item_shop\"r\n" +
	"\x0fPurchaseSummary\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12'\n" +
	"\x0fpurchase_amount\x18\x03 \x01(\x03R\x0epurchaseAmountBvZtgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/item_shop;item_shopb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_goTypes = []any{
	(*PurchaseSummary)(nil), // 0: takasho.schema.lettuce_server.resource.item_shop.PurchaseSummary
}
var file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_init() }
func file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_init() {
	if File_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto = out.File
	file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_item_shop_purchase_summary_proto_depIdxs = nil
}
