// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/pvp/emblem_step.proto

package pvp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmblemStep int32

const (
	EmblemStep_EMBLEM_STEP_NO_EMBLEM EmblemStep = 0
	EmblemStep_EMBLEM_STEP_WHITE     EmblemStep = 1
	EmblemStep_EMBLEM_STEP_BRONZE    EmblemStep = 2
	EmblemStep_EMBLEM_STEP_SILVER    EmblemStep = 3
	EmblemStep_EMBLEM_STEP_GOLD      EmblemStep = 4
)

// Enum value maps for EmblemStep.
var (
	EmblemStep_name = map[int32]string{
		0: "EMBLEM_STEP_NO_EMBLEM",
		1: "EMBLEM_STEP_WHITE",
		2: "EMBLEM_STEP_BRONZE",
		3: "EMBLEM_STEP_SILVER",
		4: "EMBLEM_STEP_GOLD",
	}
	EmblemStep_value = map[string]int32{
		"EMBLEM_STEP_NO_EMBLEM": 0,
		"EMBLEM_STEP_WHITE":     1,
		"EMBLEM_STEP_BRONZE":    2,
		"EMBLEM_STEP_SILVER":    3,
		"EMBLEM_STEP_GOLD":      4,
	}
)

func (x EmblemStep) Enum() *EmblemStep {
	p := new(EmblemStep)
	*p = x
	return p
}

func (x EmblemStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmblemStep) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_enumTypes[0].Descriptor()
}

func (EmblemStep) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_enumTypes[0]
}

func (x EmblemStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmblemStep.Descriptor instead.
func (EmblemStep) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescGZIP(), []int{0}
}

var File_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDesc = "" +
	"\n" +
	"<takasho/schema/lettuce_server/resource/pvp/emblem_step.proto\x12*takasho.schema.lettuce_server.resource.pvp*\x84\x01\n" +
	"\n" +
	"EmblemStep\x12\x19\n" +
	"\x15EMBLEM_STEP_NO_EMBLEM\x10\x00\x12\x15\n" +
	"\x11EMBLEM_STEP_WHITE\x10\x01\x12\x16\n" +
	"\x12EMBLEM_STEP_BRONZE\x10\x02\x12\x16\n" +
	"\x12EMBLEM_STEP_SILVER\x10\x03\x12\x14\n" +
	"\x10EMBLEM_STEP_GOLD\x10\x04BjZhgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/pvp;pvpb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_goTypes = []any{
	(EmblemStep)(0), // 0: takasho.schema.lettuce_server.resource.pvp.EmblemStep
}
var file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_init() }
func file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_init() {
	if File_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_depIdxs,
		EnumInfos:         file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_enumTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto = out.File
	file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_pvp_emblem_step_proto_depIdxs = nil
}
