// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/pvp/sub_rank_type.proto

package pvp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubRankType int32

const (
	SubRankType_SUB_RANK_TYPE_UNSPECIFIED SubRankType = 0
	SubRankType_SUB_RANK_TYPE_FIRST       SubRankType = 1
	SubRankType_SUB_RANK_TYPE_SECOND      SubRankType = 2
	SubRankType_SUB_RANK_TYPE_THIRD       SubRankType = 3
	SubRankType_SUB_RANK_TYPE_FOURTH      SubRankType = 4
)

// Enum value maps for SubRankType.
var (
	SubRankType_name = map[int32]string{
		0: "SUB_RANK_TYPE_UNSPECIFIED",
		1: "SUB_RANK_TYPE_FIRST",
		2: "SUB_RANK_TYPE_SECOND",
		3: "SUB_RANK_TYPE_THIRD",
		4: "SUB_RANK_TYPE_FOURTH",
	}
	SubRankType_value = map[string]int32{
		"SUB_RANK_TYPE_UNSPECIFIED": 0,
		"SUB_RANK_TYPE_FIRST":       1,
		"SUB_RANK_TYPE_SECOND":      2,
		"SUB_RANK_TYPE_THIRD":       3,
		"SUB_RANK_TYPE_FOURTH":      4,
	}
)

func (x SubRankType) Enum() *SubRankType {
	p := new(SubRankType)
	*p = x
	return p
}

func (x SubRankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubRankType) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_enumTypes[0].Descriptor()
}

func (SubRankType) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_enumTypes[0]
}

func (x SubRankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubRankType.Descriptor instead.
func (SubRankType) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescGZIP(), []int{0}
}

var File_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDesc = "" +
	"\n" +
	">takasho/schema/lettuce_server/resource/pvp/sub_rank_type.proto\x12*takasho.schema.lettuce_server.resource.pvp*\x92\x01\n" +
	"\vSubRankType\x12\x1d\n" +
	"\x19SUB_RANK_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SUB_RANK_TYPE_FIRST\x10\x01\x12\x18\n" +
	"\x14SUB_RANK_TYPE_SECOND\x10\x02\x12\x17\n" +
	"\x13SUB_RANK_TYPE_THIRD\x10\x03\x12\x18\n" +
	"\x14SUB_RANK_TYPE_FOURTH\x10\x04BjZhgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/pvp;pvpb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_goTypes = []any{
	(SubRankType)(0), // 0: takasho.schema.lettuce_server.resource.pvp.SubRankType
}
var file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_init() }
func file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_init() {
	if File_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_depIdxs,
		EnumInfos:         file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_enumTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto = out.File
	file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_pvp_sub_rank_type_proto_depIdxs = nil
}
