// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/card_skin/card_skin_type.proto

package card_skin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardSkinType int32

const (
	CardSkinType_CARD_SKIN_TYPE_UNSPECIFIED   CardSkinType = 0
	CardSkinType_CARD_SKIN_TYPE_DECORATION    CardSkinType = 1
	CardSkinType_CARD_SKIN_TYPE_BATTLE_EFFECT CardSkinType = 2
)

// Enum value maps for CardSkinType.
var (
	CardSkinType_name = map[int32]string{
		0: "CARD_SKIN_TYPE_UNSPECIFIED",
		1: "CARD_SKIN_TYPE_DECORATION",
		2: "CARD_SKIN_TYPE_BATTLE_EFFECT",
	}
	CardSkinType_value = map[string]int32{
		"CARD_SKIN_TYPE_UNSPECIFIED":   0,
		"CARD_SKIN_TYPE_DECORATION":    1,
		"CARD_SKIN_TYPE_BATTLE_EFFECT": 2,
	}
)

func (x CardSkinType) Enum() *CardSkinType {
	p := new(CardSkinType)
	*p = x
	return p
}

func (x CardSkinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardSkinType) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_enumTypes[0].Descriptor()
}

func (CardSkinType) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_enumTypes[0]
}

func (x CardSkinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardSkinType.Descriptor instead.
func (CardSkinType) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescGZIP(), []int{0}
}

var File_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDesc = "" +
	"\n" +
	"Etakasho/schema/lettuce_server/resource/card_skin/card_skin_type.proto\x120takasho.schema.lettuce_server.resource.card_skin*o\n" +
	"\fCardSkinType\x12\x1e\n" +
	"\x1aCARD_SKIN_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CARD_SKIN_TYPE_DECORATION\x10\x01\x12 \n" +
	"\x1cCARD_SKIN_TYPE_BATTLE_EFFECT\x10\x02BvZtgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card_skin;card_skinb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_goTypes = []any{
	(CardSkinType)(0), // 0: takasho.schema.lettuce_server.resource.card_skin.CardSkinType
}
var file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_init() }
func file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_init() {
	if File_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_depIdxs,
		EnumInfos:         file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_enumTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto = out.File
	file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_card_skin_card_skin_type_proto_depIdxs = nil
}
