// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/card/card_stock.proto

package card

import (
	language "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/language"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardStock struct {
	state                          protoimpl.MessageState     `protogen:"open.v1"`
	CardId                         string                     `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardAmount                     uint64                     `protobuf:"varint,2,opt,name=card_amount,json=cardAmount,proto3" json:"card_amount,omitempty"`
	LanguageTags                   []*CardStock_Types_LangTag `protobuf:"bytes,3,rep,name=language_tags,json=languageTags,proto3" json:"language_tags,omitempty"`
	ExpansionIds                   []string                   `protobuf:"bytes,4,rep,name=expansion_ids,json=expansionIds,proto3" json:"expansion_ids,omitempty"`
	FirstReceivedAt                *timestamppb.Timestamp     `protobuf:"bytes,98,opt,name=first_received_at,json=firstReceivedAt,proto3" json:"first_received_at,omitempty"`
	LastReceivedAt                 *timestamppb.Timestamp     `protobuf:"bytes,99,opt,name=last_received_at,json=lastReceivedAt,proto3" json:"last_received_at,omitempty"`
	LastCardSkinReceivedAt         *timestamppb.Timestamp     `protobuf:"bytes,100,opt,name=last_card_skin_received_at,json=lastCardSkinReceivedAt,proto3" json:"last_card_skin_received_at,omitempty"`
	LastCardSkinAndFrameReceivedAt *timestamppb.Timestamp     `protobuf:"bytes,101,opt,name=last_card_skin_and_frame_received_at,json=lastCardSkinAndFrameReceivedAt,proto3" json:"last_card_skin_and_frame_received_at,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *CardStock) Reset() {
	*x = CardStock{}
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStock) ProtoMessage() {}

func (x *CardStock) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStock.ProtoReflect.Descriptor instead.
func (*CardStock) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescGZIP(), []int{0}
}

func (x *CardStock) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardStock) GetCardAmount() uint64 {
	if x != nil {
		return x.CardAmount
	}
	return 0
}

func (x *CardStock) GetLanguageTags() []*CardStock_Types_LangTag {
	if x != nil {
		return x.LanguageTags
	}
	return nil
}

func (x *CardStock) GetExpansionIds() []string {
	if x != nil {
		return x.ExpansionIds
	}
	return nil
}

func (x *CardStock) GetFirstReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstReceivedAt
	}
	return nil
}

func (x *CardStock) GetLastReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReceivedAt
	}
	return nil
}

func (x *CardStock) GetLastCardSkinReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCardSkinReceivedAt
	}
	return nil
}

func (x *CardStock) GetLastCardSkinAndFrameReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCardSkinAndFrameReceivedAt
	}
	return nil
}

type CardStock_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStock_Types) Reset() {
	*x = CardStock_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStock_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStock_Types) ProtoMessage() {}

func (x *CardStock_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStock_Types.ProtoReflect.Descriptor instead.
func (*CardStock_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescGZIP(), []int{0, 0}
}

type CardStock_Types_LangTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          language.Language      `protobuf:"varint,1,opt,name=lang,proto3,enum=takasho.schema.lettuce_server.resource.language.Language" json:"lang,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStock_Types_LangTag) Reset() {
	*x = CardStock_Types_LangTag{}
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStock_Types_LangTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStock_Types_LangTag) ProtoMessage() {}

func (x *CardStock_Types_LangTag) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStock_Types_LangTag.ProtoReflect.Descriptor instead.
func (*CardStock_Types_LangTag) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CardStock_Types_LangTag) GetLang() language.Language {
	if x != nil {
		return x.Lang
	}
	return language.Language(0)
}

func (x *CardStock_Types_LangTag) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_takasho_schema_lettuce_server_resource_card_card_stock_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDesc = "" +
	"\n" +
	"<takasho/schema/lettuce_server/resource/card/card_stock.proto\x12+takasho.schema.lettuce_server.resource.card\x1a\x1fgoogle/protobuf/timestamp.proto\x1a>takasho/schema/lettuce_server/resource/language/language.proto\"\xa0\x05\n" +
	"\tCardStock\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1f\n" +
	"\vcard_amount\x18\x02 \x01(\x04R\n" +
	"cardAmount\x12i\n" +
	"\rlanguage_tags\x18\x03 \x03(\v2D.takasho.schema.lettuce_server.resource.card.CardStock.Types.LangTagR\flanguageTags\x12#\n" +
	"\rexpansion_ids\x18\x04 \x03(\tR\fexpansionIds\x12F\n" +
	"\x11first_received_at\x18b \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstReceivedAt\x12D\n" +
	"\x10last_received_at\x18c \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReceivedAt\x12V\n" +
	"\x1alast_card_skin_received_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\x16lastCardSkinReceivedAt\x12h\n" +
	"$last_card_skin_and_frame_received_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\x1elastCardSkinAndFrameReceivedAt\x1ay\n" +
	"\x05Types\x1ap\n" +
	"\aLangTag\x12M\n" +
	"\x04lang\x18\x01 \x01(\x0e29.takasho.schema.lettuce_server.resource.language.LanguageR\x04lang\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amountBlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card;cardb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_takasho_schema_lettuce_server_resource_card_card_stock_proto_goTypes = []any{
	(*CardStock)(nil),               // 0: takasho.schema.lettuce_server.resource.card.CardStock
	(*CardStock_Types)(nil),         // 1: takasho.schema.lettuce_server.resource.card.CardStock.Types
	(*CardStock_Types_LangTag)(nil), // 2: takasho.schema.lettuce_server.resource.card.CardStock.Types.LangTag
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
	(language.Language)(0),          // 4: takasho.schema.lettuce_server.resource.language.Language
}
var file_takasho_schema_lettuce_server_resource_card_card_stock_proto_depIdxs = []int32{
	2, // 0: takasho.schema.lettuce_server.resource.card.CardStock.language_tags:type_name -> takasho.schema.lettuce_server.resource.card.CardStock.Types.LangTag
	3, // 1: takasho.schema.lettuce_server.resource.card.CardStock.first_received_at:type_name -> google.protobuf.Timestamp
	3, // 2: takasho.schema.lettuce_server.resource.card.CardStock.last_received_at:type_name -> google.protobuf.Timestamp
	3, // 3: takasho.schema.lettuce_server.resource.card.CardStock.last_card_skin_received_at:type_name -> google.protobuf.Timestamp
	3, // 4: takasho.schema.lettuce_server.resource.card.CardStock.last_card_skin_and_frame_received_at:type_name -> google.protobuf.Timestamp
	4, // 5: takasho.schema.lettuce_server.resource.card.CardStock.Types.LangTag.lang:type_name -> takasho.schema.lettuce_server.resource.language.Language
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_card_card_stock_proto_init() }
func file_takasho_schema_lettuce_server_resource_card_card_stock_proto_init() {
	if File_takasho_schema_lettuce_server_resource_card_card_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_card_card_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_card_card_stock_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_card_card_stock_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_card_card_stock_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_card_card_stock_proto = out.File
	file_takasho_schema_lettuce_server_resource_card_card_stock_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_card_card_stock_proto_depIdxs = nil
}
