// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/trade/trade_session_status.proto

package trade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeSessionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	State         TradeSessionState      `protobuf:"varint,2,opt,name=state,proto3,enum=takasho.schema.lettuce_server.resource.trade.TradeSessionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSessionStatus) Reset() {
	*x = TradeSessionStatus{}
	mi := &file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSessionStatus) ProtoMessage() {}

func (x *TradeSessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSessionStatus.ProtoReflect.Descriptor instead.
func (*TradeSessionStatus) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescGZIP(), []int{0}
}

func (x *TradeSessionStatus) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *TradeSessionStatus) GetState() TradeSessionState {
	if x != nil {
		return x.State
	}
	return TradeSessionState_TRADE_SESSION_STATE_UNSPECIFIED
}

var File_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDesc = "" +
	"\n" +
	"Gtakasho/schema/lettuce_server/resource/trade/trade_session_status.proto\x12,takasho.schema.lettuce_server.resource.trade\x1a\x1fgoogle/protobuf/timestamp.proto\x1aFtakasho/schema/lettuce_server/resource/trade/trade_session_state.proto\"\xa4\x01\n" +
	"\x12TradeSessionStatus\x127\n" +
	"\texpire_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12U\n" +
	"\x05state\x18\x02 \x01(\x0e2?.takasho.schema.lettuce_server.resource.trade.TradeSessionStateR\x05stateBnZlgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/trade;tradeb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_goTypes = []any{
	(*TradeSessionStatus)(nil),    // 0: takasho.schema.lettuce_server.resource.trade.TradeSessionStatus
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(TradeSessionState)(0),        // 2: takasho.schema.lettuce_server.resource.trade.TradeSessionState
}
var file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_depIdxs = []int32{
	1, // 0: takasho.schema.lettuce_server.resource.trade.TradeSessionStatus.expire_at:type_name -> google.protobuf.Timestamp
	2, // 1: takasho.schema.lettuce_server.resource.trade.TradeSessionStatus.state:type_name -> takasho.schema.lettuce_server.resource.trade.TradeSessionState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_init() }
func file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_init() {
	if File_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_resource_trade_trade_session_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto = out.File
	file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_trade_trade_session_status_proto_depIdxs = nil
}
