// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/player_profile/profile_spine.proto

package player_profile

import (
	collection "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/collection"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileSpine struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	PlayerId       string                       `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname       string                       `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IconId         string                       `protobuf:"bytes,3,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`
	PlayerLevel    uint64                       `protobuf:"varint,4,opt,name=player_level,json=playerLevel,proto3" json:"player_level,omitempty"`
	LastLoggedInAt *timestamppb.Timestamp       `protobuf:"bytes,5,opt,name=last_logged_in_at,json=lastLoggedInAt,proto3" json:"last_logged_in_at,omitempty"`
	EmblemIds      []string                     `protobuf:"bytes,6,rep,name=emblem_ids,json=emblemIds,proto3" json:"emblem_ids,omitempty"`
	Collection     *collection.MyBestCollection `protobuf:"bytes,7,opt,name=collection,proto3" json:"collection,omitempty"`
	FriendId       string                       `protobuf:"bytes,8,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	AvailableType  AvailableType                `protobuf:"varint,9,opt,name=available_type,json=availableType,proto3,enum=takasho.schema.lettuce_server.resource.player_profile.AvailableType" json:"available_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileSpine) Reset() {
	*x = ProfileSpine{}
	mi := &file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSpine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSpine) ProtoMessage() {}

func (x *ProfileSpine) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSpine.ProtoReflect.Descriptor instead.
func (*ProfileSpine) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileSpine) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ProfileSpine) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileSpine) GetIconId() string {
	if x != nil {
		return x.IconId
	}
	return ""
}

func (x *ProfileSpine) GetPlayerLevel() uint64 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

func (x *ProfileSpine) GetLastLoggedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoggedInAt
	}
	return nil
}

func (x *ProfileSpine) GetEmblemIds() []string {
	if x != nil {
		return x.EmblemIds
	}
	return nil
}

func (x *ProfileSpine) GetCollection() *collection.MyBestCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *ProfileSpine) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *ProfileSpine) GetAvailableType() AvailableType {
	if x != nil {
		return x.AvailableType
	}
	return AvailableType_AVAILABLE_TYPE_UNSPECIFIED
}

var File_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDesc = "" +
	"\n" +
	"Itakasho/schema/lettuce_server/resource/player_profile/profile_spine.proto\x125takasho.schema.lettuce_server.resource.player_profile\x1a\x1fgoogle/protobuf/timestamp.proto\x1aJtakasho/schema/lettuce_server/resource/collection/my_best_collection.proto\x1aJtakasho/schema/lettuce_server/resource/player_profile/available_type.proto\"\xd8\x03\n" +
	"\fProfileSpine\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x17\n" +
	"\aicon_id\x18\x03 \x01(\tR\x06iconId\x12!\n" +
	"\fplayer_level\x18\x04 \x01(\x04R\vplayerLevel\x12E\n" +
	"\x11last_logged_in_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastLoggedInAt\x12\x1d\n" +
	"\n" +
	"emblem_ids\x18\x06 \x03(\tR\temblemIds\x12c\n" +
	"\n" +
	"collection\x18\a \x01(\v2C.takasho.schema.lettuce_server.resource.collection.MyBestCollectionR\n" +
	"collection\x12\x1b\n" +
	"\tfriend_id\x18\b \x01(\tR\bfriendId\x12k\n" +
	"\x0eavailable_type\x18\t \x01(\x0e2D.takasho.schema.lettuce_server.resource.player_profile.AvailableTypeR\ravailableTypeB\x80\x01Z~github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/player_profile;player_profileb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_goTypes = []any{
	(*ProfileSpine)(nil),                // 0: takasho.schema.lettuce_server.resource.player_profile.ProfileSpine
	(*timestamppb.Timestamp)(nil),       // 1: google.protobuf.Timestamp
	(*collection.MyBestCollection)(nil), // 2: takasho.schema.lettuce_server.resource.collection.MyBestCollection
	(AvailableType)(0),                  // 3: takasho.schema.lettuce_server.resource.player_profile.AvailableType
}
var file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_depIdxs = []int32{
	1, // 0: takasho.schema.lettuce_server.resource.player_profile.ProfileSpine.last_logged_in_at:type_name -> google.protobuf.Timestamp
	2, // 1: takasho.schema.lettuce_server.resource.player_profile.ProfileSpine.collection:type_name -> takasho.schema.lettuce_server.resource.collection.MyBestCollection
	3, // 2: takasho.schema.lettuce_server.resource.player_profile.ProfileSpine.available_type:type_name -> takasho.schema.lettuce_server.resource.player_profile.AvailableType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_init() }
func file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_init() {
	if File_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_resource_player_profile_available_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto = out.File
	file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_player_profile_profile_spine_proto_depIdxs = nil
}
