// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/deck/deck_slot.proto

package deck

import (
	card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotNumber    uint64                 `protobuf:"varint,1,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	CardInstance  *card.CardInstance     `protobuf:"bytes,2,opt,name=card_instance,json=cardInstance,proto3" json:"card_instance,omitempty"`
	MainCardType  DeckMainCardType       `protobuf:"varint,3,opt,name=main_card_type,json=mainCardType,proto3,enum=takasho.schema.lettuce_server.resource.deck.DeckMainCardType" json:"main_card_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckSlot) Reset() {
	*x = DeckSlot{}
	mi := &file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSlot) ProtoMessage() {}

func (x *DeckSlot) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSlot.ProtoReflect.Descriptor instead.
func (*DeckSlot) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescGZIP(), []int{0}
}

func (x *DeckSlot) GetSlotNumber() uint64 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

func (x *DeckSlot) GetCardInstance() *card.CardInstance {
	if x != nil {
		return x.CardInstance
	}
	return nil
}

func (x *DeckSlot) GetMainCardType() DeckMainCardType {
	if x != nil {
		return x.MainCardType
	}
	return DeckMainCardType_DECK_MAIN_CARD_TYPE_UNSPECIFIED
}

var File_takasho_schema_lettuce_server_resource_deck_deck_slot_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDesc = "" +
	"\n" +
	";takasho/schema/lettuce_server/resource/deck/deck_slot.proto\x12+takasho.schema.lettuce_server.resource.deck\x1a?takasho/schema/lettuce_server/resource/card/card_instance.proto\x1aEtakasho/schema/lettuce_server/resource/deck/deck_main_card_type.proto\"\xf0\x01\n" +
	"\bDeckSlot\x12\x1f\n" +
	"\vslot_number\x18\x01 \x01(\x04R\n" +
	"slotNumber\x12^\n" +
	"\rcard_instance\x18\x02 \x01(\v29.takasho.schema.lettuce_server.resource.card.CardInstanceR\fcardInstance\x12c\n" +
	"\x0emain_card_type\x18\x03 \x01(\x0e2=.takasho.schema.lettuce_server.resource.deck.DeckMainCardTypeR\fmainCardTypeBlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/deck;deckb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_goTypes = []any{
	(*DeckSlot)(nil),          // 0: takasho.schema.lettuce_server.resource.deck.DeckSlot
	(*card.CardInstance)(nil), // 1: takasho.schema.lettuce_server.resource.card.CardInstance
	(DeckMainCardType)(0),     // 2: takasho.schema.lettuce_server.resource.deck.DeckMainCardType
}
var file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_depIdxs = []int32{
	1, // 0: takasho.schema.lettuce_server.resource.deck.DeckSlot.card_instance:type_name -> takasho.schema.lettuce_server.resource.card.CardInstance
	2, // 1: takasho.schema.lettuce_server.resource.deck.DeckSlot.main_card_type:type_name -> takasho.schema.lettuce_server.resource.deck.DeckMainCardType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_init() }
func file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_init() {
	if File_takasho_schema_lettuce_server_resource_deck_deck_slot_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_resource_deck_deck_main_card_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_deck_deck_slot_proto = out.File
	file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_deck_deck_slot_proto_depIdxs = nil
}
