// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/item/card_instance.proto

package item

import (
	card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardInstance  *card.CardInstance     `protobuf:"bytes,1,opt,name=card_instance,json=cardInstance,proto3" json:"card_instance,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInstance) Reset() {
	*x = CardInstance{}
	mi := &file_takasho_schema_lettuce_server_resource_item_card_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInstance) ProtoMessage() {}

func (x *CardInstance) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_item_card_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInstance.ProtoReflect.Descriptor instead.
func (*CardInstance) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescGZIP(), []int{0}
}

func (x *CardInstance) GetCardInstance() *card.CardInstance {
	if x != nil {
		return x.CardInstance
	}
	return nil
}

func (x *CardInstance) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_takasho_schema_lettuce_server_resource_item_card_instance_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDesc = "" +
	"\n" +
	"?takasho/schema/lettuce_server/resource/item/card_instance.proto\x12+takasho.schema.lettuce_server.resource.item\x1a?takasho/schema/lettuce_server/resource/card/card_instance.proto\"\x86\x01\n" +
	"\fCardInstance\x12^\n" +
	"\rcard_instance\x18\x01 \x01(\v29.takasho.schema.lettuce_server.resource.card.CardInstanceR\fcardInstance\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amountBlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/item;itemb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_item_card_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_item_card_instance_proto_goTypes = []any{
	(*CardInstance)(nil),      // 0: takasho.schema.lettuce_server.resource.item.CardInstance
	(*card.CardInstance)(nil), // 1: takasho.schema.lettuce_server.resource.card.CardInstance
}
var file_takasho_schema_lettuce_server_resource_item_card_instance_proto_depIdxs = []int32{
	1, // 0: takasho.schema.lettuce_server.resource.item.CardInstance.card_instance:type_name -> takasho.schema.lettuce_server.resource.card.CardInstance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_item_card_instance_proto_init() }
func file_takasho_schema_lettuce_server_resource_item_card_instance_proto_init() {
	if File_takasho_schema_lettuce_server_resource_item_card_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_card_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_item_card_instance_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_item_card_instance_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_item_card_instance_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_item_card_instance_proto = out.File
	file_takasho_schema_lettuce_server_resource_item_card_instance_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_item_card_instance_proto_depIdxs = nil
}
