// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/item/currency.proto

package item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency_Types_Type int32

const (
	Currency_Types_TYPE_UNSPECIFIED         Currency_Types_Type = 0
	Currency_Types_TYPE_SHOP_TICKET         Currency_Types_Type = 3
	Currency_Types_TYPE_BRIGHT_SAND         Currency_Types_Type = 4
	Currency_Types_TYPE_PREMIER_SHOP_TICKET Currency_Types_Type = 5
	Currency_Types_TYPE_SUBSCRIPTION_TICKET Currency_Types_Type = 6
)

// Enum value maps for Currency_Types_Type.
var (
	Currency_Types_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		3: "TYPE_SHOP_TICKET",
		4: "TYPE_BRIGHT_SAND",
		5: "TYPE_PREMIER_SHOP_TICKET",
		6: "TYPE_SUBSCRIPTION_TICKET",
	}
	Currency_Types_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":         0,
		"TYPE_SHOP_TICKET":         3,
		"TYPE_BRIGHT_SAND":         4,
		"TYPE_PREMIER_SHOP_TICKET": 5,
		"TYPE_SUBSCRIPTION_TICKET": 6,
	}
)

func (x Currency_Types_Type) Enum() *Currency_Types_Type {
	p := new(Currency_Types_Type)
	*p = x
	return p
}

func (x Currency_Types_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency_Types_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_takasho_schema_lettuce_server_resource_item_currency_proto_enumTypes[0].Descriptor()
}

func (Currency_Types_Type) Type() protoreflect.EnumType {
	return &file_takasho_schema_lettuce_server_resource_item_currency_proto_enumTypes[0]
}

func (x Currency_Types_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency_Types_Type.Descriptor instead.
func (Currency_Types_Type) EnumDescriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Currency_Types_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=takasho.schema.lettuce_server.resource.item.Currency_Types_Type" json:"type,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetType() Currency_Types_Type {
	if x != nil {
		return x.Type
	}
	return Currency_Types_TYPE_UNSPECIFIED
}

func (x *Currency) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Currency_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency_Types) Reset() {
	*x = Currency_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency_Types) ProtoMessage() {}

func (x *Currency_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency_Types.ProtoReflect.Descriptor instead.
func (*Currency_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescGZIP(), []int{0, 0}
}

var File_takasho_schema_lettuce_server_resource_item_currency_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDesc = "" +
	"\n" +
	":takasho/schema/lettuce_server/resource/item/currency.proto\x12+takasho.schema.lettuce_server.resource.item\"\x89\x02\n" +
	"\bCurrency\x12T\n" +
	"\x04type\x18\x01 \x01(\x0e2@.takasho.schema.lettuce_server.resource.item.Currency.Types.TypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x1a\x8e\x01\n" +
	"\x05Types\"\x84\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TYPE_SHOP_TICKET\x10\x03\x12\x14\n" +
	"\x10TYPE_BRIGHT_SAND\x10\x04\x12\x1c\n" +
	"\x18TYPE_PREMIER_SHOP_TICKET\x10\x05\x12\x1c\n" +
	"\x18TYPE_SUBSCRIPTION_TICKET\x10\x06BlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/item;itemb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_item_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_takasho_schema_lettuce_server_resource_item_currency_proto_goTypes = []any{
	(Currency_Types_Type)(0), // 0: takasho.schema.lettuce_server.resource.item.Currency.Types.Type
	(*Currency)(nil),         // 1: takasho.schema.lettuce_server.resource.item.Currency
	(*Currency_Types)(nil),   // 2: takasho.schema.lettuce_server.resource.item.Currency.Types
}
var file_takasho_schema_lettuce_server_resource_item_currency_proto_depIdxs = []int32{
	0, // 0: takasho.schema.lettuce_server.resource.item.Currency.type:type_name -> takasho.schema.lettuce_server.resource.item.Currency.Types.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_item_currency_proto_init() }
func file_takasho_schema_lettuce_server_resource_item_currency_proto_init() {
	if File_takasho_schema_lettuce_server_resource_item_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_item_currency_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_item_currency_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_item_currency_proto_depIdxs,
		EnumInfos:         file_takasho_schema_lettuce_server_resource_item_currency_proto_enumTypes,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_item_currency_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_item_currency_proto = out.File
	file_takasho_schema_lettuce_server_resource_item_currency_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_item_currency_proto_depIdxs = nil
}
