// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/pack/pack_detail.proto

package pack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackDetail struct {
	state            protoimpl.MessageState                 `protogen:"open.v1"`
	PackId           string                                 `protobuf:"bytes,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	ExpansionId      string                                 `protobuf:"bytes,2,opt,name=expansion_id,json=expansionId,proto3" json:"expansion_id,omitempty"`
	PackTableWeights []*PackDetail_Types_PackTableWeight    `protobuf:"bytes,4,rep,name=pack_table_weights,json=packTableWeights,proto3" json:"pack_table_weights,omitempty"`
	PackTables       map[string]*PackDetail_Types_PackTable `protobuf:"bytes,5,rep,name=pack_tables,json=packTables,proto3" json:"pack_tables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PackDetail) Reset() {
	*x = PackDetail{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail) ProtoMessage() {}

func (x *PackDetail) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail.ProtoReflect.Descriptor instead.
func (*PackDetail) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0}
}

func (x *PackDetail) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *PackDetail) GetExpansionId() string {
	if x != nil {
		return x.ExpansionId
	}
	return ""
}

func (x *PackDetail) GetPackTableWeights() []*PackDetail_Types_PackTableWeight {
	if x != nil {
		return x.PackTableWeights
	}
	return nil
}

func (x *PackDetail) GetPackTables() map[string]*PackDetail_Types_PackTable {
	if x != nil {
		return x.PackTables
	}
	return nil
}

type PackDetail_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types) Reset() {
	*x = PackDetail_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types) ProtoMessage() {}

func (x *PackDetail_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types.ProtoReflect.Descriptor instead.
func (*PackDetail_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0}
}

type PackDetail_Types_PackTableWeight struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PackTableId       string                 `protobuf:"bytes,1,opt,name=pack_table_id,json=packTableId,proto3" json:"pack_table_id,omitempty"`
	ProbabilityString string                 `protobuf:"bytes,4,opt,name=probability_string,json=probabilityString,proto3" json:"probability_string,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTableWeight) Reset() {
	*x = PackDetail_Types_PackTableWeight{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTableWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTableWeight) ProtoMessage() {}

func (x *PackDetail_Types_PackTableWeight) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTableWeight.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTableWeight) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PackDetail_Types_PackTableWeight) GetPackTableId() string {
	if x != nil {
		return x.PackTableId
	}
	return ""
}

func (x *PackDetail_Types_PackTableWeight) GetProbabilityString() string {
	if x != nil {
		return x.ProbabilityString
	}
	return ""
}

type PackDetail_Types_PackTable struct {
	state               protoimpl.MessageState                                 `protogen:"open.v1"`
	PackTableId         string                                                 `protobuf:"bytes,1,opt,name=pack_table_id,json=packTableId,proto3" json:"pack_table_id,omitempty"`
	DrawCountLabels     []string                                               `protobuf:"bytes,2,rep,name=draw_count_labels,json=drawCountLabels,proto3" json:"draw_count_labels,omitempty"`
	DrawCountCardTables map[string]*PackDetail_Types_PackTable_Types_CardTable `protobuf:"bytes,3,rep,name=draw_count_card_tables,json=drawCountCardTables,proto3" json:"draw_count_card_tables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable) Reset() {
	*x = PackDetail_Types_PackTable{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable) ProtoMessage() {}

func (x *PackDetail_Types_PackTable) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *PackDetail_Types_PackTable) GetPackTableId() string {
	if x != nil {
		return x.PackTableId
	}
	return ""
}

func (x *PackDetail_Types_PackTable) GetDrawCountLabels() []string {
	if x != nil {
		return x.DrawCountLabels
	}
	return nil
}

func (x *PackDetail_Types_PackTable) GetDrawCountCardTables() map[string]*PackDetail_Types_PackTable_Types_CardTable {
	if x != nil {
		return x.DrawCountCardTables
	}
	return nil
}

type PackDetail_Types_PackTable_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types) Reset() {
	*x = PackDetail_Types_PackTable_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

type PackDetail_Types_PackTable_Types_CardTable struct {
	state         protoimpl.MessageState                                                           `protogen:"open.v1"`
	LabelWeights  []*PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight                  `protobuf:"bytes,1,rep,name=label_weights,json=labelWeights,proto3" json:"label_weights,omitempty"`
	LabelItems    map[string]*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems `protobuf:"bytes,2,rep,name=label_items,json=labelItems,proto3" json:"label_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types_CardTable) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0}
}

func (x *PackDetail_Types_PackTable_Types_CardTable) GetLabelWeights() []*PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight {
	if x != nil {
		return x.LabelWeights
	}
	return nil
}

func (x *PackDetail_Types_PackTable_Types_CardTable) GetLabelItems() map[string]*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems {
	if x != nil {
		return x.LabelItems
	}
	return nil
}

type PackDetail_Types_PackTable_Types_CardTable_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable_Types) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable_Types.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0}
}

type PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems struct {
	state         protoimpl.MessageState                                                                   `protogen:"open.v1"`
	CardWeights   []*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight `protobuf:"bytes,1,rep,name=card_weights,json=cardWeights,proto3" json:"card_weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0, 0}
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems) GetCardWeights() []*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight {
	if x != nil {
		return x.CardWeights
	}
	return nil
}

type PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Label             string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ProbabilityString string                 `protobuf:"bytes,4,opt,name=probability_string,json=probabilityString,proto3" json:"probability_string,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0, 1}
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight) GetProbabilityString() string {
	if x != nil {
		return x.ProbabilityString
	}
	return ""
}

type PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types) ProtoMessage() {}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0, 0, 0}
}

type PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CardId            string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	ProbabilityString string                 `protobuf:"bytes,4,opt,name=probability_string,json=probabilityString,proto3" json:"probability_string,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) Reset() {
	*x = PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight{}
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) ProtoMessage() {
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight.ProtoReflect.Descriptor instead.
func (*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0, 0, 0, 0}
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight) GetProbabilityString() string {
	if x != nil {
		return x.ProbabilityString
	}
	return ""
}

var File_takasho_schema_lettuce_server_resource_pack_pack_detail_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDesc = "" +
	"\n" +
	"=takasho/schema/lettuce_server/resource/pack/pack_detail.proto\x12+takasho.schema.lettuce_server.resource.pack\"\xa6\x0e\n" +
	"\n" +
	"PackDetail\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12!\n" +
	"\fexpansion_id\x18\x02 \x01(\tR\vexpansionId\x12{\n" +
	"\x12pack_table_weights\x18\x04 \x03(\v2M.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTableWeightR\x10packTableWeights\x12h\n" +
	"\vpack_tables\x18\x05 \x03(\v2G.takasho.schema.lettuce_server.resource.pack.PackDetail.PackTablesEntryR\n" +
	"packTables\x1a\xeb\n" +
	"\n" +
	"\x05Types\x1ad\n" +
	"\x0fPackTableWeight\x12\"\n" +
	"\rpack_table_id\x18\x01 \x01(\tR\vpackTableId\x12-\n" +
	"\x12probability_string\x18\x04 \x01(\tR\x11probabilityString\x1a\xfb\t\n" +
	"\tPackTable\x12\"\n" +
	"\rpack_table_id\x18\x01 \x01(\tR\vpackTableId\x12*\n" +
	"\x11draw_count_labels\x18\x02 \x03(\tR\x0fdrawCountLabels\x12\x95\x01\n" +
	"\x16draw_count_card_tables\x18\x03 \x03(\v2`.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.DrawCountCardTablesEntryR\x13drawCountCardTables\x1a\xe3\x06\n" +
	"\x05Types\x1a\xd9\x06\n" +
	"\tCardTable\x12\x8e\x01\n" +
	"\rlabel_weights\x18\x01 \x03(\v2i.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.LabelWeightR\flabelWeights\x12\x88\x01\n" +
	"\vlabel_items\x18\x02 \x03(\v2g.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.LabelItemsEntryR\n" +
	"labelItems\x1a\xfb\x02\n" +
	"\x05Types\x1a\x9d\x02\n" +
	"\x13CardTableLabelItems\x12\xa6\x01\n" +
	"\fcard_weights\x18\x01 \x03(\v2\x82\x01.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems.Types.CardWeightR\vcardWeights\x1a]\n" +
	"\x05Types\x1aT\n" +
	"\n" +
	"CardWeight\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12-\n" +
	"\x12probability_string\x18\x04 \x01(\tR\x11probabilityString\x1aR\n" +
	"\vLabelWeight\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12-\n" +
	"\x12probability_string\x18\x04 \x01(\tR\x11probabilityString\x1a\xb1\x01\n" +
	"\x0fLabelItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x87\x01\n" +
	"\x05value\x18\x02 \x01(\v2q.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItemsR\x05value:\x028\x01\x1a\x9f\x01\n" +
	"\x18DrawCountCardTablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12m\n" +
	"\x05value\x18\x02 \x01(\v2W.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTableR\x05value:\x028\x01\x1a\x86\x01\n" +
	"\x0fPackTablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12]\n" +
	"\x05value\x18\x02 \x01(\v2G.takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTableR\x05value:\x028\x01BlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/pack;packb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_goTypes = []any{
	(*PackDetail)(nil),                       // 0: takasho.schema.lettuce_server.resource.pack.PackDetail
	(*PackDetail_Types)(nil),                 // 1: takasho.schema.lettuce_server.resource.pack.PackDetail.Types
	nil,                                      // 2: takasho.schema.lettuce_server.resource.pack.PackDetail.PackTablesEntry
	(*PackDetail_Types_PackTableWeight)(nil), // 3: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTableWeight
	(*PackDetail_Types_PackTable)(nil),       // 4: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable
	(*PackDetail_Types_PackTable_Types)(nil), // 5: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types
	nil,                                      // 6: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.DrawCountCardTablesEntry
	(*PackDetail_Types_PackTable_Types_CardTable)(nil),       // 7: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable
	(*PackDetail_Types_PackTable_Types_CardTable_Types)(nil), // 8: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types
	nil, // 9: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.LabelItemsEntry
	(*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems)(nil),                  // 10: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems
	(*PackDetail_Types_PackTable_Types_CardTable_Types_LabelWeight)(nil),                          // 11: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.LabelWeight
	(*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types)(nil),            // 12: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems.Types
	(*PackDetail_Types_PackTable_Types_CardTable_Types_CardTableLabelItems_Types_CardWeight)(nil), // 13: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems.Types.CardWeight
}
var file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_depIdxs = []int32{
	3,  // 0: takasho.schema.lettuce_server.resource.pack.PackDetail.pack_table_weights:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTableWeight
	2,  // 1: takasho.schema.lettuce_server.resource.pack.PackDetail.pack_tables:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.PackTablesEntry
	4,  // 2: takasho.schema.lettuce_server.resource.pack.PackDetail.PackTablesEntry.value:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable
	6,  // 3: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.draw_count_card_tables:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.DrawCountCardTablesEntry
	7,  // 4: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.DrawCountCardTablesEntry.value:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable
	11, // 5: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.label_weights:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.LabelWeight
	9,  // 6: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.label_items:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.LabelItemsEntry
	10, // 7: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.LabelItemsEntry.value:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems
	13, // 8: takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems.card_weights:type_name -> takasho.schema.lettuce_server.resource.pack.PackDetail.Types.PackTable.Types.CardTable.Types.CardTableLabelItems.Types.CardWeight
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_init() }
func file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_init() {
	if File_takasho_schema_lettuce_server_resource_pack_pack_detail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_pack_pack_detail_proto = out.File
	file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_pack_pack_detail_proto_depIdxs = nil
}
