// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/player_resources/player_resources.proto

package player_resources

import (
	card "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card"
	card_frame "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card_frame"
	card_skin "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/card_skin"
	item "github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/item"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerResources struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	CardStocks             []*card.CardStock             `protobuf:"bytes,1,rep,name=card_stocks,json=cardStocks,proto3" json:"card_stocks,omitempty"`
	CardSkinStocks         []*card_skin.CardSkinStock    `protobuf:"bytes,2,rep,name=card_skin_stocks,json=cardSkinStocks,proto3" json:"card_skin_stocks,omitempty"`
	PackPowerChargers      []*item.PackPowerCharger      `protobuf:"bytes,3,rep,name=pack_power_chargers,json=packPowerChargers,proto3" json:"pack_power_chargers,omitempty"`
	ChallengePowerChargers []*item.ChallengePowerCharger `protobuf:"bytes,4,rep,name=challenge_power_chargers,json=challengePowerChargers,proto3" json:"challenge_power_chargers,omitempty"`
	PeripheralGoods        []*item.PeripheralGoods       `protobuf:"bytes,5,rep,name=peripheral_goods,json=peripheralGoods,proto3" json:"peripheral_goods,omitempty"`
	Currencies             []*item.Currency              `protobuf:"bytes,6,rep,name=currencies,proto3" json:"currencies,omitempty"`
	ProfileDecorations     []*item.ProfileDecoration     `protobuf:"bytes,7,rep,name=profile_decorations,json=profileDecorations,proto3" json:"profile_decorations,omitempty"`
	RewardTickets          []*item.RewardTicket          `protobuf:"bytes,8,rep,name=reward_tickets,json=rewardTickets,proto3" json:"reward_tickets,omitempty"`
	RevivalClocks          []*item.RevivalClock          `protobuf:"bytes,9,rep,name=revival_clocks,json=revivalClocks,proto3" json:"revival_clocks,omitempty"`
	RentalDecks            []*item.RentalDeck            `protobuf:"bytes,10,rep,name=rental_decks,json=rentalDecks,proto3" json:"rental_decks,omitempty"`
	ThemeDeckRecipes       []*item.ThemeDeckRecipe       `protobuf:"bytes,11,rep,name=theme_deck_recipes,json=themeDeckRecipes,proto3" json:"theme_deck_recipes,omitempty"`
	EventPowerChargers     []*item.EventPowerCharger     `protobuf:"bytes,12,rep,name=event_power_chargers,json=eventPowerChargers,proto3" json:"event_power_chargers,omitempty"`
	PackCeilPoints         []*item.PackCeilPoint         `protobuf:"bytes,13,rep,name=pack_ceil_points,json=packCeilPoints,proto3" json:"pack_ceil_points,omitempty"`
	ExpStock               *item.ExpStock                `protobuf:"bytes,14,opt,name=exp_stock,json=expStock,proto3" json:"exp_stock,omitempty"`
	TradePowerChargers     []*item.TradePowerCharger     `protobuf:"bytes,15,rep,name=trade_power_chargers,json=tradePowerChargers,proto3" json:"trade_power_chargers,omitempty"`
	TradeItems             []*item.TradeItem             `protobuf:"bytes,16,rep,name=trade_items,json=tradeItems,proto3" json:"trade_items,omitempty"`
	TradeTickets           []*item.TradeTicket           `protobuf:"bytes,19,rep,name=trade_tickets,json=tradeTickets,proto3" json:"trade_tickets,omitempty"`
	CardFrameStocks        []*card_frame.CardFrameStock  `protobuf:"bytes,20,rep,name=card_frame_stocks,json=cardFrameStocks,proto3" json:"card_frame_stocks,omitempty"`
	PackGuaranteePoints    []*item.PackGuaranteePoint    `protobuf:"bytes,21,rep,name=pack_guarantee_points,json=packGuaranteePoints,proto3" json:"pack_guarantee_points,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlayerResources) Reset() {
	*x = PlayerResources{}
	mi := &file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResources) ProtoMessage() {}

func (x *PlayerResources) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResources.ProtoReflect.Descriptor instead.
func (*PlayerResources) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerResources) GetCardStocks() []*card.CardStock {
	if x != nil {
		return x.CardStocks
	}
	return nil
}

func (x *PlayerResources) GetCardSkinStocks() []*card_skin.CardSkinStock {
	if x != nil {
		return x.CardSkinStocks
	}
	return nil
}

func (x *PlayerResources) GetPackPowerChargers() []*item.PackPowerCharger {
	if x != nil {
		return x.PackPowerChargers
	}
	return nil
}

func (x *PlayerResources) GetChallengePowerChargers() []*item.ChallengePowerCharger {
	if x != nil {
		return x.ChallengePowerChargers
	}
	return nil
}

func (x *PlayerResources) GetPeripheralGoods() []*item.PeripheralGoods {
	if x != nil {
		return x.PeripheralGoods
	}
	return nil
}

func (x *PlayerResources) GetCurrencies() []*item.Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *PlayerResources) GetProfileDecorations() []*item.ProfileDecoration {
	if x != nil {
		return x.ProfileDecorations
	}
	return nil
}

func (x *PlayerResources) GetRewardTickets() []*item.RewardTicket {
	if x != nil {
		return x.RewardTickets
	}
	return nil
}

func (x *PlayerResources) GetRevivalClocks() []*item.RevivalClock {
	if x != nil {
		return x.RevivalClocks
	}
	return nil
}

func (x *PlayerResources) GetRentalDecks() []*item.RentalDeck {
	if x != nil {
		return x.RentalDecks
	}
	return nil
}

func (x *PlayerResources) GetThemeDeckRecipes() []*item.ThemeDeckRecipe {
	if x != nil {
		return x.ThemeDeckRecipes
	}
	return nil
}

func (x *PlayerResources) GetEventPowerChargers() []*item.EventPowerCharger {
	if x != nil {
		return x.EventPowerChargers
	}
	return nil
}

func (x *PlayerResources) GetPackCeilPoints() []*item.PackCeilPoint {
	if x != nil {
		return x.PackCeilPoints
	}
	return nil
}

func (x *PlayerResources) GetExpStock() *item.ExpStock {
	if x != nil {
		return x.ExpStock
	}
	return nil
}

func (x *PlayerResources) GetTradePowerChargers() []*item.TradePowerCharger {
	if x != nil {
		return x.TradePowerChargers
	}
	return nil
}

func (x *PlayerResources) GetTradeItems() []*item.TradeItem {
	if x != nil {
		return x.TradeItems
	}
	return nil
}

func (x *PlayerResources) GetTradeTickets() []*item.TradeTicket {
	if x != nil {
		return x.TradeTickets
	}
	return nil
}

func (x *PlayerResources) GetCardFrameStocks() []*card_frame.CardFrameStock {
	if x != nil {
		return x.CardFrameStocks
	}
	return nil
}

func (x *PlayerResources) GetPackGuaranteePoints() []*item.PackGuaranteePoint {
	if x != nil {
		return x.PackGuaranteePoints
	}
	return nil
}

var File_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDesc = "" +
	"\n" +
	"Ntakasho/schema/lettuce_server/resource/player_resources/player_resources.proto\x127takasho.schema.lettuce_server.resource.player_resources\x1a<takasho/schema/lettuce_server/resource/card/card_stock.proto\x1aHtakasho/schema/lettuce_server/resource/card_frame/card_frame_stock.proto\x1aFtakasho/schema/lettuce_server/resource/card_skin/card_skin_stock.proto\x1aItakasho/schema/lettuce_server/resource/item/challenge_power_charger.proto\x1a:takasho/schema/lettuce_server/resource/item/currency.proto\x1aEtakasho/schema/lettuce_server/resource/item/event_power_charger.proto\x1a;takasho/schema/lettuce_server/resource/item/exp_stock.proto\x1aAtakasho/schema/lettuce_server/resource/item/pack_ceil_point.proto\x1aFtakasho/schema/lettuce_server/resource/item/pack_guarantee_point.proto\x1aDtakasho/schema/lettuce_server/resource/item/pack_power_charger.proto\x1aBtakasho/schema/lettuce_server/resource/item/peripheral_goods.proto\x1aDtakasho/schema/lettuce_server/resource/item/profile_decoration.proto\x1a=takasho/schema/lettuce_server/resource/item/rental_deck.proto\x1a?takasho/schema/lettuce_server/resource/item/revival_clock.proto\x1a?takasho/schema/lettuce_server/resource/item/reward_ticket.proto\x1aCtakasho/schema/lettuce_server/resource/item/theme_deck_recipe.proto\x1a<takasho/schema/lettuce_server/resource/item/trade_item.proto\x1aEtakasho/schema/lettuce_server/resource/item/trade_power_charger.proto\x1a>takasho/schema/lettuce_server/resource/item/trade_ticket.proto\"\xb9\x0f\n" +
	"\x0fPlayerResources\x12W\n" +
	"\vcard_stocks\x18\x01 \x03(\v26.takasho.schema.lettuce_server.resource.card.CardStockR\n" +
	"cardStocks\x12i\n" +
	"\x10card_skin_stocks\x18\x02 \x03(\v2?.takasho.schema.lettuce_server.resource.card_skin.CardSkinStockR\x0ecardSkinStocks\x12m\n" +
	"\x13pack_power_chargers\x18\x03 \x03(\v2=.takasho.schema.lettuce_server.resource.item.PackPowerChargerR\x11packPowerChargers\x12|\n" +
	"\x18challenge_power_chargers\x18\x04 \x03(\v2B.takasho.schema.lettuce_server.resource.item.ChallengePowerChargerR\x16challengePowerChargers\x12g\n" +
	"\x10peripheral_goods\x18\x05 \x03(\v2<.takasho.schema.lettuce_server.resource.item.PeripheralGoodsR\x0fperipheralGoods\x12U\n" +
	"\n" +
	"currencies\x18\x06 \x03(\v25.takasho.schema.lettuce_server.resource.item.CurrencyR\n" +
	"currencies\x12o\n" +
	"\x13profile_decorations\x18\a \x03(\v2>.takasho.schema.lettuce_server.resource.item.ProfileDecorationR\x12profileDecorations\x12`\n" +
	"\x0ereward_tickets\x18\b \x03(\v29.takasho.schema.lettuce_server.resource.item.RewardTicketR\rrewardTickets\x12`\n" +
	"\x0erevival_clocks\x18\t \x03(\v29.takasho.schema.lettuce_server.resource.item.RevivalClockR\rrevivalClocks\x12Z\n" +
	"\frental_decks\x18\n" +
	" \x03(\v27.takasho.schema.lettuce_server.resource.item.RentalDeckR\vrentalDecks\x12j\n" +
	"\x12theme_deck_recipes\x18\v \x03(\v2<.takasho.schema.lettuce_server.resource.item.ThemeDeckRecipeR\x10themeDeckRecipes\x12p\n" +
	"\x14event_power_chargers\x18\f \x03(\v2>.takasho.schema.lettuce_server.resource.item.EventPowerChargerR\x12eventPowerChargers\x12d\n" +
	"\x10pack_ceil_points\x18\r \x03(\v2:.takasho.schema.lettuce_server.resource.item.PackCeilPointR\x0epackCeilPoints\x12R\n" +
	"\texp_stock\x18\x0e \x01(\v25.takasho.schema.lettuce_server.resource.item.ExpStockR\bexpStock\x12p\n" +
	"\x14trade_power_chargers\x18\x0f \x03(\v2>.takasho.schema.lettuce_server.resource.item.TradePowerChargerR\x12tradePowerChargers\x12W\n" +
	"\vtrade_items\x18\x10 \x03(\v26.takasho.schema.lettuce_server.resource.item.TradeItemR\n" +
	"tradeItems\x12]\n" +
	"\rtrade_tickets\x18\x13 \x03(\v28.takasho.schema.lettuce_server.resource.item.TradeTicketR\ftradeTickets\x12m\n" +
	"\x11card_frame_stocks\x18\x14 \x03(\v2A.takasho.schema.lettuce_server.resource.card_frame.CardFrameStockR\x0fcardFrameStocks\x12s\n" +
	"\x15pack_guarantee_points\x18\x15 \x03(\v2?.takasho.schema.lettuce_server.resource.item.PackGuaranteePointR\x13packGuaranteePointsB\x85\x01Z\x82\x01github.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/player_resources;player_resourcesb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_goTypes = []any{
	(*PlayerResources)(nil),            // 0: takasho.schema.lettuce_server.resource.player_resources.PlayerResources
	(*card.CardStock)(nil),             // 1: takasho.schema.lettuce_server.resource.card.CardStock
	(*card_skin.CardSkinStock)(nil),    // 2: takasho.schema.lettuce_server.resource.card_skin.CardSkinStock
	(*item.PackPowerCharger)(nil),      // 3: takasho.schema.lettuce_server.resource.item.PackPowerCharger
	(*item.ChallengePowerCharger)(nil), // 4: takasho.schema.lettuce_server.resource.item.ChallengePowerCharger
	(*item.PeripheralGoods)(nil),       // 5: takasho.schema.lettuce_server.resource.item.PeripheralGoods
	(*item.Currency)(nil),              // 6: takasho.schema.lettuce_server.resource.item.Currency
	(*item.ProfileDecoration)(nil),     // 7: takasho.schema.lettuce_server.resource.item.ProfileDecoration
	(*item.RewardTicket)(nil),          // 8: takasho.schema.lettuce_server.resource.item.RewardTicket
	(*item.RevivalClock)(nil),          // 9: takasho.schema.lettuce_server.resource.item.RevivalClock
	(*item.RentalDeck)(nil),            // 10: takasho.schema.lettuce_server.resource.item.RentalDeck
	(*item.ThemeDeckRecipe)(nil),       // 11: takasho.schema.lettuce_server.resource.item.ThemeDeckRecipe
	(*item.EventPowerCharger)(nil),     // 12: takasho.schema.lettuce_server.resource.item.EventPowerCharger
	(*item.PackCeilPoint)(nil),         // 13: takasho.schema.lettuce_server.resource.item.PackCeilPoint
	(*item.ExpStock)(nil),              // 14: takasho.schema.lettuce_server.resource.item.ExpStock
	(*item.TradePowerCharger)(nil),     // 15: takasho.schema.lettuce_server.resource.item.TradePowerCharger
	(*item.TradeItem)(nil),             // 16: takasho.schema.lettuce_server.resource.item.TradeItem
	(*item.TradeTicket)(nil),           // 17: takasho.schema.lettuce_server.resource.item.TradeTicket
	(*card_frame.CardFrameStock)(nil),  // 18: takasho.schema.lettuce_server.resource.card_frame.CardFrameStock
	(*item.PackGuaranteePoint)(nil),    // 19: takasho.schema.lettuce_server.resource.item.PackGuaranteePoint
}
var file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_depIdxs = []int32{
	1,  // 0: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.card_stocks:type_name -> takasho.schema.lettuce_server.resource.card.CardStock
	2,  // 1: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.card_skin_stocks:type_name -> takasho.schema.lettuce_server.resource.card_skin.CardSkinStock
	3,  // 2: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.pack_power_chargers:type_name -> takasho.schema.lettuce_server.resource.item.PackPowerCharger
	4,  // 3: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.challenge_power_chargers:type_name -> takasho.schema.lettuce_server.resource.item.ChallengePowerCharger
	5,  // 4: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.peripheral_goods:type_name -> takasho.schema.lettuce_server.resource.item.PeripheralGoods
	6,  // 5: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.currencies:type_name -> takasho.schema.lettuce_server.resource.item.Currency
	7,  // 6: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.profile_decorations:type_name -> takasho.schema.lettuce_server.resource.item.ProfileDecoration
	8,  // 7: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.reward_tickets:type_name -> takasho.schema.lettuce_server.resource.item.RewardTicket
	9,  // 8: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.revival_clocks:type_name -> takasho.schema.lettuce_server.resource.item.RevivalClock
	10, // 9: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.rental_decks:type_name -> takasho.schema.lettuce_server.resource.item.RentalDeck
	11, // 10: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.theme_deck_recipes:type_name -> takasho.schema.lettuce_server.resource.item.ThemeDeckRecipe
	12, // 11: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.event_power_chargers:type_name -> takasho.schema.lettuce_server.resource.item.EventPowerCharger
	13, // 12: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.pack_ceil_points:type_name -> takasho.schema.lettuce_server.resource.item.PackCeilPoint
	14, // 13: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.exp_stock:type_name -> takasho.schema.lettuce_server.resource.item.ExpStock
	15, // 14: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.trade_power_chargers:type_name -> takasho.schema.lettuce_server.resource.item.TradePowerCharger
	16, // 15: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.trade_items:type_name -> takasho.schema.lettuce_server.resource.item.TradeItem
	17, // 16: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.trade_tickets:type_name -> takasho.schema.lettuce_server.resource.item.TradeTicket
	18, // 17: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.card_frame_stocks:type_name -> takasho.schema.lettuce_server.resource.card_frame.CardFrameStock
	19, // 18: takasho.schema.lettuce_server.resource.player_resources.PlayerResources.pack_guarantee_points:type_name -> takasho.schema.lettuce_server.resource.item.PackGuaranteePoint
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() {
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_init()
}
func file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_init() {
	if File_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto = out.File
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_player_resources_player_resources_proto_depIdxs = nil
}
