// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/system/device_info.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      PlatformType           `protobuf:"varint,1,opt,name=platform,proto3,enum=takasho.schema.lettuce_server.resource.system.PlatformType" json:"platform,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_takasho_schema_lettuce_server_resource_system_device_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_system_device_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetPlatform() PlatformType {
	if x != nil {
		return x.Platform
	}
	return PlatformType_PLATFORM_TYPE_UNSPECIFIED
}

func (x *DeviceInfo) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

var File_takasho_schema_lettuce_server_resource_system_device_info_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDesc = "" +
	"\n" +
	"?takasho/schema/lettuce_server/resource/system/device_info.proto\x12-takasho.schema.lettuce_server.resource.system\x1aAtakasho/schema/lettuce_server/resource/system/platform_type.proto\"\x85\x01\n" +
	"\n" +
	"DeviceInfo\x12W\n" +
	"\bplatform\x18\x01 \x01(\x0e2;.takasho.schema.lettuce_server.resource.system.PlatformTypeR\bplatform\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifierBpZngithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/system;systemb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_system_device_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_takasho_schema_lettuce_server_resource_system_device_info_proto_goTypes = []any{
	(*DeviceInfo)(nil), // 0: takasho.schema.lettuce_server.resource.system.DeviceInfo
	(PlatformType)(0),  // 1: takasho.schema.lettuce_server.resource.system.PlatformType
}
var file_takasho_schema_lettuce_server_resource_system_device_info_proto_depIdxs = []int32{
	1, // 0: takasho.schema.lettuce_server.resource.system.DeviceInfo.platform:type_name -> takasho.schema.lettuce_server.resource.system.PlatformType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_system_device_info_proto_init() }
func file_takasho_schema_lettuce_server_resource_system_device_info_proto_init() {
	if File_takasho_schema_lettuce_server_resource_system_device_info_proto != nil {
		return
	}
	file_takasho_schema_lettuce_server_resource_system_platform_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_system_device_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_system_device_info_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_system_device_info_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_system_device_info_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_system_device_info_proto = out.File
	file_takasho_schema_lettuce_server_resource_system_device_info_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_system_device_info_proto_depIdxs = nil
}
