// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: takasho/schema/lettuce_server/resource/feed/card_statistics.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardStatistics struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	CardStates    []*CardStatistics_Types_CardState `protobuf:"bytes,1,rep,name=card_states,json=cardStates,proto3" json:"card_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStatistics) Reset() {
	*x = CardStatistics{}
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStatistics) ProtoMessage() {}

func (x *CardStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStatistics.ProtoReflect.Descriptor instead.
func (*CardStatistics) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *CardStatistics) GetCardStates() []*CardStatistics_Types_CardState {
	if x != nil {
		return x.CardStates
	}
	return nil
}

type CardStatistics_Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStatistics_Types) Reset() {
	*x = CardStatistics_Types{}
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStatistics_Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStatistics_Types) ProtoMessage() {}

func (x *CardStatistics_Types) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStatistics_Types.ProtoReflect.Descriptor instead.
func (*CardStatistics_Types) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescGZIP(), []int{0, 0}
}

type CardStatistics_Types_CardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	GoldEffectFlg bool                   `protobuf:"varint,2,opt,name=gold_effect_flg,json=goldEffectFlg,proto3" json:"gold_effect_flg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardStatistics_Types_CardState) Reset() {
	*x = CardStatistics_Types_CardState{}
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStatistics_Types_CardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStatistics_Types_CardState) ProtoMessage() {}

func (x *CardStatistics_Types_CardState) ProtoReflect() protoreflect.Message {
	mi := &file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStatistics_Types_CardState.ProtoReflect.Descriptor instead.
func (*CardStatistics_Types_CardState) Descriptor() ([]byte, []int) {
	return file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CardStatistics_Types_CardState) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardStatistics_Types_CardState) GetGoldEffectFlg() bool {
	if x != nil {
		return x.GoldEffectFlg
	}
	return false
}

var File_takasho_schema_lettuce_server_resource_feed_card_statistics_proto protoreflect.FileDescriptor

const file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDesc = "" +
	"\n" +
	"Atakasho/schema/lettuce_server/resource/feed/card_statistics.proto\x12+takasho.schema.lettuce_server.resource.feed\"\xd5\x01\n" +
	"\x0eCardStatistics\x12l\n" +
	"\vcard_states\x18\x01 \x03(\v2K.takasho.schema.lettuce_server.resource.feed.CardStatistics.Types.CardStateR\n" +
	"cardStates\x1aU\n" +
	"\x05Types\x1aL\n" +
	"\tCardState\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12&\n" +
	"\x0fgold_effect_flg\x18\x02 \x01(\bR\rgoldEffectFlgBlZjgithub.com/Layen-lang/PTCGP-Private-Server/internal/proto/takasho/schema/lettuce_server/resource/feed;feedb\x06proto3"

var (
	file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescOnce sync.Once
	file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescData []byte
)

func file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescGZIP() []byte {
	file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescOnce.Do(func() {
		file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDesc)))
	})
	return file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDescData
}

var file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_goTypes = []any{
	(*CardStatistics)(nil),                 // 0: takasho.schema.lettuce_server.resource.feed.CardStatistics
	(*CardStatistics_Types)(nil),           // 1: takasho.schema.lettuce_server.resource.feed.CardStatistics.Types
	(*CardStatistics_Types_CardState)(nil), // 2: takasho.schema.lettuce_server.resource.feed.CardStatistics.Types.CardState
}
var file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_depIdxs = []int32{
	2, // 0: takasho.schema.lettuce_server.resource.feed.CardStatistics.card_states:type_name -> takasho.schema.lettuce_server.resource.feed.CardStatistics.Types.CardState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_init() }
func file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_init() {
	if File_takasho_schema_lettuce_server_resource_feed_card_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDesc), len(file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_goTypes,
		DependencyIndexes: file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_depIdxs,
		MessageInfos:      file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_msgTypes,
	}.Build()
	File_takasho_schema_lettuce_server_resource_feed_card_statistics_proto = out.File
	file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_goTypes = nil
	file_takasho_schema_lettuce_server_resource_feed_card_statistics_proto_depIdxs = nil
}
